
# Project Vehicle Crash - Modeling Approach Part I

*Note: This code is for modeling on Vehicle Crash data of year 2007-2017 from Pennsylvania Department of Transportation (Penn DOT). See more details here - https://www.opendataphilly.org/dataset/vehicular-crash-data*

* _Author: Daniel Hu (<font color='blue'>daniel.hu2001@gmail.com</font>)_
* _Testing Environment: Python 3.7 on Mac OS_
* _Date: 06/30/2019_

>__Table of Contents__
- [Read input data](#Read-input-data)
- [crash level data](#crash)
- [roadway data](#roadway)
- [vehicle data](#vehicle)
- [person data](#person)
- [master data](#master)

# Step 1. Import packages and setup

In [1]:
# python packages
import pandas as pd
import numpy as np
import math
import time
import subprocess as sbp
import os

# visualization
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set(style="whitegrid", color_codes=True)
import gmplot

# ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# dos command to check pyhon version
!python --version

Python 3.7.3

In [3]:
# package versions

print("pandas version: {0}".format(pd.__version__))
print("numpy version: {0}".format(np.__version__))

pandas version: 0.24.2
numpy version: 1.15.0

 <a id='Read-input-data'> </a>
 # Step 2. Read Input Data

## 2.1 Load raw data

In [4]:
# confirm working directory
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
# crash data

df_crash_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2007_Philadelphia.csv')
df_crash_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2008_Philadelphia.csv')
df_crash_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2009_Philadelphia.csv')
df_crash_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2010_Philadelphia.csv')
df_crash_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2011_Philadelphia.csv')
df_crash_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2012_Philadelphia.csv')
df_crash_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2013_Philadelphia.csv')
df_crash_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2014_Philadelphia.csv')
df_crash_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2015_Philadelphia.csv')
df_crash_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CRASH_2016_Philadelphia.csv')
df_crash_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_CRASH_2017.csv')

In [5]:
df_crash_07_17 = pd.concat([df_crash_2007
                            ,df_crash_2008
                            ,df_crash_2009
                            ,df_crash_2010
                            ,df_crash_2011
                            ,df_crash_2012
                            ,df_crash_2013
                            ,df_crash_2014
                            ,df_crash_2015
                            ,df_crash_2016
                            ,df_crash_2017])

In [6]:
# commercial vehicle

df_commveh_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2007_Philadelphia.csv')
df_commveh_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2008_Philadelphia.csv')
df_commveh_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2009_Philadelphia.csv')
df_commveh_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2010_Philadelphia.csv')
df_commveh_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2011_Philadelphia.csv')
df_commveh_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2012_Philadelphia.csv')
df_commveh_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2013_Philadelphia.csv')
df_commveh_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2014_Philadelphia.csv')
df_commveh_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2015_Philadelphia.csv')
df_commveh_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\COMMVEH_2016_Philadelphia.csv')
df_commveh_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_COMMVEH_2017.csv')

In [7]:
df_commveh_07_17 = pd.concat([df_commveh_2007
                              ,df_commveh_2008
                              ,df_commveh_2009
                              ,df_commveh_2010
                              ,df_commveh_2011
                              ,df_commveh_2012
                              ,df_commveh_2013
                              ,df_commveh_2014
                              ,df_commveh_2015
                              ,df_commveh_2016
                              ,df_commveh_2017])

In [8]:
# cycle

df_cycle_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2007_Philadelphia.csv')
df_cycle_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2008_Philadelphia.csv')
df_cycle_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2009_Philadelphia.csv')
df_cycle_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2010_Philadelphia.csv')
df_cycle_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2011_Philadelphia.csv')
df_cycle_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2012_Philadelphia.csv')
df_cycle_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2013_Philadelphia.csv')
df_cycle_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2014_Philadelphia.csv')
df_cycle_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2015_Philadelphia.csv')
df_cycle_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\CYCLE_2016_Philadelphia.csv')
df_cycle_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_CYCLE_2017.csv')

In [9]:
df_cycle_07_17 = pd.concat([df_cycle_2007
                            ,df_cycle_2008
                            ,df_cycle_2009
                            ,df_cycle_2010
                            ,df_cycle_2011
                            ,df_cycle_2012
                            ,df_cycle_2013
                            ,df_cycle_2014
                            ,df_cycle_2015
                            ,df_cycle_2016
                            ,df_cycle_2017])

In [10]:
# flag

df_flag_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2007_Philadelphia.csv')
df_flag_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2008_Philadelphia.csv')
df_flag_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2009_Philadelphia.csv')
df_flag_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2010_Philadelphia.csv')
df_flag_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2011_Philadelphia.csv')
df_flag_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2012_Philadelphia.csv')
df_flag_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2013_Philadelphia.csv')
df_flag_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2014_Philadelphia.csv')
df_flag_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2015_Philadelphia.csv')
df_flag_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\FLAG_2016_Philadelphia.csv')
df_flag_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_FLAG_2017.csv')

In [11]:
df_flag_07_17 = pd.concat([df_flag_2007
                            ,df_flag_2008
                            ,df_flag_2009
                            ,df_flag_2010
                            ,df_flag_2011
                            ,df_flag_2012
                            ,df_flag_2013
                            ,df_flag_2014
                            ,df_flag_2015
                            ,df_flag_2016
                            ,df_flag_2017])

In [12]:
# person

df_person_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2007_Philadelphia.csv')
df_person_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2008_Philadelphia.csv')
df_person_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2009_Philadelphia.csv')
df_person_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2010_Philadelphia.csv')
df_person_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2011_Philadelphia.csv')
df_person_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2012_Philadelphia.csv')
df_person_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2013_Philadelphia.csv')
df_person_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2014_Philadelphia.csv')
df_person_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2015_Philadelphia.csv')
df_person_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\PERSON_2016_Philadelphia.csv')
df_person_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_PERSON_2017.csv')

In [13]:
df_person_07_17 = pd.concat([df_person_2007
                            ,df_person_2008
                            ,df_person_2009
                            ,df_person_2010
                            ,df_person_2011
                            ,df_person_2012
                            ,df_person_2013
                            ,df_person_2014
                            ,df_person_2015
                            ,df_person_2016
                            ,df_person_2017])

In [14]:
# roadway

df_roadway_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2007_Philadelphia.csv')
df_roadway_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2008_Philadelphia.csv')
df_roadway_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2009_Philadelphia.csv')
df_roadway_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2010_Philadelphia.csv')
df_roadway_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2011_Philadelphia.csv')
df_roadway_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2012_Philadelphia.csv')
df_roadway_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2013_Philadelphia.csv')
df_roadway_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2014_Philadelphia.csv')
df_roadway_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2015_Philadelphia.csv')
df_roadway_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\ROADWAY_2016_Philadelphia.csv')
df_roadway_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_ROADWAY_2017.csv')

In [15]:
df_roadway_07_17 = pd.concat([df_roadway_2007
                            ,df_roadway_2008
                            ,df_roadway_2009
                            ,df_roadway_2010
                            ,df_roadway_2011
                            ,df_roadway_2012
                            ,df_roadway_2013
                            ,df_roadway_2014
                            ,df_roadway_2015
                            ,df_roadway_2016
                            ,df_roadway_2017])

In [16]:
# trailer vehicle

df_trailveh_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2007_Philadelphia.csv')
df_trailveh_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2008_Philadelphia.csv')
df_trailveh_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2009_Philadelphia.csv')
df_trailveh_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2010_Philadelphia.csv')
df_trailveh_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2011_Philadelphia.csv')
df_trailveh_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2012_Philadelphia.csv')
df_trailveh_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2013_Philadelphia.csv')
df_trailveh_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2014_Philadelphia.csv')
df_trailveh_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2015_Philadelphia.csv')
df_trailveh_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\TRAILVEH_2016_Philadelphia.csv')
df_trailveh_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_TREILVEH_2017.csv')

In [17]:
df_trailveh_07_17 = pd.concat([df_trailveh_2007
                            ,df_trailveh_2008
                            ,df_trailveh_2009
                            ,df_trailveh_2010
                            ,df_trailveh_2011
                            ,df_trailveh_2012
                            ,df_trailveh_2013
                            ,df_trailveh_2014
                            ,df_trailveh_2015
                            ,df_trailveh_2016
                            ,df_trailveh_2017])

In [18]:
# vehicle

df_vehicle_2007 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2007_Philadelphia.csv')
df_vehicle_2008 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2008_Philadelphia.csv')
df_vehicle_2009 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2009_Philadelphia.csv')
df_vehicle_2010 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2010_Philadelphia.csv')
df_vehicle_2011 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2011_Philadelphia.csv')
df_vehicle_2012 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2012_Philadelphia.csv')
df_vehicle_2013 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2013_Philadelphia.csv')
df_vehicle_2014 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2014_Philadelphia.csv')
df_vehicle_2015 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2015_Philadelphia.csv')
df_vehicle_2016 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\VEHICLE_2016_Philadelphia.csv')
df_vehicle_2017 = pd.read_csv(r'C:\Users\weiko\Desktop\homework\vehicle\raw\Philadelphia_VEHICLE_2017.csv')

In [19]:
df_vehicle_07_17 = pd.concat([df_vehicle_2007
                            ,df_vehicle_2008
                            ,df_vehicle_2009
                            ,df_vehicle_2010
                            ,df_vehicle_2011
                            ,df_vehicle_2012
                            ,df_vehicle_2013
                            ,df_vehicle_2014
                            ,df_vehicle_2015
                            ,df_vehicle_2016
                            ,df_vehicle_2017])

## 2.2 Quality check on raw data

> Data Structure
* Crash Level: **df_crash_07_17**, **df_flag_07_17**
* Roadway Segment Level: **df_roadway_07_17**
* Unit Level: **df_vehicle_07_17**, **df_commveh_07_17**, **df_cycle_07_17**, **df_trailveh_07_17**
* Personal Level: **df_person_07_17**

### 2.2.1 crash and flag data 2007-2017 (crash level)

In [20]:
# max number of rows to display
pd.options.display.max_rows = 500

# crash data for 2007 - 2017
df_crash_07_17.head(2).transpose()

                                             0                        1
ARRIVAL_TM                                1815                      300
AUTOMOBILE_COUNT                             3                        3
BELTED_DEATH_COUNT                           0                        0
BELTED_MAJ_INJ_COUNT                         0                        0
BICYCLE_COUNT                                0                        0
BICYCLE_DEATH_COUNT                          0                        0
BICYCLE_MAJ_INJ_COUNT                        0                        0
BUS_COUNT                                    0                        0
COLLISION_TYPE                               2                        5
COMM_VEH_COUNT                               0                        0
CONS_ZONE_SPD_LIM                          NaN                      NaN
COUNTY                                      67                       67
COUNTY_NAME                                NaN                      NaN
COUNTY_YEAR            CRASH_2007_Philadelphia  CRASH_2007_Philadelphia
CRASH_MONTH                                  2                        2
CRASH_YEAR                                2007                     2007
CRN                                 2007045703               2007047000
DAY_OF_WEEK                                  2                        7
DEC_LAT                                40.0509                  39.9416
DEC_LONG                              -75.1807                 -75.1493
DISPATCH_TM                               1815                      256
DISTRICT                                     6                        6
DRIVER_COUNT_16YR                            0                        0
DRIVER_COUNT_17YR                            1                        0
DRIVER_COUNT_18YR                            0                        0
DRIVER_COUNT_19YR                            0                        0
DRIVER_COUNT_20YR                            0                        1
DRIVER_COUNT_50_64YR                         0                        0
DRIVER_COUNT_65_74YR                         0                        0
DRIVER_COUNT_75PLUS                          0                        0
EST_HRS_CLOSED                             NaN                      NaN
FATAL_COUNT                                  0                        0
HEAVY_TRUCK_COUNT                            0                        0
HOUR_OF_DAY                                 99                        2
ILLUMINATION                                 3                        6
INJURY_COUNT                                 2                        0
INTERSECT_TYPE                               0                        0
LANE_CLOSED                                  0                        0
LATITUDE                          40 03:03.000             39 56:29.734
LN_CLOSE_DIR                               NaN                      NaN
LOCATION_TYPE                                0                        0
LONGITUDE                         75 10:50.397             75 08:57.440
MAJ_INJ_COUNT                                0                        0
MAX_SEVERITY_LEVEL                           8                        0
MCYCLE_DEATH_COUNT                           0                        0
MCYCLE_MAJ_INJ_COUNT                         0                        0
MIN_INJ_COUNT                                0                        0
MOD_INJ_COUNT                                0                        0
MOTORCYCLE_COUNT                             0                        0
MUNICIPALITY                             67301                    67301
NTFY_HIWY_MAINT                              N                        N
PED_COUNT                                    0                        0
PED_DEATH_COUNT                              0                        0
PED_MAJ_INJ_COUNT                            0                        0
PERSON_COUNT                                 2                        4
POLICE_AGCY                              67301                    67301
RDWY_SURF_TYPE_CD                          NaN                      NaN
RELATION_TO_ROAD                             6                        6
ROAD_CONDITION                               0                        1
SCH_BUS_IND                                  N                        N
SCH_ZONE_IND                                 N                        N
SMALL_TRUCK_COUNT                            0                        0
SPEC_JURIS_CD                              NaN                      NaN
SUV_COUNT                                    0                        3
TCD_FUNC_CD                                  0                        3
TCD_TYPE                                     0                        2
TFC_DETOUR_IND                             NaN                      NaN
TIME_OF_DAY                               9999                      250
TOTAL_UNITS                                  3                        7
TOT_INJ_COUNT                                2                        0
UNBELTED_OCC_COUNT                           0                        2
UNB_DEATH_COUNT                              0                        0
UNB_MAJ_INJ_COUNT                            0                        0
UNK_INJ_DEG_COUNT                            2                        0
UNK_INJ_PER_COUNT                            0                        0
URBAN_RURAL                                  3                        3
VAN_COUNT                                    0                        0
VEHICLE_COUNT                                3                        7
WEATHER                                      1                        4
WORKERS_PRES                               NaN                      NaN
WORK_ZONE_IND                                N                        N
WORK_ZONE_LOC                              NaN                      NaN
WORK_ZONE_TYPE                             NaN                      NaN
WZ_CLOSE_DETOUR                            NaN                      NaN
WZ_FLAGGER                                 NaN                      NaN
WZ_LAW_OFFCR_IND                           NaN                      NaN
WZ_LN_CLOSURE                              NaN                      NaN
WZ_MOVING                                  NaN                      NaN
WZ_OTHER                                   NaN                      NaN
WZ_SHLDER_MDN                              NaN                      NaN

In [21]:
df_crash_07_17.columns

Index(['ARRIVAL_TM', 'AUTOMOBILE_COUNT', 'BELTED_DEATH_COUNT',
       'BELTED_MAJ_INJ_COUNT', 'BICYCLE_COUNT', 'BICYCLE_DEATH_COUNT',
       'BICYCLE_MAJ_INJ_COUNT', 'BUS_COUNT', 'COLLISION_TYPE',
       'COMM_VEH_COUNT', 'CONS_ZONE_SPD_LIM', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_MONTH', 'CRASH_YEAR', 'CRN', 'DAY_OF_WEEK',
       'DEC_LAT', 'DEC_LONG', 'DISPATCH_TM', 'DISTRICT', 'DRIVER_COUNT_16YR',
       'DRIVER_COUNT_17YR', 'DRIVER_COUNT_18YR', 'DRIVER_COUNT_19YR',
       'DRIVER_COUNT_20YR', 'DRIVER_COUNT_50_64YR', 'DRIVER_COUNT_65_74YR',
       'DRIVER_COUNT_75PLUS', 'EST_HRS_CLOSED', 'FATAL_COUNT',
       'HEAVY_TRUCK_COUNT', 'HOUR_OF_DAY', 'ILLUMINATION', 'INJURY_COUNT',
       'INTERSECT_TYPE', 'LANE_CLOSED', 'LATITUDE', 'LN_CLOSE_DIR',
       'LOCATION_TYPE', 'LONGITUDE', 'MAJ_INJ_COUNT', 'MAX_SEVERITY_LEVEL',
       'MCYCLE_DEATH_COUNT', 'MCYCLE_MAJ_INJ_COUNT', 'MIN_INJ_COUNT',
       'MOD_INJ_COUNT', 'MOTORCYCLE_COUNT', 'MUNICIPALITY', 'NTFY_HIWY_MAINT',
       'PED_COUNT', 'PED_DEATH_COUNT', 'PED_MAJ_INJ_COUNT', 'PERSON_COUNT',
       'POLICE_AGCY', 'RDWY_SURF_TYPE_CD', 'RELATION_TO_ROAD',
       'ROAD_CONDITION', 'SCH_BUS_IND', 'SCH_ZONE_IND', 'SMALL_TRUCK_COUNT',
       'SPEC_JURIS_CD', 'SUV_COUNT', 'TCD_FUNC_CD', 'TCD_TYPE',
       'TFC_DETOUR_IND', 'TIME_OF_DAY', 'TOTAL_UNITS', 'TOT_INJ_COUNT',
       'UNBELTED_OCC_COUNT', 'UNB_DEATH_COUNT', 'UNB_MAJ_INJ_COUNT',
       'UNK_INJ_DEG_COUNT', 'UNK_INJ_PER_COUNT', 'URBAN_RURAL', 'VAN_COUNT',
       'VEHICLE_COUNT', 'WEATHER', 'WORKERS_PRES', 'WORK_ZONE_IND',
       'WORK_ZONE_LOC', 'WORK_ZONE_TYPE', 'WZ_CLOSE_DETOUR', 'WZ_FLAGGER',
       'WZ_LAW_OFFCR_IND', 'WZ_LN_CLOSURE', 'WZ_MOVING', 'WZ_OTHER',
       'WZ_SHLDER_MDN'],
      dtype='object')

In [22]:
df_crash_07_17['CRN'].count()

123116

In [23]:
df_crash_07_17['CRN'].nunique()

123116

In [24]:
# by year
df_crash_07_17['CRASH_YEAR'].value_counts().sort_index()

2007    11624
2008    10676
2009    10743
2010    11070
2011    10911
2012    11395
2013    11170
2014    10646
2015    11570
2016    12190
2017    11121
Name: CRASH_YEAR, dtype: int64

In [25]:
# no duplicate crn
df_crash_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    11624
2008    10676
2009    10743
2010    11070
2011    10911
2012    11395
2013    11170
2014    10646
2015    11570
2016    12190
2017    11121
Name: CRN, dtype: int64

In [27]:
# max number of rows to display
pd.options.display.max_rows = 500

# check missing value
df_crash_07_17.isnull().sum()
# no missing value

ARRIVAL_TM                  978
AUTOMOBILE_COUNT              0
BELTED_DEATH_COUNT            0
BELTED_MAJ_INJ_COUNT          0
BICYCLE_COUNT                 0
BICYCLE_DEATH_COUNT           0
BICYCLE_MAJ_INJ_COUNT         0
BUS_COUNT                     0
COLLISION_TYPE                0
COMM_VEH_COUNT                0
CONS_ZONE_SPD_LIM        110648
COUNTY                        0
COUNTY_NAME              111995
COUNTY_YEAR               11121
CRASH_MONTH                   0
CRASH_YEAR                    0
CRN                           0
DAY_OF_WEEK                   0
DEC_LAT                    1294
DEC_LONG                   1294
DISPATCH_TM                1074
DISTRICT                      0
DRIVER_COUNT_16YR             0
DRIVER_COUNT_17YR             0
DRIVER_COUNT_18YR             0
DRIVER_COUNT_19YR             0
DRIVER_COUNT_20YR             0
DRIVER_COUNT_50_64YR          0
DRIVER_COUNT_65_74YR          0
DRIVER_COUNT_75PLUS           0
EST_HRS_CLOSED            79648
FATAL_COUNT                   0
HEAVY_TRUCK_COUNT             0
HOUR_OF_DAY                   9
ILLUMINATION                  9
INJURY_COUNT                  0
INTERSECT_TYPE                0
LANE_CLOSED                   0
LATITUDE                   1247
LN_CLOSE_DIR              79650
LOCATION_TYPE                 0
LONGITUDE                  1247
MAJ_INJ_COUNT                 0
MAX_SEVERITY_LEVEL            0
MCYCLE_DEATH_COUNT            0
MCYCLE_MAJ_INJ_COUNT          0
MIN_INJ_COUNT                 0
MOD_INJ_COUNT                 0
MOTORCYCLE_COUNT              0
MUNICIPALITY                  0
NTFY_HIWY_MAINT           32301
PED_COUNT                     0
PED_DEATH_COUNT               0
PED_MAJ_INJ_COUNT             0
PERSON_COUNT                  0
POLICE_AGCY                  80
RDWY_SURF_TYPE_CD        111090
RELATION_TO_ROAD              3
ROAD_CONDITION                5
SCH_BUS_IND                7597
SCH_ZONE_IND              21488
SMALL_TRUCK_COUNT             0
SPEC_JURIS_CD            111090
SUV_COUNT                     0
TCD_FUNC_CD                   6
TCD_TYPE                      0
TFC_DETOUR_IND            79647
TIME_OF_DAY                   9
TOTAL_UNITS                   0
TOT_INJ_COUNT                 0
UNBELTED_OCC_COUNT            0
UNB_DEATH_COUNT               0
UNB_MAJ_INJ_COUNT             0
UNK_INJ_DEG_COUNT             0
UNK_INJ_PER_COUNT             0
URBAN_RURAL                   0
VAN_COUNT                     0
VEHICLE_COUNT                 0
WEATHER                      18
WORKERS_PRES             110648
WORK_ZONE_IND                 0
WORK_ZONE_LOC            110648
WORK_ZONE_TYPE           110648
WZ_CLOSE_DETOUR          110869
WZ_FLAGGER               110877
WZ_LAW_OFFCR_IND         110648
WZ_LN_CLOSURE            110783
WZ_MOVING                110866
WZ_OTHER                 110861
WZ_SHLDER_MDN            110850
dtype: int64

In [28]:
# basic info
df_crash_07_17.info()

# number os obs: 77462
# 90 features: float64(2), int64(65), object(23)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123116 entries, 0 to 11120
Data columns (total 90 columns):
ARRIVAL_TM               122138 non-null object
AUTOMOBILE_COUNT         123116 non-null int64
BELTED_DEATH_COUNT       123116 non-null int64
BELTED_MAJ_INJ_COUNT     123116 non-null int64
BICYCLE_COUNT            123116 non-null int64
BICYCLE_DEATH_COUNT      123116 non-null int64
BICYCLE_MAJ_INJ_COUNT    123116 non-null int64
BUS_COUNT                123116 non-null int64
COLLISION_TYPE           123116 non-null int64
COMM_VEH_COUNT           123116 non-null int64
CONS_ZONE_SPD_LIM        12468 non-null object
COUNTY                   123116 non-null int64
COUNTY_NAME              11121 non-null object
COUNTY_YEAR              111995 non-null object
CRASH_MONTH              123116 non-null int64
CRASH_YEAR               123116 non-null int64
CRN                      123116 non-null int64
DAY_OF_WEEK              123116 non-null int64
DEC_LAT                  121822 non-null float64
DEC_LONG                 121822 non-null float64
DISPATCH_TM              122042 non-null object
DISTRICT                 123116 non-null int64
DRIVER_COUNT_16YR        123116 non-null int64
DRIVER_COUNT_17YR        123116 non-null int64
DRIVER_COUNT_18YR        123116 non-null int64
DRIVER_COUNT_19YR        123116 non-null int64
DRIVER_COUNT_20YR        123116 non-null int64
DRIVER_COUNT_50_64YR     123116 non-null int64
DRIVER_COUNT_65_74YR     123116 non-null int64
DRIVER_COUNT_75PLUS      123116 non-null int64
EST_HRS_CLOSED           43468 non-null object
FATAL_COUNT              123116 non-null int64
HEAVY_TRUCK_COUNT        123116 non-null int64
HOUR_OF_DAY              123107 non-null float64
ILLUMINATION             123107 non-null float64
INJURY_COUNT             123116 non-null int64
INTERSECT_TYPE           123116 non-null int64
LANE_CLOSED              123116 non-null int64
LATITUDE                 121869 non-null object
LN_CLOSE_DIR             43466 non-null object
LOCATION_TYPE            123116 non-null int64
LONGITUDE                121869 non-null object
MAJ_INJ_COUNT            123116 non-null int64
MAX_SEVERITY_LEVEL       123116 non-null int64
MCYCLE_DEATH_COUNT       123116 non-null int64
MCYCLE_MAJ_INJ_COUNT     123116 non-null int64
MIN_INJ_COUNT            123116 non-null int64
MOD_INJ_COUNT            123116 non-null int64
MOTORCYCLE_COUNT         123116 non-null int64
MUNICIPALITY             123116 non-null int64
NTFY_HIWY_MAINT          90815 non-null object
PED_COUNT                123116 non-null int64
PED_DEATH_COUNT          123116 non-null int64
PED_MAJ_INJ_COUNT        123116 non-null int64
PERSON_COUNT             123116 non-null int64
POLICE_AGCY              123036 non-null object
RDWY_SURF_TYPE_CD        12026 non-null object
RELATION_TO_ROAD         123113 non-null float64
ROAD_CONDITION           123111 non-null float64
SCH_BUS_IND              115519 non-null object
SCH_ZONE_IND             101628 non-null object
SMALL_TRUCK_COUNT        123116 non-null int64
SPEC_JURIS_CD            12026 non-null object
SUV_COUNT                123116 non-null int64
TCD_FUNC_CD              123110 non-null float64
TCD_TYPE                 123116 non-null int64
TFC_DETOUR_IND           43469 non-null object
TIME_OF_DAY              123107 non-null float64
TOTAL_UNITS              123116 non-null int64
TOT_INJ_COUNT            123116 non-null int64
UNBELTED_OCC_COUNT       123116 non-null int64
UNB_DEATH_COUNT          123116 non-null int64
UNB_MAJ_INJ_COUNT        123116 non-null int64
UNK_INJ_DEG_COUNT        123116 non-null int64
UNK_INJ_PER_COUNT        123116 non-null int64
URBAN_RURAL              123116 non-null int64
VAN_COUNT                123116 non-null int64
VEHICLE_COUNT            123116 non-null int64
WEATHER                  123098 non-null float64
WORKERS_PRES             12468 non-null object
WORK_ZONE_IND            123116 non-null object
WORK_ZONE_LOC            12468 non-null object
WORK_ZONE_TYPE           12468 non-null object
WZ_CLOSE_DETOUR          12247 non-null object
WZ_FLAGGER               12239 non-null object
WZ_LAW_OFFCR_IND         12468 non-null object
WZ_LN_CLOSURE            12333 non-null object
WZ_MOVING                12250 non-null object
WZ_OTHER                 12255 non-null object
WZ_SHLDER_MDN            12266 non-null object
dtypes: float64(9), int64(54), object(27)
memory usage: 85.5+ MB

In [29]:
# max number of columns to display
pd.options.display.max_columns = 200

# describe numeric features
df_crash_07_17.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
AUTOMOBILE_COUNT,123116.0,1.219062e+00,8.759277e-01,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+01
BELTED_DEATH_COUNT,123116.0,5.035901e-04,2.484060e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
BELTED_MAJ_INJ_COUNT,123116.0,4.085578e-03,7.360198e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
BICYCLE_COUNT,123116.0,4.585919e-02,2.103422e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
BICYCLE_DEATH_COUNT,123116.0,2.924072e-04,1.709749e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
BICYCLE_MAJ_INJ_COUNT,123116.0,1.332077e-03,3.691617e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
BUS_COUNT,123116.0,2.558563e-02,1.602450e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
COLLISION_TYPE,123116.0,4.307637e+00,2.468722e+00,0.000000e+00,2.000000e+00,4.000000e+00,7.000000e+00,9.000000e+00
COMM_VEH_COUNT,123116.0,5.896065e-02,2.444196e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
COUNTY,123116.0,6.700000e+01,0.000000e+00,6.700000e+01,6.700000e+01,6.700000e+01,6.700000e+01,6.700000e+01
CRASH_MONTH,123116.0,6.615745e+00,3.381683e+00,1.000000e+00,4.000000e+00,7.000000e+00,1.000000e+01,1.200000e+01
CRASH_YEAR,123116.0,2.012044e+03,3.178742e+00,2.007000e+03,2.009000e+03,2.012000e+03,2.015000e+03,2.017000e+03
CRN,123116.0,2.012219e+09,3.160587e+06,2.007002e+09,2.009120e+09,2.012083e+09,2.015063e+09,2.018048e+09
DAY_OF_WEEK,123116.0,4.109791e+00,2.010190e+00,1.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00,7.000000e+00
DEC_LAT,121822.0,3.999556e+01,5.141369e-02,3.987540e+01,3.995710e+01,3.999470e+01,4.003210e+01,4.185100e+01
DEC_LONG,121822.0,-7.514508e+01,7.393554e-02,-8.050070e+01,-7.519240e+01,-7.515560e+01,-7.510490e+01,-7.495750e+01
DISTRICT,123116.0,6.000000e+00,0.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00
DRIVER_COUNT_16YR,123116.0,2.802235e-03,5.316856e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
DRIVER_COUNT_17YR,123116.0,1.130641e-02,1.064184e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
DRIVER_COUNT_18YR,123116.0,2.257221e-02,1.496255e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
DRIVER_COUNT_19YR,123116.0,3.210793e-02,1.778471e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
DRIVER_COUNT_20YR,123116.0,4.031158e-02,1.996003e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
DRIVER_COUNT_50_64YR,123116.0,2.854219e-01,5.122888e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00
DRIVER_COUNT_65_74YR,123116.0,7.244387e-02,2.666671e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
DRIVER_COUNT_75PLUS,123116.0,3.565743e-02,1.889070e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
FATAL_COUNT,123116.0,8.723480e-03,1.012704e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
HEAVY_TRUCK_COUNT,123116.0,3.675396e-02,1.937304e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
HOUR_OF_DAY,123107.0,1.716536e+01,1.991453e+01,0.000000e+00,8.000000e+00,1.400000e+01,1.800000e+01,9.900000e+01
ILLUMINATION,123107.0,1.829595e+00,1.138833e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,8.000000e+00
INJURY_COUNT,123116.0,1.085911e+00,1.066525e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.500000e+01
INTERSECT_TYPE,123116.0,8.532522e-01,1.275149e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.100000e+01
LANE_CLOSED,123116.0,4.133175e-01,7.319554e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.000000e+00
LOCATION_TYPE,123116.0,5.001543e-01,4.009791e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.900000e+01
MAJ_INJ_COUNT,123116.0,2.566685e-02,1.771336e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
MAX_SEVERITY_LEVEL,123116.0,4.189464e+00,2.899854e+00,0.000000e+00,3.000000e+00,4.000000e+00,8.000000e+00,9.000000e+00
MCYCLE_DEATH_COUNT,123116.0,1.502648e-03,3.956491e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
MCYCLE_MAJ_INJ_COUNT,123116.0,2.696644e-03,5.430758e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
MIN_INJ_COUNT,123116.0,5.326034e-01,8.626135e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.500000e+01
MOD_INJ_COUNT,123116.0,1.385035e-01,4.516886e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.300000e+01
MOTORCYCLE_COUNT,123116.0,2.786803e-02,1.688340e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
MUNICIPALITY,123116.0,6.730100e+04,0.000000e+00,6.730100e+04,6.730100e+04,6.730100e+04,6.730100e+04,6.730100e+04
PED_COUNT,123116.0,1.604666e-01,3.880586e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01
PED_DEATH_COUNT,123116.0,3.037786e-03,5.832852e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
PED_MAJ_INJ_COUNT,123116.0,6.928425e-03,8.498013e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
PERSON_COUNT,123116.0,2.687368e+00,1.848853e+00,0.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,9.000000e+01
RELATION_TO_ROAD,123113.0,1.619301e+00,1.454528e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00
ROAD_CONDITION,123111.0,3.517314e-01,1.032182e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00
SMALL_TRUCK_COUNT,123116.0,1.206667e-01,3.457245e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
SUV_COUNT,123116.0,3.264645e-01,5.602940e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,5.000000e+00
TCD_FUNC_CD,123110.0,1.571562e+00,1.778042e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,9.000000e+00
TCD_TYPE,123116.0,1.179392e+00,1.370579e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,9.000000e+00
TIME_OF_DAY,123107.0,1.747325e+03,2.006512e+03,0.000000e+00,8.560000e+02,1.430000e+03,1.840000e+03,9.999000e+03
TOTAL_UNITS,123116.0,2.117466e+00,7.455847e-01,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.200000e+01
TOT_INJ_COUNT,123116.0,1.085683e+00,1.066825e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.500000e+01
UNBELTED_OCC_COUNT,123116.0,2.012249e-01,6.125099e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01
UNB_DEATH_COUNT,123116.0,1.055915e-03,3.488923e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00
UNB_MAJ_INJ_COUNT,123116.0,2.810358e-03,5.889420e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
UNK_INJ_DEG_COUNT,123116.0,3.889096e-01,8.139606e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.500000e+01
UNK_INJ_PER_COUNT,123116.0,1.647389e-01,5.543283e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e+01
URBAN_RURAL,123116.0,3.000000e+00,0.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
VAN_COUNT,123116.0,1.133565e-01,3.354291e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
VEHICLE_COUNT,123116.0,1.905122e+00,8.540047e-01,0.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,2.200000e+01
WEATHER,123098.0,1.367065e+00,1.170346e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00

In [30]:
# flag data for 2007 - 2017
df_flag_07_17.head(2).transpose()

                                           0                       1
AGGRESSIVE_DRIVING                         0                       0
ALCOHOL_RELATED                            1                       0
BICYCLE                                    0                       0
CELL_PHONE                                 0                       0
COMM_VEHICLE                               0                       0
COUNTY                                    67                      67
COUNTY_NAME                              NaN                     NaN
COUNTY_YEAR           FLAG_2007_Philadelphia  FLAG_2007_Philadelphia
CRASH_YEAR                              2007                    2007
CRN                               2008020096              2008020233
CROSS_MEDIAN                               1                       0
CURVED_ROAD                                0                       0
CURVE_DVR_ERROR                            0                       0
DEER_RELATED                               0                       0
DISTRACTED                                 0                       0
DRINKING_DRIVER                            1                       0
DRIVER_16YR                                0                       0
DRIVER_17YR                                0                       0
DRIVER_18YR                                0                       0
DRIVER_19YR                                0                       1
DRIVER_20YR                                0                       0
DRIVER_50_64YR                             1                       1
DRIVER_65_74YR                             0                       0
DRIVER_75PLUS                              0                       0
DRUGGED_DRIVER                             0                       0
DRUG_RELATED                               0                       0
FATAL                                      1                       1
FATAL_OR_MAJ_INJ                           1                       1
FATIGUE_ASLEEP                             0                       0
FIRE_IN_VEHICLE                            0                       0
HAZARDOUS_TRUCK                            0                       0
HIT_BARRIER                                0                       0
HIT_BRIDGE                                 0                       0
HIT_DEER                                   0                       0
HIT_EMBANKMENT                             0                       0
HIT_FIXED_OBJECT                           0                       0
HIT_GDRAIL                                 0                       0
HIT_GDRAIL_END                             0                       0
HIT_PARKED_VEHICLE                         0                       0
HIT_POLE                                   0                       0
HIT_TREE_SHRUB                             0                       0
HO_OPPDIR_SDSWP                            1                       0
HVY_TRUCK_RELATED                          0                       0
ICY_ROAD                                   0                       0
ILLEGAL_DRUG_RELATED                       0                       0
ILLUMINATION_DARK                          0                       0
IMPAIRED_DRIVER                            1                       0
INJURY                                     1                       0
INJURY_OR_FATAL                            1                       1
INTERSECTION                               0                       1
INTERSTATE                                 0                       0
LIMIT_65MPH                                0                       0
LOCAL_ROAD                                 1                       1
LOCAL_ROAD_ONLY                            1                       0
MAJOR_INJURY                               0                       0
MC_DRINKING_DRIVER                         0                       0
MINOR_INJURY                               0                       0
MODERATE_INJURY                            0                       0
MOTORCYCLE                                 0                       1
MUNICIPALITY                           67301                   67301
NHTSA_AGG_DRIVING                          0                       0
NON_INTERSECTION                           1                       0
NO_CLEARANCE                               0                       0
OVERTURNED                                 0                       0
PEDESTRIAN                                 0                       0
PHANTOM_VEHICLE                            0                       0
PROPERTY_DAMAGE_ONLY                       0                       0
PSP_REPORTED                               0                       0
REAR_END                                   0                       0
RUNNING_RED_LT                             0                       0
RUNNING_STOP_SIGN                          0                       0
SCHOOL_BUS                                 0                       0
SCHOOL_BUS_UNIT                            0                       0
SCHOOL_ZONE                                0                       0
SHLDR_RELATED                              0                       0
SIGNALIZED_INT                             0                       1
SNOW_SLUSH_ROAD                            0                       0
SPEEDING                                   0                       0
SPEEDING_RELATED                           0                       0
STATE_ROAD                                 0                       1
STOP_CONTROLLED_INT                        0                       0
SUDDEN_DEER                                0                       0
SV_RUN_OFF_RD                              0                       0
TAILGATING                                 0                       0
TRAIN                                      0                       0
TRAIN_TROLLEY                              0                       0
TROLLEY                                    0                       0
TURNPIKE                                   0                       0
UNBELTED                                   0                       0
UNDERAGE_DRNK_DRV                          0                       0
UNLICENSED                                 0                       0
UNSIGNALIZED_INT                           0                       0
VEHICLE_FAILURE                            0                       0
VEHICLE_TOWED                              1                       1
WET_ROAD                                   0                       0
WORK_ZONE                                  0                       0

In [31]:
df_flag_07_17.columns

Index(['AGGRESSIVE_DRIVING', 'ALCOHOL_RELATED', 'BICYCLE', 'CELL_PHONE',
       'COMM_VEHICLE', 'COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR', 'CRASH_YEAR',
       'CRN', 'CROSS_MEDIAN', 'CURVED_ROAD', 'CURVE_DVR_ERROR', 'DEER_RELATED',
       'DISTRACTED', 'DRINKING_DRIVER', 'DRIVER_16YR', 'DRIVER_17YR',
       'DRIVER_18YR', 'DRIVER_19YR', 'DRIVER_20YR', 'DRIVER_50_64YR',
       'DRIVER_65_74YR', 'DRIVER_75PLUS', 'DRUGGED_DRIVER', 'DRUG_RELATED',
       'FATAL', 'FATAL_OR_MAJ_INJ', 'FATIGUE_ASLEEP', 'FIRE_IN_VEHICLE',
       'HAZARDOUS_TRUCK', 'HIT_BARRIER', 'HIT_BRIDGE', 'HIT_DEER',
       'HIT_EMBANKMENT', 'HIT_FIXED_OBJECT', 'HIT_GDRAIL', 'HIT_GDRAIL_END',
       'HIT_PARKED_VEHICLE', 'HIT_POLE', 'HIT_TREE_SHRUB', 'HO_OPPDIR_SDSWP',
       'HVY_TRUCK_RELATED', 'ICY_ROAD', 'ILLEGAL_DRUG_RELATED',
       'ILLUMINATION_DARK', 'IMPAIRED_DRIVER', 'INJURY', 'INJURY_OR_FATAL',
       'INTERSECTION', 'INTERSTATE', 'LIMIT_65MPH', 'LOCAL_ROAD',
       'LOCAL_ROAD_ONLY', 'MAJOR_INJURY', 'MC_DRINKING_DRIVER', 'MINOR_INJURY',
       'MODERATE_INJURY', 'MOTORCYCLE', 'MUNICIPALITY', 'NHTSA_AGG_DRIVING',
       'NON_INTERSECTION', 'NO_CLEARANCE', 'OVERTURNED', 'PEDESTRIAN',
       'PHANTOM_VEHICLE', 'PROPERTY_DAMAGE_ONLY', 'PSP_REPORTED', 'REAR_END',
       'RUNNING_RED_LT', 'RUNNING_STOP_SIGN', 'SCHOOL_BUS', 'SCHOOL_BUS_UNIT',
       'SCHOOL_ZONE', 'SHLDR_RELATED', 'SIGNALIZED_INT', 'SNOW_SLUSH_ROAD',
       'SPEEDING', 'SPEEDING_RELATED', 'STATE_ROAD', 'STOP_CONTROLLED_INT',
       'SUDDEN_DEER', 'SV_RUN_OFF_RD', 'TAILGATING', 'TRAIN', 'TRAIN_TROLLEY',
       'TROLLEY', 'TURNPIKE', 'UNBELTED', 'UNDERAGE_DRNK_DRV', 'UNLICENSED',
       'UNSIGNALIZED_INT', 'VEHICLE_FAILURE', 'VEHICLE_TOWED', 'WET_ROAD',
       'WORK_ZONE'],
      dtype='object')

In [32]:
df_flag_07_17['CRN'].count()

123114

In [33]:
# by year
df_flag_07_17['CRASH_YEAR'].value_counts().sort_index()

2007    11624
2008    10676
2009    10743
2010    11070
2011    10911
2012    11395
2013    11170
2014    10646
2015    11570
2016    12190
2017    11119
Name: CRASH_YEAR, dtype: int64

In [34]:
# no duplicate crn
df_flag_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    11624
2008    10676
2009    10743
2010    11070
2011    10911
2012    11395
2013    11170
2014    10646
2015    11570
2016    12190
2017    11119
Name: CRN, dtype: int64

In [35]:
# check missing value
df_flag_07_17.isnull().sum()
# no missing value

AGGRESSIVE_DRIVING           0
ALCOHOL_RELATED              0
BICYCLE                      0
CELL_PHONE                   0
COMM_VEHICLE                 0
COUNTY                       0
COUNTY_NAME             111995
COUNTY_YEAR              11119
CRASH_YEAR                   0
CRN                          0
CROSS_MEDIAN                 0
CURVED_ROAD                  0
CURVE_DVR_ERROR              0
DEER_RELATED                 0
DISTRACTED                   0
DRINKING_DRIVER              0
DRIVER_16YR                  0
DRIVER_17YR                  0
DRIVER_18YR                  0
DRIVER_19YR                  0
DRIVER_20YR                  0
DRIVER_50_64YR               0
DRIVER_65_74YR               0
DRIVER_75PLUS                0
DRUGGED_DRIVER               0
DRUG_RELATED                 0
FATAL                        0
FATAL_OR_MAJ_INJ             0
FATIGUE_ASLEEP               0
FIRE_IN_VEHICLE              0
HAZARDOUS_TRUCK              0
HIT_BARRIER                  0
HIT_BRIDGE                   0
HIT_DEER                     0
HIT_EMBANKMENT               0
HIT_FIXED_OBJECT             0
HIT_GDRAIL                   0
HIT_GDRAIL_END               0
HIT_PARKED_VEHICLE           0
HIT_POLE                     0
HIT_TREE_SHRUB               0
HO_OPPDIR_SDSWP              0
HVY_TRUCK_RELATED            0
ICY_ROAD                     0
ILLEGAL_DRUG_RELATED         0
ILLUMINATION_DARK            0
IMPAIRED_DRIVER              0
INJURY                       0
INJURY_OR_FATAL              0
INTERSECTION                 0
INTERSTATE                   0
LIMIT_65MPH                  0
LOCAL_ROAD                   0
LOCAL_ROAD_ONLY              0
MAJOR_INJURY                 0
MC_DRINKING_DRIVER           0
MINOR_INJURY                 0
MODERATE_INJURY              0
MOTORCYCLE                   0
MUNICIPALITY                 0
NHTSA_AGG_DRIVING            0
NON_INTERSECTION             0
NO_CLEARANCE                 0
OVERTURNED                   0
PEDESTRIAN                   0
PHANTOM_VEHICLE              0
PROPERTY_DAMAGE_ONLY         0
PSP_REPORTED                 0
REAR_END                     0
RUNNING_RED_LT               0
RUNNING_STOP_SIGN            0
SCHOOL_BUS                   0
SCHOOL_BUS_UNIT              0
SCHOOL_ZONE                  0
SHLDR_RELATED                0
SIGNALIZED_INT               0
SNOW_SLUSH_ROAD              0
SPEEDING                     0
SPEEDING_RELATED             0
STATE_ROAD                   0
STOP_CONTROLLED_INT          0
SUDDEN_DEER                  0
SV_RUN_OFF_RD                0
TAILGATING                   0
TRAIN                        0
TRAIN_TROLLEY                0
TROLLEY                      0
TURNPIKE                     0
UNBELTED                     0
UNDERAGE_DRNK_DRV            0
UNLICENSED                   0
UNSIGNALIZED_INT             0
VEHICLE_FAILURE              0
VEHICLE_TOWED                0
WET_ROAD                     0
WORK_ZONE                    0
dtype: int64

In [36]:
df_flag_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123114 entries, 0 to 11118
Data columns (total 96 columns):
AGGRESSIVE_DRIVING      123114 non-null int64
ALCOHOL_RELATED         123114 non-null int64
BICYCLE                 123114 non-null int64
CELL_PHONE              123114 non-null int64
COMM_VEHICLE            123114 non-null int64
COUNTY                  123114 non-null int64
COUNTY_NAME             11119 non-null object
COUNTY_YEAR             111995 non-null object
CRASH_YEAR              123114 non-null int64
CRN                     123114 non-null int64
CROSS_MEDIAN            123114 non-null int64
CURVED_ROAD             123114 non-null int64
CURVE_DVR_ERROR         123114 non-null int64
DEER_RELATED            123114 non-null int64
DISTRACTED              123114 non-null int64
DRINKING_DRIVER         123114 non-null int64
DRIVER_16YR             123114 non-null int64
DRIVER_17YR             123114 non-null int64
DRIVER_18YR             123114 non-null int64
DRIVER_19YR             123114 non-null int64
DRIVER_20YR             123114 non-null int64
DRIVER_50_64YR          123114 non-null int64
DRIVER_65_74YR          123114 non-null int64
DRIVER_75PLUS           123114 non-null int64
DRUGGED_DRIVER          123114 non-null int64
DRUG_RELATED            123114 non-null int64
FATAL                   123114 non-null int64
FATAL_OR_MAJ_INJ        123114 non-null int64
FATIGUE_ASLEEP          123114 non-null int64
FIRE_IN_VEHICLE         123114 non-null int64
HAZARDOUS_TRUCK         123114 non-null int64
HIT_BARRIER             123114 non-null int64
HIT_BRIDGE              123114 non-null int64
HIT_DEER                123114 non-null int64
HIT_EMBANKMENT          123114 non-null int64
HIT_FIXED_OBJECT        123114 non-null int64
HIT_GDRAIL              123114 non-null int64
HIT_GDRAIL_END          123114 non-null int64
HIT_PARKED_VEHICLE      123114 non-null int64
HIT_POLE                123114 non-null int64
HIT_TREE_SHRUB          123114 non-null int64
HO_OPPDIR_SDSWP         123114 non-null int64
HVY_TRUCK_RELATED       123114 non-null int64
ICY_ROAD                123114 non-null int64
ILLEGAL_DRUG_RELATED    123114 non-null int64
ILLUMINATION_DARK       123114 non-null int64
IMPAIRED_DRIVER         123114 non-null int64
INJURY                  123114 non-null int64
INJURY_OR_FATAL         123114 non-null int64
INTERSECTION            123114 non-null int64
INTERSTATE              123114 non-null int64
LIMIT_65MPH             123114 non-null int64
LOCAL_ROAD              123114 non-null int64
LOCAL_ROAD_ONLY         123114 non-null int64
MAJOR_INJURY            123114 non-null int64
MC_DRINKING_DRIVER      123114 non-null int64
MINOR_INJURY            123114 non-null int64
MODERATE_INJURY         123114 non-null int64
MOTORCYCLE              123114 non-null int64
MUNICIPALITY            123114 non-null int64
NHTSA_AGG_DRIVING       123114 non-null int64
NON_INTERSECTION        123114 non-null int64
NO_CLEARANCE            123114 non-null int64
OVERTURNED              123114 non-null int64
PEDESTRIAN              123114 non-null int64
PHANTOM_VEHICLE         123114 non-null int64
PROPERTY_DAMAGE_ONLY    123114 non-null int64
PSP_REPORTED            123114 non-null int64
REAR_END                123114 non-null int64
RUNNING_RED_LT          123114 non-null int64
RUNNING_STOP_SIGN       123114 non-null int64
SCHOOL_BUS              123114 non-null int64
SCHOOL_BUS_UNIT         123114 non-null int64
SCHOOL_ZONE             123114 non-null int64
SHLDR_RELATED           123114 non-null int64
SIGNALIZED_INT          123114 non-null int64
SNOW_SLUSH_ROAD         123114 non-null int64
SPEEDING                123114 non-null int64
SPEEDING_RELATED        123114 non-null int64
STATE_ROAD              123114 non-null int64
STOP_CONTROLLED_INT     123114 non-null int64
SUDDEN_DEER             123114 non-null int64
SV_RUN_OFF_RD           123114 non-null int64
TAILGATING              123114 non-null int64
TRAIN                   123114 non-null int64
TRAIN_TROLLEY           123114 non-null int64
TROLLEY                 123114 non-null int64
TURNPIKE                123114 non-null int64
UNBELTED                123114 non-null int64
UNDERAGE_DRNK_DRV       123114 non-null int64
UNLICENSED              123114 non-null int64
UNSIGNALIZED_INT        123114 non-null int64
VEHICLE_FAILURE         123114 non-null int64
VEHICLE_TOWED           123114 non-null int64
WET_ROAD                123114 non-null int64
WORK_ZONE               123114 non-null int64
dtypes: int64(94), object(2)
memory usage: 91.1+ MB

In [37]:
df_flag_07_17.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
AGGRESSIVE_DRIVING,123114.0,4.795637e-01,4.995842e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
ALCOHOL_RELATED,123114.0,5.680101e-02,2.314629e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
BICYCLE,123114.0,4.561626e-02,2.086523e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
CELL_PHONE,123114.0,8.244391e-03,9.042393e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
COMM_VEHICLE,123114.0,5.691473e-02,2.316806e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
COUNTY,123114.0,6.700000e+01,0.000000e+00,6.700000e+01,6.700000e+01,6.700000e+01,6.700000e+01,6.700000e+01
CRASH_YEAR,123114.0,2.012044e+03,3.178705e+00,2.007000e+03,2.009000e+03,2.012000e+03,2.015000e+03,2.017000e+03
CRN,123114.0,2.012219e+09,3.160526e+06,2.007002e+09,2.009120e+09,2.012083e+09,2.015063e+09,2.018040e+09
CROSS_MEDIAN,123114.0,1.415761e-02,1.181410e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
CURVED_ROAD,123114.0,7.597836e-02,2.649646e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
CURVE_DVR_ERROR,123114.0,1.271180e-02,1.120282e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DEER_RELATED,123114.0,7.878876e-04,2.805839e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DISTRACTED,123114.0,6.018000e-02,2.378210e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRINKING_DRIVER,123114.0,5.139139e-02,2.207956e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_16YR,123114.0,2.786036e-03,5.270955e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_17YR,123114.0,1.123349e-02,1.053916e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_18YR,123114.0,2.241012e-02,1.480138e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_19YR,123114.0,3.184041e-02,1.755758e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_20YR,123114.0,3.974365e-02,1.953571e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_50_64YR,123114.0,2.578423e-01,4.374485e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
DRIVER_65_74YR,123114.0,7.051188e-02,2.560088e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRIVER_75PLUS,123114.0,3.501633e-02,1.838218e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRUGGED_DRIVER,123114.0,2.535861e-02,1.572124e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DRUG_RELATED,123114.0,2.718619e-02,1.626263e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FATAL,123114.0,8.090063e-03,8.958057e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FATAL_OR_MAJ_INJ,123114.0,3.063015e-02,1.723142e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FATIGUE_ASLEEP,123114.0,1.068116e-02,1.027967e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
FIRE_IN_VEHICLE,123114.0,1.835697e-03,4.280587e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HAZARDOUS_TRUCK,123114.0,5.848238e-04,2.417616e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_BARRIER,123114.0,6.085417e-02,2.390636e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_BRIDGE,123114.0,2.022516e-03,4.492707e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_DEER,123114.0,3.898825e-04,1.974167e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_EMBANKMENT,123114.0,4.239973e-03,6.497715e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_FIXED_OBJECT,123114.0,1.231541e-01,3.286154e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_GDRAIL,123114.0,1.477492e-02,1.206513e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_GDRAIL_END,123114.0,4.174992e-03,6.447942e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_PARKED_VEHICLE,123114.0,1.146661e-01,3.186198e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_POLE,123114.0,3.117436e-02,1.737894e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HIT_TREE_SHRUB,123114.0,1.539224e-02,1.231074e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HO_OPPDIR_SDSWP,123114.0,5.779197e-02,2.333506e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
HVY_TRUCK_RELATED,123114.0,3.307504e-02,1.788333e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
ICY_ROAD,123114.0,1.234628e-02,1.104262e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
ILLEGAL_DRUG_RELATED,123114.0,1.635882e-02,1.268517e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
ILLUMINATION_DARK,123114.0,3.529737e-01,4.778965e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
IMPAIRED_DRIVER,123114.0,6.670241e-02,2.495069e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
INJURY,123114.0,7.541303e-01,4.306034e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
INJURY_OR_FATAL,123114.0,7.595562e-01,4.273547e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
INTERSECTION,123114.0,5.347158e-01,4.987954e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
INTERSTATE,123114.0,1.264600e-01,3.323685e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
LIMIT_65MPH,123114.0,1.380834e-04,1.175013e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
LOCAL_ROAD,123114.0,6.397160e-01,4.800847e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
LOCAL_ROAD_ONLY,123114.0,3.817031e-01,4.858063e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
MAJOR_INJURY,123114.0,2.318177e-02,1.504811e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
MC_DRINKING_DRIVER,123114.0,6.498042e-04,2.548308e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
MINOR_INJURY,123114.0,3.915883e-01,4.881074e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
MODERATE_INJURY,123114.0,1.134721e-01,3.171703e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
MOTORCYCLE,123114.0,2.703186e-02,1.621769e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
MUNICIPALITY,123114.0,6.730100e+04,0.000000e+00,6.730100e+04,6.730100e+04,6.730100e+04,6.730100e+04,6.730100e+04
NHTSA_AGG_DRIVING,123114.0,3.934565e-02,1.944168e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
NON_INTERSECTION,123114.0,4.652842e-01,4.987954e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
NO_CLEARANCE,123114.0,3.837094e-02,1.920909e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
OVERTURNED,123114.0,1.912049e-02,1.369491e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
PEDESTRIAN,123114.0,1.538493e-01,3.608057e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
PHANTOM_VEHICLE,123114.0,6.197508e-03,7.848025e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
PROPERTY_DAMAGE_ONLY,123114.0,2.338158e-01,4.232581e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
PSP_REPORTED,123114.0,1.316179e-01,3.380762e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
REAR_END,123114.0,2.355215e-01,4.243261e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
RUNNING_RED_LT,123114.0,5.356824e-02,2.251646e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
RUNNING_STOP_SIGN,123114.0,2.201212e-02,1.467234e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SCHOOL_BUS,123114.0,6.619881e-03,8.109323e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SCHOOL_BUS_UNIT,123114.0,4.451159e-03,6.656863e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SCHOOL_ZONE,123114.0,9.202853e-03,9.548945e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SHLDR_RELATED,123114.0,2.030638e-04,1.424866e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SIGNALIZED_INT,123114.0,3.279156e-01,4.694558e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
SNOW_SLUSH_ROAD,123114.0,1.205387e-02,1.091269e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SPEEDING,123114.0,3.543870e-02,1.848867e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SPEEDING_RELATED,123114.0,1.518836e-01,3.589095e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
STATE_ROAD,123114.0,6.181831e-01,4.858340e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
STOP_CONTROLLED_INT,123114.0,1.194828e-01,3.243570e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SUDDEN_DEER,123114.0,8.285004e-04,2.877187e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
SV_RUN_OFF_RD,123114.0,1.595188e-01,3.661607e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
TAILGATING,123114.0,5.420180e-02,2.264164e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
TRAIN,123114.0,8.122553e-05,9.012191e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
TRAIN_TROLLEY,123114.0,2.672320e-03,5.162558e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
TROLLEY,123114.0,2.591094e-03,5.083701e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
TURNPIKE,123114.0,8.122553e-06,2.850009e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
UNBELTED,123114.0,1.376692e-01,3.445538e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
UNDERAGE_DRNK_DRV,123114.0,2.379908e-03,4.872641e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
UNLICENSED,123114.0,1.611515e-02,1.259189e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
UNSIGNALIZED_INT,123114.0,2.068002e-01,4.050126e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
VEHICLE_FAILURE,123114.0,3.735562e-02,1.896325e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
VEHICLE_TOWED,123114.0,6.521598e-01,4.762869e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
WET_ROAD,123114.0,1.783631e-01,3.828197e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
WORK_ZONE,123114.0,1.185080e-02,1.082149e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00

### 2.2.2 roadway data 2007-2017 (roadway segment level)

In [38]:
df_roadway_07_17.head(2).transpose()

                                      0                          1
ACCESS_CTRL                           1                        NaN
ADJ_RDWY_SEQ                          3                          4
COUNTY                               67                         67
COUNTY_NAME                         NaN                        NaN
COUNTY_YEAR   ROADWAY_2007_Philadelphia  ROADWAY_2007_Philadelphia
CRASH_YEAR                         2007                       2007
CRN                          2007014726                 2008053049
LANE_COUNT                            2                          2
MUNICIPALITY                      67301                      67301
OFFSET                              190                        NaN
RDWY_ORIENT                           W                          E
RDWY_SEQ_NUM                          3                          3
ROAD_OWNER                            1                          4
ROUTE                              0076                        NaN
SEGMENT                            3401                        NaN
SPEED_LIMIT                          50                         35
STREET_NAME               SCHUYLKILL EX                  HAINES ST

In [39]:
df_roadway_07_17.columns

Index(['ACCESS_CTRL', 'ADJ_RDWY_SEQ', 'COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR',
       'CRASH_YEAR', 'CRN', 'LANE_COUNT', 'MUNICIPALITY', 'OFFSET',
       'RDWY_ORIENT', 'RDWY_SEQ_NUM', 'ROAD_OWNER', 'ROUTE', 'SEGMENT',
       'SPEED_LIMIT', 'STREET_NAME'],
      dtype='object')

In [40]:
df_roadway_07_17['CRN'].count()

216211

In [41]:
df_roadway_07_17['CRN'].nunique()

123679

In [42]:
df_roadway_07_17['CRASH_YEAR'].value_counts().sort_index()

2007    20213
2008    18242
2009    19243
2010    19627
2011    19500
2012    20186
2013    19777
2014    18563
2015    19998
2016    21334
2017    19528
Name: CRASH_YEAR, dtype: int64

In [43]:
df_roadway_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    11661
2008    10707
2009    10783
2010    11135
2011    10972
2012    11471
2013    11227
2014    10704
2015    11611
2016    12248
2017    11160
Name: CRN, dtype: int64

In [44]:
df_roadway_07_17.groupby('CRASH_YEAR')['SEGMENT'].nunique().sort_index()

CRASH_YEAR
2007    191
2008    195
2009    194
2010    193
2011    197
2012    194
2013    192
2014    195
2015    194
2016    192
2017    195
Name: SEGMENT, dtype: int64

In [45]:
# check missing value
df_roadway_07_17.isnull().sum()

ACCESS_CTRL     120268
ADJ_RDWY_SEQ     19528
COUNTY               0
COUNTY_NAME     196683
COUNTY_YEAR      19528
CRASH_YEAR           0
CRN                  0
LANE_COUNT          40
MUNICIPALITY         0
OFFSET          109511
RDWY_ORIENT        248
RDWY_SEQ_NUM         0
ROAD_OWNER           0
ROUTE           108679
SEGMENT         109157
SPEED_LIMIT      38740
STREET_NAME        897
dtype: int64

In [46]:
# basic information
df_roadway_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 216211 entries, 0 to 19527
Data columns (total 17 columns):
ACCESS_CTRL     95943 non-null float64
ADJ_RDWY_SEQ    196683 non-null float64
COUNTY          216211 non-null int64
COUNTY_NAME     19528 non-null object
COUNTY_YEAR     196683 non-null object
CRASH_YEAR      216211 non-null int64
CRN             216211 non-null int64
LANE_COUNT      216171 non-null float64
MUNICIPALITY    216211 non-null int64
OFFSET          106700 non-null float64
RDWY_ORIENT     215963 non-null object
RDWY_SEQ_NUM    216211 non-null int64
ROAD_OWNER      216211 non-null int64
ROUTE           107532 non-null object
SEGMENT         107054 non-null object
SPEED_LIMIT     177471 non-null float64
STREET_NAME     215314 non-null object
dtypes: float64(5), int64(6), object(6)
memory usage: 29.7+ MB

In [47]:
# describe numeric features
df_roadway_07_17.describe()

,ACCESS_CTRL,ADJ_RDWY_SEQ,COUNTY,CRASH_YEAR,CRN,LANE_COUNT,MUNICIPALITY,OFFSET,RDWY_SEQ_NUM,ROAD_OWNER,SPEED_LIMIT
count,95943.000000,196683.000000,216211.0,216211.000000,2.162110e+05,216171.000000,216211.000000,106700.000000,216211.000000,216211.000000,177471.000000
mean,2.596906,3.606509,67.0,2012.043277,2.012223e+09,5.140199,67178.726078,1082.691078,3.607041,2.932964,31.348587
std,0.799673,0.857411,0.0,3.169175,3.150858e+06,16.959089,1940.093719,958.672513,0.856326,1.113353,9.109460
min,1.000000,3.000000,67.0,2007.000000,2.007002e+09,0.000000,2214.000000,0.000000,3.000000,1.000000,10.000000
25%,3.000000,3.000000,67.0,2009.000000,2.009121e+09,2.000000,67301.000000,168.000000,3.000000,2.000000,25.000000
50%,3.000000,3.000000,67.0,2012.000000,2.012083e+09,2.000000,67301.000000,939.000000,3.000000,4.000000,25.000000
75%,3.000000,4.000000,67.0,2015.000000,2.015062e+09,2.000000,67301.000000,1752.000000,4.000000,4.000000,35.000000
max,3.000000,12.000000,67.0,2017.000000,2.018048e+09,99.000000,67301.000000,9062.000000,12.000000,9.000000,75.000000

### 2.2.3 vehicle, commveh, cycle, trailveh data 2007-2017 (unit level)

In [48]:
df_vehicle_07_17.head(2).transpose()

                                           0                          1
AVOID_MAN_CD                             NaN                        NaN
BODY_TYPE                                  4                         75
COMM_VEH                                   N                          Y
COUNTY                                    67                         67
COUNTY_NAME                              NaN                        NaN
COUNTY_YEAR        VEHICLE_2007_Philadelphia  VEHICLE_2007_Philadelphia
CRASH_YEAR                              2007                       2007
CRN                               2012030689                 2012030689
DAMAGE_IND                                 3                          1
DVR_PRES_IND                               1                          1
EMERG_VEH_USE_CD                         NaN                        NaN
GRADE                                      1                          1
HAZMAT_IND                               NaN                          N
IMPACT_POINT                              10                          2
INS_CO                                   NaN                        NaN
INS_CO_TEL                               NaN                        NaN
INS_IND                                    Y                          Y
MAKE_CD                                   37                         82
MODEL_CD                                 UAX                        NaN
MODEL_YR                                2007                       2007
MUNICIPALITY                           67301                      67301
OWNER_DRIVER                               1                          2
PARTIAL_VIN                      1HGFA16897L                1FUJA6CK37L
PEOPLE_IN_UNIT                             1                          1
PRIN_IMP_PT                              NaN                        NaN
RDWY_ALIGNMENT                             1                          1
SPECIAL_USAGE                              0                         21
TOW_CO_NM                                NaN                        NaN
TOW_CO_TEL                               NaN                        NaN
TOW_IND                                    Y                          N
TRAVEL_DIRECTION                           S                          S
TRAVEL_SPD                                35                         35
TRL_VEH_CNT                              NaN                          1
UNDER_RIDE_IND                           NaN                        NaN
UNIT_NUM                                   2                          1
UNIT_TYPE                                  1                          1
VEH_COLOR_CD                               1                          3
VEH_MOVEMENT                               1                         15
VEH_POSITION                               6                          3
VEH_REG_STATE                             PA                         OK
VEH_ROLE_CD                                2                          1
VEH_TYPE                                   1                          5
VINA_BODY_TYPE_CD                        P4D                        TTR

In [49]:
df_vehicle_07_17.columns

Index(['AVOID_MAN_CD', 'BODY_TYPE', 'COMM_VEH', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_YEAR', 'CRN', 'DAMAGE_IND', 'DVR_PRES_IND',
       'EMERG_VEH_USE_CD', 'GRADE', 'HAZMAT_IND', 'IMPACT_POINT', 'INS_CO',
       'INS_CO_TEL', 'INS_IND', 'MAKE_CD', 'MODEL_CD', 'MODEL_YR',
       'MUNICIPALITY', 'OWNER_DRIVER', 'PARTIAL_VIN', 'PEOPLE_IN_UNIT',
       'PRIN_IMP_PT', 'RDWY_ALIGNMENT', 'SPECIAL_USAGE', 'TOW_CO_NM',
       'TOW_CO_TEL', 'TOW_IND', 'TRAVEL_DIRECTION', 'TRAVEL_SPD',
       'TRL_VEH_CNT', 'UNDER_RIDE_IND', 'UNIT_NUM', 'UNIT_TYPE',
       'VEH_COLOR_CD', 'VEH_MOVEMENT', 'VEH_POSITION', 'VEH_REG_STATE',
       'VEH_ROLE_CD', 'VEH_TYPE', 'VINA_BODY_TYPE_CD'],
      dtype='object')

In [50]:
df_vehicle_07_17['CRASH_YEAR'].value_counts().sort_index()

2007    24505
2008    22364
2009    22535
2010    23207
2011    22842
2012    23955
2013    23687
2014    22633
2015    24718
2016    26228
2017    24010
Name: CRASH_YEAR, dtype: int64

In [51]:
df_vehicle_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    11624
2008    10676
2009    10743
2010    11070
2011    10911
2012    11395
2013    11170
2014    10646
2015    11570
2016    12190
2017    11121
Name: CRN, dtype: int64

In [52]:
df_vehicle_07_17.groupby('CRASH_YEAR')['PARTIAL_VIN'].nunique().sort_index()

CRASH_YEAR
2007    16738
2008    15797
2009    15652
2010    15906
2011    15785
2012    16658
2013    16237
2014    15860
2015    17370
2016    18274
2017    16953
Name: PARTIAL_VIN, dtype: int64

In [53]:
df_vehicle_07_17['CRN'].count()

260684

In [54]:
# check missing value
df_vehicle_07_17.isnull().sum()

AVOID_MAN_CD         259131
BODY_TYPE             29568
COMM_VEH               8241
COUNTY                24010
COUNTY_NAME          236674
COUNTY_YEAR           24010
CRASH_YEAR                0
CRN                       0
DAMAGE_IND            20062
DVR_PRES_IND          20654
EMERG_VEH_USE_CD     259131
GRADE                 20106
HAZMAT_IND           218959
IMPACT_POINT          19938
INS_CO                93659
INS_CO_TEL           260684
INS_IND               28982
MAKE_CD               29185
MODEL_CD             101611
MODEL_YR              36779
MUNICIPALITY              0
OWNER_DRIVER          47342
PARTIAL_VIN           37171
PEOPLE_IN_UNIT            0
PRIN_IMP_PT          259131
RDWY_ALIGNMENT        20009
SPECIAL_USAGE         20277
TOW_CO_NM            171355
TOW_CO_TEL           260684
TOW_IND               19831
TRAVEL_DIRECTION      29602
TRAVEL_SPD            18148
TRL_VEH_CNT          121014
UNDER_RIDE_IND       259131
UNIT_NUM                  0
UNIT_TYPE                 0
VEH_COLOR_CD          21845
VEH_MOVEMENT          20127
VEH_POSITION          20192
VEH_REG_STATE         34643
VEH_ROLE_CD              16
VEH_TYPE              19801
VINA_BODY_TYPE_CD     47415
dtype: int64

In [55]:
# basic information
df_vehicle_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260684 entries, 0 to 24009
Data columns (total 43 columns):
AVOID_MAN_CD         1553 non-null float64
BODY_TYPE            231116 non-null float64
COMM_VEH             252443 non-null object
COUNTY               236674 non-null float64
COUNTY_NAME          24010 non-null object
COUNTY_YEAR          236674 non-null object
CRASH_YEAR           260684 non-null int64
CRN                  260684 non-null int64
DAMAGE_IND           240622 non-null float64
DVR_PRES_IND         240030 non-null float64
EMERG_VEH_USE_CD     1553 non-null float64
GRADE                240578 non-null float64
HAZMAT_IND           41725 non-null object
IMPACT_POINT         240746 non-null float64
INS_CO               167025 non-null object
INS_CO_TEL           0 non-null float64
INS_IND              231702 non-null object
MAKE_CD              231499 non-null object
MODEL_CD             159073 non-null object
MODEL_YR             223905 non-null float64
MUNICIPALITY         260684 non-null int64
OWNER_DRIVER         213342 non-null float64
PARTIAL_VIN          223513 non-null object
PEOPLE_IN_UNIT       260684 non-null int64
PRIN_IMP_PT          1553 non-null float64
RDWY_ALIGNMENT       240675 non-null float64
SPECIAL_USAGE        240407 non-null float64
TOW_CO_NM            89329 non-null object
TOW_CO_TEL           0 non-null float64
TOW_IND              240853 non-null object
TRAVEL_DIRECTION     231082 non-null object
TRAVEL_SPD           242536 non-null float64
TRL_VEH_CNT          139670 non-null float64
UNDER_RIDE_IND       1553 non-null float64
UNIT_NUM             260684 non-null int64
UNIT_TYPE            260684 non-null int64
VEH_COLOR_CD         238839 non-null float64
VEH_MOVEMENT         240557 non-null float64
VEH_POSITION         240492 non-null float64
VEH_REG_STATE        226041 non-null object
VEH_ROLE_CD          260668 non-null float64
VEH_TYPE             240883 non-null float64
VINA_BODY_TYPE_CD    213269 non-null object
dtypes: float64(23), int64(6), object(14)
memory usage: 87.5+ MB

In [56]:
# describe numeric features
df_vehicle_07_17.describe()

,AVOID_MAN_CD,BODY_TYPE,COUNTY,CRASH_YEAR,CRN,DAMAGE_IND,DVR_PRES_IND,EMERG_VEH_USE_CD,GRADE,IMPACT_POINT,INS_CO_TEL,MODEL_YR,MUNICIPALITY,OWNER_DRIVER,PEOPLE_IN_UNIT,PRIN_IMP_PT,RDWY_ALIGNMENT,SPECIAL_USAGE,TOW_CO_TEL,TRAVEL_SPD,TRL_VEH_CNT,UNDER_RIDE_IND,UNIT_NUM,UNIT_TYPE,VEH_COLOR_CD,VEH_MOVEMENT,VEH_POSITION,VEH_ROLE_CD,VEH_TYPE
count,1553.000000,231116.000000,236674.0,260684.000000,2.606840e+05,240622.00000,240030.000000,1553.000000,240578.000000,240746.000000,0.0,223905.000000,260684.0,213342.000000,260684.000000,1553.000000,240675.000000,240407.000000,0.0,242536.000000,139670.000000,1553.000000,260684.000000,260684.000000,238839.000000,240557.000000,240492.000000,260668.000000,240883.000000
mean,3.082421,13.157103,67.0,2012.073756,2.012249e+09,2.84592,1.297500,0.399871,1.315706,14.831333,NaN,2137.992577,67301.0,9.837571,1.274681,14.383129,1.088435,4.107830,NaN,578.028981,0.025517,0.681906,1.702694,3.934875,11.394421,6.886563,12.820006,1.572168,4.611621
std,3.894671,16.281028,0.0,3.184800,3.166129e+06,2.33843,0.762113,1.835131,1.237860,24.809480,NaN,1027.101806,0.0,27.345073,1.239162,22.609685,0.550928,18.661281,NaN,485.181883,0.263303,2.324076,1.372144,8.366665,23.651662,16.652956,27.583728,0.639569,12.785550
min,0.000000,1.000000,67.0,2007.000000,2.007002e+09,0.00000,1.000000,0.000000,1.000000,0.000000,NaN,40.000000,67301.0,0.000000,0.000000,0.000000,1.000000,0.000000,NaN,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
25%,0.000000,4.000000,67.0,2009.000000,2.009121e+09,1.00000,1.000000,0.000000,1.000000,5.000000,NaN,2000.000000,67301.0,1.000000,1.000000,6.000000,1.000000,0.000000,NaN,20.000000,0.000000,0.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000
50%,0.000000,4.000000,67.0,2012.000000,2.012089e+09,3.00000,1.000000,0.000000,1.000000,9.000000,NaN,2004.000000,67301.0,1.000000,1.000000,12.000000,1.000000,0.000000,NaN,999.000000,0.000000,0.000000,2.000000,1.000000,5.000000,1.000000,3.000000,2.000000,1.000000
75%,9.000000,15.000000,67.0,2015.000000,2.015067e+09,3.00000,1.000000,0.000000,1.000000,12.000000,NaN,2008.000000,67301.0,2.000000,1.000000,12.000000,1.000000,0.000000,NaN,999.000000,0.000000,0.000000,2.000000,1.000000,7.000000,6.000000,7.000000,2.000000,6.000000
max,9.000000,99.000000,67.0,2017.000000,2.018048e+09,9.00000,9.000000,9.000000,9.000000,99.000000,NaN,9999.000000,67301.0,99.000000,99.000000,99.000000,9.000000,99.000000,NaN,999.000000,9.000000,9.000000,99.000000,51.000000,99.000000,99.000000,99.000000,3.000000,99.000000

In [57]:
df_commveh_07_17.head(2).transpose()

                                            0                          1
AXLE_CNT                                   99                         99
CARGO_BD_TYPE                               8                          7
CARRIER_ADDR_1                 1019 E. 9TH ST        1600 ARCH ST 4TH FL
CARRIER_ADDR_2                            NaN                        NaN
CARRIER_ADDR_CITY                     CHESTER               PHILADELPHIA
CARRIER_ADDR_STATE                         PA                         PA
CARRIER_ADDR_ZIP                        19013                      99999
CARRIER_NM            DELAWARE COUNTY TRANSP.       CITY OF PHILADELPHIA
CARRIER_TEL                             1e+10                      1e+10
COUNTY                                     67                         67
COUNTY_NAME                               NaN                        NaN
COUNTY_YEAR         COMMVEH_2007_Philadelphia  COMMVEH_2007_Philadelphia
CRASH_YEAR                               2007                       2007
CRN                                2007098134                 2007098274
GVWR                                      NaN                        NaN
HAZMAT_CD1                                NaN                        NaN
HAZMAT_CD2                                NaN                        NaN
HAZMAT_CD3                                NaN                        NaN
HAZMAT_CD4                                NaN                        NaN
HAZMAT_IND                                  N                          N
HAZMAT_REL_IND1                           NaN                        NaN
HAZMAT_REL_IND2                           NaN                        NaN
HAZMAT_REL_IND3                           NaN                        NaN
HAZMAT_REL_IND4                           NaN                        NaN
ICC_NUM                                   NaN                        NaN
MUNICIPALITY                            67301                      67301
OSIZE_LOAD_IND                            NaN                        NaN
PUC_NUM                                   NaN                        NaN
UNIT_NUM                                    1                          1
USDOT_NUM                               1e+08                      1e+08
VEH_CONFIG_CD                              11                          5

In [58]:
df_commveh_07_17.columns

Index(['AXLE_CNT', 'CARGO_BD_TYPE', 'CARRIER_ADDR_1', 'CARRIER_ADDR_2',
       'CARRIER_ADDR_CITY', 'CARRIER_ADDR_STATE', 'CARRIER_ADDR_ZIP',
       'CARRIER_NM', 'CARRIER_TEL', 'COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR',
       'CRASH_YEAR', 'CRN', 'GVWR', 'HAZMAT_CD1', 'HAZMAT_CD2', 'HAZMAT_CD3',
       'HAZMAT_CD4', 'HAZMAT_IND', 'HAZMAT_REL_IND1', 'HAZMAT_REL_IND2',
       'HAZMAT_REL_IND3', 'HAZMAT_REL_IND4', 'ICC_NUM', 'MUNICIPALITY',
       'OSIZE_LOAD_IND', 'PUC_NUM', 'UNIT_NUM', 'USDOT_NUM', 'VEH_CONFIG_CD'],
      dtype='object')

In [59]:
df_commveh_07_17['CRN'].count()

7248

In [60]:
df_commveh_07_17.groupby('CRASH_YEAR')['CRN'].count().sort_index()

CRASH_YEAR
2007    695
2008    653
2009    600
2010    651
2011    622
2012    606
2013    602
2014    639
2015    709
2016    779
2017    692
Name: CRN, dtype: int64

In [61]:
df_commveh_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    663
2008    634
2009    578
2010    631
2011    605
2012    581
2013    590
2014    614
2015    687
2016    740
2017    674
Name: CRN, dtype: int64

In [62]:
df_commveh_07_17.isnull().sum()

AXLE_CNT                47
CARGO_BD_TYPE            1
CARRIER_ADDR_1           5
CARRIER_ADDR_2        6988
CARRIER_ADDR_CITY        1
CARRIER_ADDR_STATE       3
CARRIER_ADDR_ZIP         4
CARRIER_NM               0
CARRIER_TEL              4
COUNTY                   0
COUNTY_NAME           6556
COUNTY_YEAR            692
CRASH_YEAR               0
CRN                      0
GVWR                  1921
HAZMAT_CD1            7177
HAZMAT_CD2            7233
HAZMAT_CD3            7237
HAZMAT_CD4            7237
HAZMAT_IND             383
HAZMAT_REL_IND1       7177
HAZMAT_REL_IND2       7233
HAZMAT_REL_IND3       7238
HAZMAT_REL_IND4       7237
ICC_NUM               6845
MUNICIPALITY             0
OSIZE_LOAD_IND         545
PUC_NUM               7138
UNIT_NUM                 0
USDOT_NUM             4342
VEH_CONFIG_CD            2
dtype: int64

In [63]:
df_commveh_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7248 entries, 0 to 691
Data columns (total 31 columns):
AXLE_CNT              7201 non-null object
CARGO_BD_TYPE         7247 non-null float64
CARRIER_ADDR_1        7243 non-null object
CARRIER_ADDR_2        260 non-null object
CARRIER_ADDR_CITY     7247 non-null object
CARRIER_ADDR_STATE    7245 non-null object
CARRIER_ADDR_ZIP      7244 non-null object
CARRIER_NM            7248 non-null object
CARRIER_TEL           7244 non-null float64
COUNTY                7248 non-null int64
COUNTY_NAME           692 non-null object
COUNTY_YEAR           6556 non-null object
CRASH_YEAR            7248 non-null int64
CRN                   7248 non-null int64
GVWR                  5327 non-null object
HAZMAT_CD1            71 non-null float64
HAZMAT_CD2            15 non-null float64
HAZMAT_CD3            11 non-null float64
HAZMAT_CD4            11 non-null float64
HAZMAT_IND            6865 non-null object
HAZMAT_REL_IND1       71 non-null float64
HAZMAT_REL_IND2       15 non-null float64
HAZMAT_REL_IND3       10 non-null float64
HAZMAT_REL_IND4       11 non-null float64
ICC_NUM               403 non-null object
MUNICIPALITY          7248 non-null int64
OSIZE_LOAD_IND        6703 non-null object
PUC_NUM               110 non-null object
UNIT_NUM              7248 non-null int64
USDOT_NUM             2906 non-null object
VEH_CONFIG_CD         7246 non-null float64
dtypes: float64(11), int64(5), object(15)
memory usage: 1.8+ MB

In [64]:
df_commveh_07_17.describe()

,CARGO_BD_TYPE,CARRIER_TEL,COUNTY,CRASH_YEAR,CRN,HAZMAT_CD1,HAZMAT_CD2,HAZMAT_CD3,HAZMAT_CD4,HAZMAT_REL_IND1,HAZMAT_REL_IND2,HAZMAT_REL_IND3,HAZMAT_REL_IND4,MUNICIPALITY,UNIT_NUM,VEH_CONFIG_CD
count,7247.000000,7.244000e+03,7248.0,7248.000000,7.248000e+03,71.000000,15.000000,11.000000,11.000000,71.000000,15.000000,10.000000,11.000000,7248.0,7248.000000,7246.000000
mean,6.030219,8.218677e+09,67.0,2012.106512,2.012277e+09,2.971831,3.933333,4.363636,3.454545,2.028169,2.666667,2.600000,3.181818,67301.0,1.604167,14.307066
std,3.234730,2.922607e+09,0.0,3.231336,3.207050e+06,1.904670,3.239635,4.201731,1.863525,2.677802,3.287784,3.373096,3.736795,0.0,1.360878,22.492412
min,0.000000,0.000000e+00,67.0,2007.000000,2.007022e+09,1.000000,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,67301.0,1.000000,0.000000
25%,2.000000,7.177293e+09,67.0,2009.000000,2.009120e+09,2.000000,2.000000,0.000000,3.000000,1.000000,1.000000,1.000000,1.000000,67301.0,1.000000,6.000000
50%,8.000000,1.000000e+10,67.0,2012.000000,2.012098e+09,3.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,67301.0,1.000000,9.000000
75%,8.000000,1.000000e+10,67.0,2015.000000,2.015083e+09,3.000000,6.000000,9.000000,3.000000,1.000000,1.500000,1.000000,5.000000,67301.0,2.000000,11.000000
max,9.000000,1.000000e+10,67.0,2017.000000,2.018048e+09,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,67301.0,99.000000,99.000000

In [65]:
df_cycle_07_17.head(2).transpose()

                                          0                        1
COUNTY                                   67                       67
COUNTY_NAME                             NaN                      NaN
COUNTY_YEAR         CYCLE_2007_Philadelphia  CYCLE_2007_Philadelphia
CRASH_YEAR                             2007                     2007
CRN                              2007080818               2007080818
MC_BAG_IND                                N                      NaN
MC_DVR_BOOTS_IND                          N                      NaN
MC_DVR_EDC_IND                            N                      NaN
MC_DVR_EYEPRT_IND                         N                      NaN
MC_DVR_HLMTDOT_IND                        N                      NaN
MC_DVR_HLMTON_IND                         N                      NaN
MC_DVR_HLMT_TYPE                          0                      NaN
MC_DVR_LNGPNTS_IND                        Y                      NaN
MC_DVR_LNGSLV_IND                         N                      NaN
MC_ENGINE_SIZE                          650                      NaN
MC_PASSNGR_IND                            N                      NaN
MC_PAS_BOOTS_IND                        NaN                      NaN
MC_PAS_EYEPRT_IND                       NaN                      NaN
MC_PAS_HLMTDOT_IND                      NaN                      NaN
MC_PAS_HLMTON_IND                       NaN                      NaN
MC_PAS_HLMT_TYPE                        NaN                      NaN
MC_PAS_LNGPNTS_IND                      NaN                      NaN
MC_PAS_LNGSLV_IND                       NaN                      NaN
MC_TRAIL_IND                              N                      NaN
MUNICIPALITY                          67301                    67301
PC_HDLGHT_IND                           NaN                        U
PC_HLMT_IND                             NaN                        N
PC_PASSNGR_IND                          NaN                        Y
PC_REAR_RFLTR_IND                       NaN                        U
UNIT_NUM                                  1                        2

In [66]:
df_cycle_07_17.columns

Index(['COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR', 'CRASH_YEAR', 'CRN',
       'MC_BAG_IND', 'MC_DVR_BOOTS_IND', 'MC_DVR_EDC_IND', 'MC_DVR_EYEPRT_IND',
       'MC_DVR_HLMTDOT_IND', 'MC_DVR_HLMTON_IND', 'MC_DVR_HLMT_TYPE',
       'MC_DVR_LNGPNTS_IND', 'MC_DVR_LNGSLV_IND', 'MC_ENGINE_SIZE',
       'MC_PASSNGR_IND', 'MC_PAS_BOOTS_IND', 'MC_PAS_EYEPRT_IND',
       'MC_PAS_HLMTDOT_IND', 'MC_PAS_HLMTON_IND', 'MC_PAS_HLMT_TYPE',
       'MC_PAS_LNGPNTS_IND', 'MC_PAS_LNGSLV_IND', 'MC_TRAIL_IND',
       'MUNICIPALITY', 'PC_HDLGHT_IND', 'PC_HLMT_IND', 'PC_PASSNGR_IND',
       'PC_REAR_RFLTR_IND', 'UNIT_NUM'],
      dtype='object')

In [67]:
df_cycle_07_17['CRN'].count()

8533

In [68]:
df_cycle_07_17.groupby('CRASH_YEAR')['CRN'].count().sort_index()

CRASH_YEAR
2007    923
2008    630
2009    730
2010    839
2011    719
2012    746
2013    799
2014    832
2015    827
2016    803
2017    685
Name: CRN, dtype: int64

In [69]:
df_cycle_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    907
2008    620
2009    715
2010    824
2011    712
2012    732
2013    786
2014    828
2015    807
2016    790
2017    671
Name: CRN, dtype: int64

In [70]:
df_cycle_07_17.isnull().sum()

COUNTY                   0
COUNTY_NAME           7848
COUNTY_YEAR            685
CRASH_YEAR               0
CRN                      0
MC_BAG_IND            4903
MC_DVR_BOOTS_IND      4904
MC_DVR_EDC_IND        4905
MC_DVR_EYEPRT_IND     4904
MC_DVR_HLMTDOT_IND    5013
MC_DVR_HLMTON_IND     5015
MC_DVR_HLMT_TYPE      4904
MC_DVR_LNGPNTS_IND    4906
MC_DVR_LNGSLV_IND     4904
MC_ENGINE_SIZE        4904
MC_PASSNGR_IND        4894
MC_PAS_BOOTS_IND      7612
MC_PAS_EYEPRT_IND     7612
MC_PAS_HLMTDOT_IND    7613
MC_PAS_HLMTON_IND     7613
MC_PAS_HLMT_TYPE      7612
MC_PAS_LNGPNTS_IND    7612
MC_PAS_LNGSLV_IND     7612
MC_TRAIL_IND          4903
MUNICIPALITY             0
PC_HDLGHT_IND         2949
PC_HLMT_IND           2948
PC_PASSNGR_IND        2946
PC_REAR_RFLTR_IND     2949
UNIT_NUM                 0
dtype: int64

In [71]:
df_cycle_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8533 entries, 0 to 684
Data columns (total 30 columns):
COUNTY                8533 non-null int64
COUNTY_NAME           685 non-null object
COUNTY_YEAR           7848 non-null object
CRASH_YEAR            8533 non-null int64
CRN                   8533 non-null int64
MC_BAG_IND            3630 non-null object
MC_DVR_BOOTS_IND      3629 non-null object
MC_DVR_EDC_IND        3628 non-null object
MC_DVR_EYEPRT_IND     3629 non-null object
MC_DVR_HLMTDOT_IND    3520 non-null object
MC_DVR_HLMTON_IND     3518 non-null object
MC_DVR_HLMT_TYPE      3629 non-null object
MC_DVR_LNGPNTS_IND    3627 non-null object
MC_DVR_LNGSLV_IND     3629 non-null object
MC_ENGINE_SIZE        3629 non-null object
MC_PASSNGR_IND        3639 non-null object
MC_PAS_BOOTS_IND      921 non-null object
MC_PAS_EYEPRT_IND     921 non-null object
MC_PAS_HLMTDOT_IND    920 non-null object
MC_PAS_HLMTON_IND     920 non-null object
MC_PAS_HLMT_TYPE      921 non-null object
MC_PAS_LNGPNTS_IND    921 non-null object
MC_PAS_LNGSLV_IND     921 non-null object
MC_TRAIL_IND          3630 non-null object
MUNICIPALITY          8533 non-null int64
PC_HDLGHT_IND         5584 non-null object
PC_HLMT_IND           5585 non-null object
PC_PASSNGR_IND        5587 non-null object
PC_REAR_RFLTR_IND     5584 non-null object
UNIT_NUM              8533 non-null int64
dtypes: int64(5), object(25)
memory usage: 2.0+ MB

In [72]:
df_cycle_07_17.describe()

       COUNTY   CRASH_YEAR           CRN  MUNICIPALITY     UNIT_NUM
count  8533.0  8533.000000  8.533000e+03        8533.0  8533.000000
mean     67.0  2011.983476  2.012122e+09       67301.0     1.617251
std       0.0     3.162661  3.148117e+06           0.0     1.180099
min      67.0  2007.000000  2.007022e+09       67301.0     1.000000
25%      67.0  2009.000000  2.009108e+09       67301.0     1.000000
50%      67.0  2012.000000  2.012079e+09       67301.0     2.000000
75%      67.0  2015.000000  2.015062e+09       67301.0     2.000000
max      67.0  2017.000000  2.018032e+09       67301.0    99.000000

In [73]:
df_trailveh_07_17.head(2).transpose()

                                            0                           1
COUNTY                                     67                          67
COUNTY_NAME                               NaN                         NaN
COUNTY_YEAR        TRAILVEH_2007_Philadelphia  TRAILVEH_2007_Philadelphia
CRASH_YEAR                               2007                        2007
CRN                                2008000426                  2008000438
MUNICIPALITY                            67301                       67301
TRL_SEQ_NUM                                 0                           0
TRL_VEH_REG_STATE                         NaN                         NaN
TRL_VEH_TAG_NUM                           NaN                         NaN
TRL_VEH_TAG_YR                            NaN                         NaN
TRL_VEH_TYPE_CD                           NaN                         NaN
UNIT_NUM                                    1                           1

In [74]:
df_trailveh_07_17.columns

Index(['COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR', 'CRASH_YEAR', 'CRN',
       'MUNICIPALITY', 'TRL_SEQ_NUM', 'TRL_VEH_REG_STATE', 'TRL_VEH_TAG_NUM',
       'TRL_VEH_TAG_YR', 'TRL_VEH_TYPE_CD', 'UNIT_NUM'],
      dtype='object')

In [75]:
df_trailveh_07_17['CRN'].count()

2930

In [76]:
df_trailveh_07_17.groupby('CRASH_YEAR')['CRN'].count().sort_index()

CRASH_YEAR
2007    595
2008    325
2009    184
2010    196
2011    198
2012    248
2013    240
2014    212
2015    236
2016    266
2017    230
Name: CRN, dtype: int64

In [77]:
df_trailveh_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    496
2008    293
2009    179
2010    188
2011    193
2012    232
2013    233
2014    208
2015    225
2016    249
2017    225
Name: CRN, dtype: int64

In [78]:
df_trailveh_07_17.isnull().sum()

COUNTY                  0
COUNTY_NAME          2700
COUNTY_YEAR           230
CRASH_YEAR              0
CRN                     0
MUNICIPALITY            0
TRL_SEQ_NUM             0
TRL_VEH_REG_STATE    1096
TRL_VEH_TAG_NUM       852
TRL_VEH_TAG_YR       1365
TRL_VEH_TYPE_CD       428
UNIT_NUM                0
dtype: int64

In [79]:
df_trailveh_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2930 entries, 0 to 229
Data columns (total 12 columns):
COUNTY               2930 non-null int64
COUNTY_NAME          230 non-null object
COUNTY_YEAR          2700 non-null object
CRASH_YEAR           2930 non-null int64
CRN                  2930 non-null int64
MUNICIPALITY         2930 non-null int64
TRL_SEQ_NUM          2930 non-null int64
TRL_VEH_REG_STATE    1834 non-null object
TRL_VEH_TAG_NUM      2078 non-null object
TRL_VEH_TAG_YR       1565 non-null object
TRL_VEH_TYPE_CD      2502 non-null object
UNIT_NUM             2930 non-null int64
dtypes: int64(6), object(6)
memory usage: 297.6+ KB

In [80]:
df_trailveh_07_17.describe()

,COUNTY,CRASH_YEAR,CRN,MUNICIPALITY,TRL_SEQ_NUM,UNIT_NUM
count,2930.0,2930.000000,2.930000e+03,2930.0,2930.0,2930.000000
mean,67.0,2011.375085,2.011535e+09,67301.0,0.0,1.629010
std,0.0,3.446255,3.414677e+06,0.0,0.0,0.808738
min,67.0,2007.000000,2.007022e+09,67301.0,0.0,1.000000
25%,67.0,2008.000000,2.008073e+09,67301.0,0.0,1.000000
50%,67.0,2011.000000,2.011128e+09,67301.0,0.0,2.000000
75%,67.0,2014.000000,2.015003e+09,67301.0,0.0,2.000000
max,67.0,2017.000000,2.018030e+09,67301.0,0.0,19.000000

### 2.2.4 person data 2007-2017 (personal level)

In [81]:
df_person_07_17.head(2).transpose()

                                          0                         1
AGE                                      26                        19
AIRBAG_PADS                               0                         0
CLOTHING_TYPE                           NaN                       NaN
COUNTY                                   67                        67
COUNTY_NAME                             NaN                       NaN
COUNTY_YEAR        PERSON_2007_Philadelphia  PERSON_2007_Philadelphia
CRASH_YEAR                             2007                      2007
CRN                              2008016368                2008016368
DVR_LIC_STATE                            PA                        PA
DVR_PED_CONDITION                         0                         0
EJECTION_IND                              0                         0
EJECT_PATH_CD                             0                         0
EXTRIC_IND                                0                         0
INJ_SEVERITY                              4                         0
MUNICIPALITY                          67301                     67301
PED_LOCATION                            NaN                       NaN
PED_SIGNAL                              NaN                       NaN
PERSON_NUM                                2                         1
PERSON_TYPE                               2                         1
RESTRAINT_HELMET                          3                         3
SEAT_POSITION                             3                         1
SEX                                       M                         M
TRANSPORTED                             NaN                       NaN
UNIT_NUM                                  2                         2

In [82]:
df_person_07_17.columns

Index(['AGE', 'AIRBAG_PADS', 'CLOTHING_TYPE', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_YEAR', 'CRN', 'DVR_LIC_STATE',
       'DVR_PED_CONDITION', 'EJECTION_IND', 'EJECT_PATH_CD', 'EXTRIC_IND',
       'INJ_SEVERITY', 'MUNICIPALITY', 'PED_LOCATION', 'PED_SIGNAL',
       'PERSON_NUM', 'PERSON_TYPE', 'RESTRAINT_HELMET', 'SEAT_POSITION', 'SEX',
       'TRANSPORTED', 'UNIT_NUM'],
      dtype='object')

In [83]:
df_person_07_17['CRN'].count()

329269

In [84]:
df_person_07_17['CRASH_YEAR'].value_counts().sort_index()

2007    32158
2008    28967
2009    29438
2010    30010
2011    29202
2012    29943
2013    29412
2014    27965
2015    30854
2016    32410
2017    28910
Name: CRASH_YEAR, dtype: int64

In [85]:
df_person_07_17.groupby('CRASH_YEAR')['CRN'].nunique().sort_index()

CRASH_YEAR
2007    11621
2008    10673
2009    10735
2010    11054
2011    10901
2012    11354
2013    11166
2014    10643
2015    11569
2016    12190
2017    11117
Name: CRN, dtype: int64

In [86]:
# check missing value
df_person_07_17.isnull().sum()

AGE                       0
AIRBAG_PADS              56
CLOTHING_TYPE        282345
COUNTY                    0
COUNTY_NAME          300359
COUNTY_YEAR           28910
CRASH_YEAR                0
CRN                       0
DVR_LIC_STATE         37356
DVR_PED_CONDITION      1441
EJECTION_IND             44
EJECT_PATH_CD            49
EXTRIC_IND               52
INJ_SEVERITY              0
MUNICIPALITY              0
PED_LOCATION         282352
PED_SIGNAL           282352
PERSON_NUM                0
PERSON_TYPE              41
RESTRAINT_HELMET         43
SEAT_POSITION            36
SEX                      44
TRANSPORTED           83518
UNIT_NUM                  0
dtype: int64

In [87]:
# basic information
df_person_07_17.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329269 entries, 0 to 28909
Data columns (total 24 columns):
AGE                  329269 non-null int64
AIRBAG_PADS          329213 non-null float64
CLOTHING_TYPE        46924 non-null object
COUNTY               329269 non-null int64
COUNTY_NAME          28910 non-null object
COUNTY_YEAR          300359 non-null object
CRASH_YEAR           329269 non-null int64
CRN                  329269 non-null int64
DVR_LIC_STATE        291913 non-null object
DVR_PED_CONDITION    327828 non-null float64
EJECTION_IND         329225 non-null object
EJECT_PATH_CD        329220 non-null object
EXTRIC_IND           329217 non-null object
INJ_SEVERITY         329269 non-null int64
MUNICIPALITY         329269 non-null int64
PED_LOCATION         46917 non-null object
PED_SIGNAL           46917 non-null object
PERSON_NUM           329269 non-null int64
PERSON_TYPE          329228 non-null float64
RESTRAINT_HELMET     329226 non-null float64
SEAT_POSITION        329233 non-null float64
SEX                  329225 non-null object
TRANSPORTED          245751 non-null object
UNIT_NUM             329269 non-null int64
dtypes: float64(5), int64(8), object(11)
memory usage: 62.8+ MB

In [88]:
# describe numeric features
df_person_07_17.describe()

,AGE,AIRBAG_PADS,COUNTY,CRASH_YEAR,CRN,DVR_PED_CONDITION,INJ_SEVERITY,MUNICIPALITY,PERSON_NUM,PERSON_TYPE,RESTRAINT_HELMET,SEAT_POSITION,UNIT_NUM
count,329269.000000,329213.000000,329269.0,329269.000000,3.292690e+05,327828.000000,329269.000000,329269.0,329269.000000,329228.000000,329226.000000,329233.000000,329269.000000
mean,41.396800,33.330707,67.0,2011.993622,2.012167e+09,1.179161,2.678530,67301.0,2.591541,1.677491,48.149013,5.282542,1.598180
std,25.264312,45.039258,0.0,3.185807,3.167542e+06,2.960386,3.274928,0.0,8.633197,1.502902,48.531833,17.607698,0.909751
min,1.000000,0.000000,67.0,2007.000000,2.007002e+09,0.000000,0.000000,67301.0,1.000000,1.000000,0.000000,0.000000,1.000000
25%,23.000000,0.000000,67.0,2009.000000,2.009106e+09,0.000000,0.000000,67301.0,1.000000,1.000000,3.000000,1.000000,1.000000
50%,35.000000,3.000000,67.0,2012.000000,2.012076e+09,0.000000,0.000000,67301.0,1.000000,1.000000,4.000000,1.000000,2.000000
75%,53.000000,99.000000,67.0,2015.000000,2.015057e+09,0.000000,4.000000,67301.0,2.000000,2.000000,99.000000,3.000000,2.000000
max,99.000000,99.000000,67.0,2017.000000,2.018048e+09,9.000000,9.000000,67301.0,99.000000,9.000000,99.000000,99.000000,99.000000

<a id='crash'> </a>

# Step 3. Prepare crash level data

In [89]:
df_crash_07_17.head(2).transpose()

                                             0                        1
ARRIVAL_TM                                1815                      300
AUTOMOBILE_COUNT                             3                        3
BELTED_DEATH_COUNT                           0                        0
BELTED_MAJ_INJ_COUNT                         0                        0
BICYCLE_COUNT                                0                        0
BICYCLE_DEATH_COUNT                          0                        0
BICYCLE_MAJ_INJ_COUNT                        0                        0
BUS_COUNT                                    0                        0
COLLISION_TYPE                               2                        5
COMM_VEH_COUNT                               0                        0
CONS_ZONE_SPD_LIM                          NaN                      NaN
COUNTY                                      67                       67
COUNTY_NAME                                NaN                      NaN
COUNTY_YEAR            CRASH_2007_Philadelphia  CRASH_2007_Philadelphia
CRASH_MONTH                                  2                        2
CRASH_YEAR                                2007                     2007
CRN                                 2007045703               2007047000
DAY_OF_WEEK                                  2                        7
DEC_LAT                                40.0509                  39.9416
DEC_LONG                              -75.1807                 -75.1493
DISPATCH_TM                               1815                      256
DISTRICT                                     6                        6
DRIVER_COUNT_16YR                            0                        0
DRIVER_COUNT_17YR                            1                        0
DRIVER_COUNT_18YR                            0                        0
DRIVER_COUNT_19YR                            0                        0
DRIVER_COUNT_20YR                            0                        1
DRIVER_COUNT_50_64YR                         0                        0
DRIVER_COUNT_65_74YR                         0                        0
DRIVER_COUNT_75PLUS                          0                        0
EST_HRS_CLOSED                             NaN                      NaN
FATAL_COUNT                                  0                        0
HEAVY_TRUCK_COUNT                            0                        0
HOUR_OF_DAY                                 99                        2
ILLUMINATION                                 3                        6
INJURY_COUNT                                 2                        0
INTERSECT_TYPE                               0                        0
LANE_CLOSED                                  0                        0
LATITUDE                          40 03:03.000             39 56:29.734
LN_CLOSE_DIR                               NaN                      NaN
LOCATION_TYPE                                0                        0
LONGITUDE                         75 10:50.397             75 08:57.440
MAJ_INJ_COUNT                                0                        0
MAX_SEVERITY_LEVEL                           8                        0
MCYCLE_DEATH_COUNT                           0                        0
MCYCLE_MAJ_INJ_COUNT                         0                        0
MIN_INJ_COUNT                                0                        0
MOD_INJ_COUNT                                0                        0
MOTORCYCLE_COUNT                             0                        0
MUNICIPALITY                             67301                    67301
NTFY_HIWY_MAINT                              N                        N
PED_COUNT                                    0                        0
PED_DEATH_COUNT                              0                        0
PED_MAJ_INJ_COUNT                            0                        0
PERSON_COUNT                                 2                        4
POLICE_AGCY                              67301                    67301
RDWY_SURF_TYPE_CD                          NaN                      NaN
RELATION_TO_ROAD                             6                        6
ROAD_CONDITION                               0                        1
SCH_BUS_IND                                  N                        N
SCH_ZONE_IND                                 N                        N
SMALL_TRUCK_COUNT                            0                        0
SPEC_JURIS_CD                              NaN                      NaN
SUV_COUNT                                    0                        3
TCD_FUNC_CD                                  0                        3
TCD_TYPE                                     0                        2
TFC_DETOUR_IND                             NaN                      NaN
TIME_OF_DAY                               9999                      250
TOTAL_UNITS                                  3                        7
TOT_INJ_COUNT                                2                        0
UNBELTED_OCC_COUNT                           0                        2
UNB_DEATH_COUNT                              0                        0
UNB_MAJ_INJ_COUNT                            0                        0
UNK_INJ_DEG_COUNT                            2                        0
UNK_INJ_PER_COUNT                            0                        0
URBAN_RURAL                                  3                        3
VAN_COUNT                                    0                        0
VEHICLE_COUNT                                3                        7
WEATHER                                      1                        4
WORKERS_PRES                               NaN                      NaN
WORK_ZONE_IND                                N                        N
WORK_ZONE_LOC                              NaN                      NaN
WORK_ZONE_TYPE                             NaN                      NaN
WZ_CLOSE_DETOUR                            NaN                      NaN
WZ_FLAGGER                                 NaN                      NaN
WZ_LAW_OFFCR_IND                           NaN                      NaN
WZ_LN_CLOSURE                              NaN                      NaN
WZ_MOVING                                  NaN                      NaN
WZ_OTHER                                   NaN                      NaN
WZ_SHLDER_MDN                              NaN                      NaN

In [90]:
df_flag_07_17.head(2).transpose()

                                           0                       1
AGGRESSIVE_DRIVING                         0                       0
ALCOHOL_RELATED                            1                       0
BICYCLE                                    0                       0
CELL_PHONE                                 0                       0
COMM_VEHICLE                               0                       0
COUNTY                                    67                      67
COUNTY_NAME                              NaN                     NaN
COUNTY_YEAR           FLAG_2007_Philadelphia  FLAG_2007_Philadelphia
CRASH_YEAR                              2007                    2007
CRN                               2008020096              2008020233
CROSS_MEDIAN                               1                       0
CURVED_ROAD                                0                       0
CURVE_DVR_ERROR                            0                       0
DEER_RELATED                               0                       0
DISTRACTED                                 0                       0
DRINKING_DRIVER                            1                       0
DRIVER_16YR                                0                       0
DRIVER_17YR                                0                       0
DRIVER_18YR                                0                       0
DRIVER_19YR                                0                       1
DRIVER_20YR                                0                       0
DRIVER_50_64YR                             1                       1
DRIVER_65_74YR                             0                       0
DRIVER_75PLUS                              0                       0
DRUGGED_DRIVER                             0                       0
DRUG_RELATED                               0                       0
FATAL                                      1                       1
FATAL_OR_MAJ_INJ                           1                       1
FATIGUE_ASLEEP                             0                       0
FIRE_IN_VEHICLE                            0                       0
HAZARDOUS_TRUCK                            0                       0
HIT_BARRIER                                0                       0
HIT_BRIDGE                                 0                       0
HIT_DEER                                   0                       0
HIT_EMBANKMENT                             0                       0
HIT_FIXED_OBJECT                           0                       0
HIT_GDRAIL                                 0                       0
HIT_GDRAIL_END                             0                       0
HIT_PARKED_VEHICLE                         0                       0
HIT_POLE                                   0                       0
HIT_TREE_SHRUB                             0                       0
HO_OPPDIR_SDSWP                            1                       0
HVY_TRUCK_RELATED                          0                       0
ICY_ROAD                                   0                       0
ILLEGAL_DRUG_RELATED                       0                       0
ILLUMINATION_DARK                          0                       0
IMPAIRED_DRIVER                            1                       0
INJURY                                     1                       0
INJURY_OR_FATAL                            1                       1
INTERSECTION                               0                       1
INTERSTATE                                 0                       0
LIMIT_65MPH                                0                       0
LOCAL_ROAD                                 1                       1
LOCAL_ROAD_ONLY                            1                       0
MAJOR_INJURY                               0                       0
MC_DRINKING_DRIVER                         0                       0
MINOR_INJURY                               0                       0
MODERATE_INJURY                            0                       0
MOTORCYCLE                                 0                       1
MUNICIPALITY                           67301                   67301
NHTSA_AGG_DRIVING                          0                       0
NON_INTERSECTION                           1                       0
NO_CLEARANCE                               0                       0
OVERTURNED                                 0                       0
PEDESTRIAN                                 0                       0
PHANTOM_VEHICLE                            0                       0
PROPERTY_DAMAGE_ONLY                       0                       0
PSP_REPORTED                               0                       0
REAR_END                                   0                       0
RUNNING_RED_LT                             0                       0
RUNNING_STOP_SIGN                          0                       0
SCHOOL_BUS                                 0                       0
SCHOOL_BUS_UNIT                            0                       0
SCHOOL_ZONE                                0                       0
SHLDR_RELATED                              0                       0
SIGNALIZED_INT                             0                       1
SNOW_SLUSH_ROAD                            0                       0
SPEEDING                                   0                       0
SPEEDING_RELATED                           0                       0
STATE_ROAD                                 0                       1
STOP_CONTROLLED_INT                        0                       0
SUDDEN_DEER                                0                       0
SV_RUN_OFF_RD                              0                       0
TAILGATING                                 0                       0
TRAIN                                      0                       0
TRAIN_TROLLEY                              0                       0
TROLLEY                                    0                       0
TURNPIKE                                   0                       0
UNBELTED                                   0                       0
UNDERAGE_DRNK_DRV                          0                       0
UNLICENSED                                 0                       0
UNSIGNALIZED_INT                           0                       0
VEHICLE_FAILURE                            0                       0
VEHICLE_TOWED                              1                       1
WET_ROAD                                   0                       0
WORK_ZONE                                  0                       0

In [91]:
# check columns
df_crash_07_17.columns

Index(['ARRIVAL_TM', 'AUTOMOBILE_COUNT', 'BELTED_DEATH_COUNT',
       'BELTED_MAJ_INJ_COUNT', 'BICYCLE_COUNT', 'BICYCLE_DEATH_COUNT',
       'BICYCLE_MAJ_INJ_COUNT', 'BUS_COUNT', 'COLLISION_TYPE',
       'COMM_VEH_COUNT', 'CONS_ZONE_SPD_LIM', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_MONTH', 'CRASH_YEAR', 'CRN', 'DAY_OF_WEEK',
       'DEC_LAT', 'DEC_LONG', 'DISPATCH_TM', 'DISTRICT', 'DRIVER_COUNT_16YR',
       'DRIVER_COUNT_17YR', 'DRIVER_COUNT_18YR', 'DRIVER_COUNT_19YR',
       'DRIVER_COUNT_20YR', 'DRIVER_COUNT_50_64YR', 'DRIVER_COUNT_65_74YR',
       'DRIVER_COUNT_75PLUS', 'EST_HRS_CLOSED', 'FATAL_COUNT',
       'HEAVY_TRUCK_COUNT', 'HOUR_OF_DAY', 'ILLUMINATION', 'INJURY_COUNT',
       'INTERSECT_TYPE', 'LANE_CLOSED', 'LATITUDE', 'LN_CLOSE_DIR',
       'LOCATION_TYPE', 'LONGITUDE', 'MAJ_INJ_COUNT', 'MAX_SEVERITY_LEVEL',
       'MCYCLE_DEATH_COUNT', 'MCYCLE_MAJ_INJ_COUNT', 'MIN_INJ_COUNT',
       'MOD_INJ_COUNT', 'MOTORCYCLE_COUNT', 'MUNICIPALITY', 'NTFY_HIWY_MAINT',
       'PED_COUNT', 'PED_DEATH_COUNT', 'PED_MAJ_INJ_COUNT', 'PERSON_COUNT',
       'POLICE_AGCY', 'RDWY_SURF_TYPE_CD', 'RELATION_TO_ROAD',
       'ROAD_CONDITION', 'SCH_BUS_IND', 'SCH_ZONE_IND', 'SMALL_TRUCK_COUNT',
       'SPEC_JURIS_CD', 'SUV_COUNT', 'TCD_FUNC_CD', 'TCD_TYPE',
       'TFC_DETOUR_IND', 'TIME_OF_DAY', 'TOTAL_UNITS', 'TOT_INJ_COUNT',
       'UNBELTED_OCC_COUNT', 'UNB_DEATH_COUNT', 'UNB_MAJ_INJ_COUNT',
       'UNK_INJ_DEG_COUNT', 'UNK_INJ_PER_COUNT', 'URBAN_RURAL', 'VAN_COUNT',
       'VEHICLE_COUNT', 'WEATHER', 'WORKERS_PRES', 'WORK_ZONE_IND',
       'WORK_ZONE_LOC', 'WORK_ZONE_TYPE', 'WZ_CLOSE_DETOUR', 'WZ_FLAGGER',
       'WZ_LAW_OFFCR_IND', 'WZ_LN_CLOSURE', 'WZ_MOVING', 'WZ_OTHER',
       'WZ_SHLDER_MDN'],
      dtype='object')

In [92]:
df_flag_07_17.columns

Index(['AGGRESSIVE_DRIVING', 'ALCOHOL_RELATED', 'BICYCLE', 'CELL_PHONE',
       'COMM_VEHICLE', 'COUNTY', 'COUNTY_NAME', 'COUNTY_YEAR', 'CRASH_YEAR',
       'CRN', 'CROSS_MEDIAN', 'CURVED_ROAD', 'CURVE_DVR_ERROR', 'DEER_RELATED',
       'DISTRACTED', 'DRINKING_DRIVER', 'DRIVER_16YR', 'DRIVER_17YR',
       'DRIVER_18YR', 'DRIVER_19YR', 'DRIVER_20YR', 'DRIVER_50_64YR',
       'DRIVER_65_74YR', 'DRIVER_75PLUS', 'DRUGGED_DRIVER', 'DRUG_RELATED',
       'FATAL', 'FATAL_OR_MAJ_INJ', 'FATIGUE_ASLEEP', 'FIRE_IN_VEHICLE',
       'HAZARDOUS_TRUCK', 'HIT_BARRIER', 'HIT_BRIDGE', 'HIT_DEER',
       'HIT_EMBANKMENT', 'HIT_FIXED_OBJECT', 'HIT_GDRAIL', 'HIT_GDRAIL_END',
       'HIT_PARKED_VEHICLE', 'HIT_POLE', 'HIT_TREE_SHRUB', 'HO_OPPDIR_SDSWP',
       'HVY_TRUCK_RELATED', 'ICY_ROAD', 'ILLEGAL_DRUG_RELATED',
       'ILLUMINATION_DARK', 'IMPAIRED_DRIVER', 'INJURY', 'INJURY_OR_FATAL',
       'INTERSECTION', 'INTERSTATE', 'LIMIT_65MPH', 'LOCAL_ROAD',
       'LOCAL_ROAD_ONLY', 'MAJOR_INJURY', 'MC_DRINKING_DRIVER', 'MINOR_INJURY',
       'MODERATE_INJURY', 'MOTORCYCLE', 'MUNICIPALITY', 'NHTSA_AGG_DRIVING',
       'NON_INTERSECTION', 'NO_CLEARANCE', 'OVERTURNED', 'PEDESTRIAN',
       'PHANTOM_VEHICLE', 'PROPERTY_DAMAGE_ONLY', 'PSP_REPORTED', 'REAR_END',
       'RUNNING_RED_LT', 'RUNNING_STOP_SIGN', 'SCHOOL_BUS', 'SCHOOL_BUS_UNIT',
       'SCHOOL_ZONE', 'SHLDR_RELATED', 'SIGNALIZED_INT', 'SNOW_SLUSH_ROAD',
       'SPEEDING', 'SPEEDING_RELATED', 'STATE_ROAD', 'STOP_CONTROLLED_INT',
       'SUDDEN_DEER', 'SV_RUN_OFF_RD', 'TAILGATING', 'TRAIN', 'TRAIN_TROLLEY',
       'TROLLEY', 'TURNPIKE', 'UNBELTED', 'UNDERAGE_DRNK_DRV', 'UNLICENSED',
       'UNSIGNALIZED_INT', 'VEHICLE_FAILURE', 'VEHICLE_TOWED', 'WET_ROAD',
       'WORK_ZONE'],
      dtype='object')

In [93]:
# define a function to map the values 
def set_value(type_num, type_name): 
    return type_name[type_num]
  
# create the dictionary 
value_dictionary ={0: 'Non collision'
                   ,1: 'Rear-end'
                   ,2: 'Head-on'
                   ,3: 'Backing'
                   ,4: 'Angle'
                   ,5: 'Sideswipe(same dir.)'
                   ,6: 'Sideswipe(Opposite dir.)'
                   ,7: 'Hit fixed object'
                   ,8: 'Hit pedestrian'
                   ,9: 'Other or Unknow'
                  } 
  
# Add a new column 
df_crash_07_17['collision_type_name'] = df_crash_07_17['COLLISION_TYPE'].apply(set_value, args =(value_dictionary, )) 
  
# Print the DataFrame 
df_crash_07_17[['COLLISION_TYPE','collision_type_name']].head(100)

    COLLISION_TYPE       collision_type_name
0                2                   Head-on
1                5      Sideswipe(same dir.)
2                1                  Rear-end
3                7          Hit fixed object
4                6  Sideswipe(Opposite dir.)
5                4                     Angle
6                1                  Rear-end
7                4                     Angle
8                5      Sideswipe(same dir.)
9                7          Hit fixed object
10               2                   Head-on
11               4                     Angle
12               1                  Rear-end
13               4                     Angle
14               1                  Rear-end
15               8            Hit pedestrian
16               7          Hit fixed object
17               8            Hit pedestrian
18               1                  Rear-end
19               6  Sideswipe(Opposite dir.)
20               1                  Rear-end
21               8            Hit pedestrian
22               1                  Rear-end
23               8            Hit pedestrian
24               4                     Angle
25               2                   Head-on
26               2                   Head-on
27               4                     Angle
28               1                  Rear-end
29               2                   Head-on
30               1                  Rear-end
31               4                     Angle
32               1                  Rear-end
33               4                     Angle
34               1                  Rear-end
35               8            Hit pedestrian
36               4                     Angle
37               7          Hit fixed object
38               4                     Angle
39               4                     Angle
40               4                     Angle
41               5      Sideswipe(same dir.)
42               1                  Rear-end
43               7          Hit fixed object
44               1                  Rear-end
45               1                  Rear-end
46               4                     Angle
47               2                   Head-on
48               4                     Angle
49               2                   Head-on
50               4                     Angle
51               1                  Rear-end
52               4                     Angle
53               1                  Rear-end
54               5      Sideswipe(same dir.)
55               5      Sideswipe(same dir.)
56               4                     Angle
57               4                     Angle
58               4                     Angle
59               1                  Rear-end
60               7          Hit fixed object
61               4                     Angle
62               1                  Rear-end
63               1                  Rear-end
64               8            Hit pedestrian
65               7          Hit fixed object
66               8            Hit pedestrian
67               1                  Rear-end
68               8            Hit pedestrian
69               7          Hit fixed object
70               1                  Rear-end
71               1                  Rear-end
72               8            Hit pedestrian
73               1                  Rear-end
74               4                     Angle
75               7          Hit fixed object
76               7          Hit fixed object
77               7          Hit fixed object
78               8            Hit pedestrian
79               4                     Angle
80               4                     Angle
81               8            Hit pedestrian
82               2                   Head-on
83               7          Hit fixed object
84               4                     Angle
85               8            Hit pedestrian
86               1                  Rear-end
87               4                     Angle
88               4                     Angle
89               1                  Rear-end
90               1                  Rear-end
91               1                  Rear-end
92               8            Hit pedestrian
93               2                   Head-on
94               0             Non collision
95               7          Hit fixed object
96               1                  Rear-end
97               7          Hit fixed object
98               8            Hit pedestrian
99               1                  Rear-end

In [94]:
df_tmp = df_crash_07_17.groupby('collision_type_name').agg({'CRN':'count','FATAL_COUNT':'sum','MAJ_INJ_COUNT':'sum'})

In [95]:
#df_tmp['pctg_fatal'] = df_tmp['FATAL_COUNT']/df_tmp['CRN']
df_tmp.to_csv('tmp.csv')

In [97]:
df_crash_07_17.groupby('COUNTY')['CRN'].count()

COUNTY
67    123116
Name: CRN, dtype: int64

In [98]:
# drop duplicae variables 
df_tmp_left = df_crash_07_17.drop(['COUNTY_YEAR','MUNICIPALITY','CRASH_YEAR','COUNTY','COUNTY_NAME'],axis=1)
df_tmp_right = df_flag_07_17.drop(['COUNTY_YEAR','MUNICIPALITY','COUNTY','COUNTY_NAME'],axis=1)

In [99]:
df_crash_flg_07_17 = pd.merge(df_tmp_left, df_tmp_right, on='CRN', how='left')

In [100]:
df_crash_flg_07_17.head(2).transpose()

                                  0                     1
ARRIVAL_TM                     1815                   300
AUTOMOBILE_COUNT                  3                     3
BELTED_DEATH_COUNT                0                     0
BELTED_MAJ_INJ_COUNT              0                     0
BICYCLE_COUNT                     0                     0
BICYCLE_DEATH_COUNT               0                     0
BICYCLE_MAJ_INJ_COUNT             0                     0
BUS_COUNT                         0                     0
COLLISION_TYPE                    2                     5
COMM_VEH_COUNT                    0                     0
CONS_ZONE_SPD_LIM               NaN                   NaN
CRASH_MONTH                       2                     2
CRN                      2007045703            2007047000
DAY_OF_WEEK                       2                     7
DEC_LAT                     40.0509               39.9416
DEC_LONG                   -75.1807              -75.1493
DISPATCH_TM                    1815                   256
DISTRICT                          6                     6
DRIVER_COUNT_16YR                 0                     0
DRIVER_COUNT_17YR                 1                     0
DRIVER_COUNT_18YR                 0                     0
DRIVER_COUNT_19YR                 0                     0
DRIVER_COUNT_20YR                 0                     1
DRIVER_COUNT_50_64YR              0                     0
DRIVER_COUNT_65_74YR              0                     0
DRIVER_COUNT_75PLUS               0                     0
EST_HRS_CLOSED                  NaN                   NaN
FATAL_COUNT                       0                     0
HEAVY_TRUCK_COUNT                 0                     0
HOUR_OF_DAY                      99                     2
ILLUMINATION                      3                     6
INJURY_COUNT                      2                     0
INTERSECT_TYPE                    0                     0
LANE_CLOSED                       0                     0
LATITUDE               40 03:03.000          39 56:29.734
LN_CLOSE_DIR                    NaN                   NaN
LOCATION_TYPE                     0                     0
LONGITUDE              75 10:50.397          75 08:57.440
MAJ_INJ_COUNT                     0                     0
MAX_SEVERITY_LEVEL                8                     0
MCYCLE_DEATH_COUNT                0                     0
MCYCLE_MAJ_INJ_COUNT              0                     0
MIN_INJ_COUNT                     0                     0
MOD_INJ_COUNT                     0                     0
MOTORCYCLE_COUNT                  0                     0
NTFY_HIWY_MAINT                   N                     N
PED_COUNT                         0                     0
PED_DEATH_COUNT                   0                     0
PED_MAJ_INJ_COUNT                 0                     0
PERSON_COUNT                      2                     4
POLICE_AGCY                   67301                 67301
RDWY_SURF_TYPE_CD               NaN                   NaN
RELATION_TO_ROAD                  6                     6
ROAD_CONDITION                    0                     1
SCH_BUS_IND                       N                     N
SCH_ZONE_IND                      N                     N
SMALL_TRUCK_COUNT                 0                     0
SPEC_JURIS_CD                   NaN                   NaN
SUV_COUNT                         0                     3
TCD_FUNC_CD                       0                     3
TCD_TYPE                          0                     2
TFC_DETOUR_IND                  NaN                   NaN
TIME_OF_DAY                    9999                   250
TOTAL_UNITS                       3                     7
TOT_INJ_COUNT                     2                     0
UNBELTED_OCC_COUNT                0                     2
UNB_DEATH_COUNT                   0                     0
UNB_MAJ_INJ_COUNT                 0                     0
UNK_INJ_DEG_COUNT                 2                     0
UNK_INJ_PER_COUNT                 0                     0
URBAN_RURAL                       3                     3
VAN_COUNT                         0                     0
VEHICLE_COUNT                     3                     7
WEATHER                           1                     4
WORKERS_PRES                    NaN                   NaN
WORK_ZONE_IND                     N                     N
WORK_ZONE_LOC                   NaN                   NaN
WORK_ZONE_TYPE                  NaN                   NaN
WZ_CLOSE_DETOUR                 NaN                   NaN
WZ_FLAGGER                      NaN                   NaN
WZ_LAW_OFFCR_IND                NaN                   NaN
WZ_LN_CLOSURE                   NaN                   NaN
WZ_MOVING                       NaN                   NaN
WZ_OTHER                        NaN                   NaN
WZ_SHLDER_MDN                   NaN                   NaN
collision_type_name         Head-on  Sideswipe(same dir.)
AGGRESSIVE_DRIVING                0                     0
ALCOHOL_RELATED                   0                     0
BICYCLE                           0                     0
CELL_PHONE                        0                     0
COMM_VEHICLE                      0                     0
CRASH_YEAR                     2007                  2007
CROSS_MEDIAN                      0                     0
CURVED_ROAD                       0                     0
CURVE_DVR_ERROR                   0                     0
DEER_RELATED                      0                     0
DISTRACTED                        1                     0
DRINKING_DRIVER                   0                     0
DRIVER_16YR                       0                     0
DRIVER_17YR                       1                     0
DRIVER_18YR                       0                     0
DRIVER_19YR                       0                     0
DRIVER_20YR                       0                     1
DRIVER_50_64YR                    0                     0
DRIVER_65_74YR                    0                     0
DRIVER_75PLUS                     0                     0
DRUGGED_DRIVER                    0                     0
DRUG_RELATED                      0                     0
FATAL                             0                     0
FATAL_OR_MAJ_INJ                  0                     0
FATIGUE_ASLEEP                    0                     0
FIRE_IN_VEHICLE                   0                     0
HAZARDOUS_TRUCK                   0                     0
HIT_BARRIER                       0                     0
HIT_BRIDGE                        0                     0
HIT_DEER                          0                     0
HIT_EMBANKMENT                    0                     0
HIT_FIXED_OBJECT                  0                     0
HIT_GDRAIL                        0                     0
HIT_GDRAIL_END                    0                     0
HIT_PARKED_VEHICLE                1                     1
HIT_POLE                          0                     0
HIT_TREE_SHRUB                    0                     0
HO_OPPDIR_SDSWP                   1                     0
HVY_TRUCK_RELATED                 0                     0
ICY_ROAD                          0                     0
ILLEGAL_DRUG_RELATED              0                     0
ILLUMINATION_DARK                 1                     1
IMPAIRED_DRIVER                   0                     0
INJURY                            1                     0
INJURY_OR_FATAL                   1                     0
INTERSECTION                      0                     0
INTERSTATE                        0                     0
LIMIT_65MPH                       0                     0
LOCAL_ROAD                        0                     1
LOCAL_ROAD_ONLY                   0                     1
MAJOR_INJURY                      0                     0
MC_DRINKING_DRIVER                0                     0
MINOR_INJURY                      0                     0
MODERATE_INJURY                   0                     0
MOTORCYCLE                        0                     0
NHTSA_AGG_DRIVING                 0                     0
NON_INTERSECTION                  1                     1
NO_CLEARANCE                      0                     0
OVERTURNED                        0                     0
PEDESTRIAN                        0                     0
PHANTOM_VEHICLE                   0                     0
PROPERTY_DAMAGE_ONLY              0                     1
PSP_REPORTED                      0                     0
REAR_END                          0                     0
RUNNING_RED_LT                    0                     0
RUNNING_STOP_SIGN                 0                     0
SCHOOL_BUS                        0                     0
SCHOOL_BUS_UNIT                   0                     0
SCHOOL_ZONE                       0                     0
SHLDR_RELATED                     0                     0
SIGNALIZED_INT                    0                     0
SNOW_SLUSH_ROAD                   0                     0
SPEEDING                          0                     0
SPEEDING_RELATED                  0                     0
STATE_ROAD                        1                     0
STOP_CONTROLLED_INT               0                     0
SUDDEN_DEER                       0                     0
SV_RUN_OFF_RD                     0                     0
TAILGATING                        0                     0
TRAIN                             0                     0
TRAIN_TROLLEY                     0                     0
TROLLEY                           0                     0
TURNPIKE                          0                     0
UNBELTED                          0                     1
UNDERAGE_DRNK_DRV                 0                     0
UNLICENSED                        0                     0
UNSIGNALIZED_INT                  0                     0
VEHICLE_FAILURE                   0                     0
VEHICLE_TOWED                     1                     1
WET_ROAD                          0                     1
WORK_ZONE                         0                     0

In [102]:
#pd.options.display.max_rows = 500

df_crash_flg_07_17.isnull().sum()

ARRIVAL_TM                  978
AUTOMOBILE_COUNT              0
BELTED_DEATH_COUNT            0
BELTED_MAJ_INJ_COUNT          0
BICYCLE_COUNT                 0
BICYCLE_DEATH_COUNT           0
BICYCLE_MAJ_INJ_COUNT         0
BUS_COUNT                     0
COLLISION_TYPE                0
COMM_VEH_COUNT                0
CONS_ZONE_SPD_LIM        110648
CRASH_MONTH                   0
CRN                           0
DAY_OF_WEEK                   0
DEC_LAT                    1294
DEC_LONG                   1294
DISPATCH_TM                1074
DISTRICT                      0
DRIVER_COUNT_16YR             0
DRIVER_COUNT_17YR             0
DRIVER_COUNT_18YR             0
DRIVER_COUNT_19YR             0
DRIVER_COUNT_20YR             0
DRIVER_COUNT_50_64YR          0
DRIVER_COUNT_65_74YR          0
DRIVER_COUNT_75PLUS           0
EST_HRS_CLOSED            79648
FATAL_COUNT                   0
HEAVY_TRUCK_COUNT             0
HOUR_OF_DAY                   9
ILLUMINATION                  9
INJURY_COUNT                  0
INTERSECT_TYPE                0
LANE_CLOSED                   0
LATITUDE                   1247
LN_CLOSE_DIR              79650
LOCATION_TYPE                 0
LONGITUDE                  1247
MAJ_INJ_COUNT                 0
MAX_SEVERITY_LEVEL            0
MCYCLE_DEATH_COUNT            0
MCYCLE_MAJ_INJ_COUNT          0
MIN_INJ_COUNT                 0
MOD_INJ_COUNT                 0
MOTORCYCLE_COUNT              0
NTFY_HIWY_MAINT           32301
PED_COUNT                     0
PED_DEATH_COUNT               0
PED_MAJ_INJ_COUNT             0
PERSON_COUNT                  0
POLICE_AGCY                  80
RDWY_SURF_TYPE_CD        111090
RELATION_TO_ROAD              3
ROAD_CONDITION                5
SCH_BUS_IND                7597
SCH_ZONE_IND              21488
SMALL_TRUCK_COUNT             0
SPEC_JURIS_CD            111090
SUV_COUNT                     0
TCD_FUNC_CD                   6
TCD_TYPE                      0
TFC_DETOUR_IND            79647
TIME_OF_DAY                   9
TOTAL_UNITS                   0
TOT_INJ_COUNT                 0
UNBELTED_OCC_COUNT            0
UNB_DEATH_COUNT               0
UNB_MAJ_INJ_COUNT             0
UNK_INJ_DEG_COUNT             0
UNK_INJ_PER_COUNT             0
URBAN_RURAL                   0
VAN_COUNT                     0
VEHICLE_COUNT                 0
WEATHER                      18
WORKERS_PRES             110648
WORK_ZONE_IND                 0
WORK_ZONE_LOC            110648
WORK_ZONE_TYPE           110648
WZ_CLOSE_DETOUR          110869
WZ_FLAGGER               110877
WZ_LAW_OFFCR_IND         110648
WZ_LN_CLOSURE            110783
WZ_MOVING                110866
WZ_OTHER                 110861
WZ_SHLDER_MDN            110850
collision_type_name           0
AGGRESSIVE_DRIVING            2
ALCOHOL_RELATED               2
BICYCLE                       2
CELL_PHONE                    2
COMM_VEHICLE                  2
CRASH_YEAR                    2
CROSS_MEDIAN                  2
CURVED_ROAD                   2
CURVE_DVR_ERROR               2
DEER_RELATED                  2
DISTRACTED                    2
DRINKING_DRIVER               2
DRIVER_16YR                   2
DRIVER_17YR                   2
DRIVER_18YR                   2
DRIVER_19YR                   2
DRIVER_20YR                   2
DRIVER_50_64YR                2
DRIVER_65_74YR                2
DRIVER_75PLUS                 2
DRUGGED_DRIVER                2
DRUG_RELATED                  2
FATAL                         2
FATAL_OR_MAJ_INJ              2
FATIGUE_ASLEEP                2
FIRE_IN_VEHICLE               2
HAZARDOUS_TRUCK               2
HIT_BARRIER                   2
HIT_BRIDGE                    2
HIT_DEER                      2
HIT_EMBANKMENT                2
HIT_FIXED_OBJECT              2
HIT_GDRAIL                    2
HIT_GDRAIL_END                2
HIT_PARKED_VEHICLE            2
HIT_POLE                      2
HIT_TREE_SHRUB                2
HO_OPPDIR_SDSWP               2
HVY_TRUCK_RELATED             2
ICY_ROAD                      2
ILLEGAL_DRUG_RELATED          2
ILLUMINATION_DARK             2
IMPAIRED_DRIVER               2
INJURY                        2
INJURY_OR_FATAL               2
INTERSECTION                  2
INTERSTATE                    2
LIMIT_65MPH                   2
LOCAL_ROAD                    2
LOCAL_ROAD_ONLY               2
MAJOR_INJURY                  2
MC_DRINKING_DRIVER            2
MINOR_INJURY                  2
MODERATE_INJURY               2
MOTORCYCLE                    2
NHTSA_AGG_DRIVING             2
NON_INTERSECTION              2
NO_CLEARANCE                  2
OVERTURNED                    2
PEDESTRIAN                    2
PHANTOM_VEHICLE               2
PROPERTY_DAMAGE_ONLY          2
PSP_REPORTED                  2
REAR_END                      2
RUNNING_RED_LT                2
RUNNING_STOP_SIGN             2
SCHOOL_BUS                    2
SCHOOL_BUS_UNIT               2
SCHOOL_ZONE                   2
SHLDR_RELATED                 2
SIGNALIZED_INT                2
SNOW_SLUSH_ROAD               2
SPEEDING                      2
SPEEDING_RELATED              2
STATE_ROAD                    2
STOP_CONTROLLED_INT           2
SUDDEN_DEER                   2
SV_RUN_OFF_RD                 2
TAILGATING                    2
TRAIN                         2
TRAIN_TROLLEY                 2
TROLLEY                       2
TURNPIKE                      2
UNBELTED                      2
UNDERAGE_DRNK_DRV             2
UNLICENSED                    2
UNSIGNALIZED_INT              2
VEHICLE_FAILURE               2
VEHICLE_TOWED                 2
WET_ROAD                      2
WORK_ZONE                     2
dtype: int64

In [243]:
df_crash_flg_07_17.to_csv('df_crash_flg_07_17.csv')

<a id='roadway'> </a>

# Step 4 Prepare roadway data

In [103]:
df_roadway_07_17.head(2).transpose()

                                      0                          1
ACCESS_CTRL                           1                        NaN
ADJ_RDWY_SEQ                          3                          4
COUNTY                               67                         67
COUNTY_NAME                         NaN                        NaN
COUNTY_YEAR   ROADWAY_2007_Philadelphia  ROADWAY_2007_Philadelphia
CRASH_YEAR                         2007                       2007
CRN                          2007014726                 2008053049
LANE_COUNT                            2                          2
MUNICIPALITY                      67301                      67301
OFFSET                              190                        NaN
RDWY_ORIENT                           W                          E
RDWY_SEQ_NUM                          3                          3
ROAD_OWNER                            1                          4
ROUTE                              0076                        NaN
SEGMENT                            3401                        NaN
SPEED_LIMIT                          50                         35
STREET_NAME               SCHUYLKILL EX                  HAINES ST

In [104]:
df_tmp = df_roadway_07_17[['CRN','LANE_COUNT','ROAD_OWNER','SPEED_LIMIT']]
df_tmp.head(2)

          CRN  LANE_COUNT  ROAD_OWNER  SPEED_LIMIT
0  2007014726         2.0           1         50.0
1  2008053049         2.0           4         35.0

In [105]:
df_tmp['road_01_interstate'] = df_tmp['ROAD_OWNER'].apply(lambda x: 1 if x == 1 else 0)
df_tmp['road_02_state'] = df_tmp['ROAD_OWNER'].apply(lambda x: 1 if (x == 2)|(x == 5)|(x == 6) else 0)
df_tmp['road_03_local'] = df_tmp['ROAD_OWNER'].apply(lambda x: 1 if (x == 3)|(x == 4) else 0)
df_tmp['road_04_other'] = df_tmp['ROAD_OWNER'].apply(lambda x: 1 if (x == 7)|(x == 8)|(x== 9) else 0)

In [106]:
df_tmp.groupby('ROAD_OWNER')['road_04_other'].sum()

ROAD_OWNER
1      0
2      0
3      0
4      0
5      0
7    171
9     40
Name: road_04_other, dtype: int64

In [107]:
df_tmp.head(2)

,CRN,LANE_COUNT,ROAD_OWNER,SPEED_LIMIT,road_01_interstate,road_02_state,road_03_local,road_04_other
0,2007014726,2.0,1,50.0,1,0,0,0
1,2008053049,2.0,4,35.0,0,0,1,0

In [108]:
df_tmp1 = df_tmp.groupby('CRN').agg({'road_01_interstate':'sum','road_02_state':'sum','road_03_local':'sum','road_04_other':'sum'}).reset_index()
df_tmp1.head(2)

          CRN  road_01_interstate  road_02_state  road_03_local  road_04_other
0  2007001504                   0              1              0              0
1  2007001511                   0              1              0              0

In [109]:
df_tmp1.columns

Index(['CRN', 'road_01_interstate', 'road_02_state', 'road_03_local',
       'road_04_other'],
      dtype='object')

In [110]:
df_tmp1['road_04_other'].sum()

211

In [111]:
df_tmp1['CRN'].count()

123679

In [112]:
df_tmp2 = df_tmp.groupby('CRN').agg({'CRN':'count','LANE_COUNT':['min','max'],'SPEED_LIMIT':['nunique','min','max']}).reset_index()
df_tmp2.columns = ["_".join(x) for x in df_tmp2.columns.ravel()]
df_tmp2 = df_tmp2.rename(columns={'CRN_': 'CRN','CRN_count':'cnt_road_segments'})
df_tmp2.head(2)

,CRN,cnt_road_segments,LANE_COUNT_min,LANE_COUNT_max,SPEED_LIMIT_nunique,SPEED_LIMIT_min,SPEED_LIMIT_max
0,2007001504,1,2.0,2.0,1,35.0,35.0
1,2007001511,1,2.0,2.0,1,35.0,35.0

In [113]:
df_tmp2.columns

Index(['CRN', 'cnt_road_segments', 'LANE_COUNT_min', 'LANE_COUNT_max',
       'SPEED_LIMIT_nunique', 'SPEED_LIMIT_min', 'SPEED_LIMIT_max'],
      dtype='object')

In [114]:
df_tmp2['CRN'].count()

123679

In [115]:
df_roadway_07_17_crn_lvl = pd.merge(df_tmp1, df_tmp2, on='CRN', how='inner')
df_roadway_07_17_crn_lvl.head(2)

,CRN,road_01_interstate,road_02_state,road_03_local,road_04_other,cnt_road_segments,LANE_COUNT_min,LANE_COUNT_max,SPEED_LIMIT_nunique,SPEED_LIMIT_min,SPEED_LIMIT_max
0,2007001504,0,1,0,0,1,2.0,2.0,1,35.0,35.0
1,2007001511,0,1,0,0,1,2.0,2.0,1,35.0,35.0

In [244]:
df_roadway_07_17_crn_lvl = df_roadway_07_17_crn_lvl.rename(columns={'road_01_interstate': 'cnt_road_01_interstate',
                                                                    'road_02_state':'cnt_road_02_state',
                                                                    'road_03_local':'cnt_road_03_local',
                                                                    'road_04_other':'cnt_road_04_other',
                                                                   })

In [245]:
df_roadway_07_17_crn_lvl.columns

Index(['CRN', 'cnt_road_01_interstate', 'cnt_road_02_state',
       'cnt_road_03_local', 'cnt_road_04_other', 'cnt_road_segments',
       'LANE_COUNT_min', 'LANE_COUNT_max', 'SPEED_LIMIT_nunique',
       'SPEED_LIMIT_min', 'SPEED_LIMIT_max'],
      dtype='object')

In [117]:
df_roadway_07_17_crn_lvl.isnull().sum()

CRN                        0
road_01_interstate         0
road_02_state              0
road_03_local              0
road_04_other              0
cnt_road_segments          0
LANE_COUNT_min             2
LANE_COUNT_max             2
SPEED_LIMIT_nunique        0
SPEED_LIMIT_min        14554
SPEED_LIMIT_max        14554
dtype: int64

In [246]:
df_roadway_07_17_crn_lvl.to_csv('df_roadway_07_17_crn_lvl.csv')

<a id='vehicle'> </a>

# Step 5. Prepare vehicle data

## 5.1 Vehicle data

In [118]:
df_vehicle_07_17.head(2).transpose()

                                           0                          1
AVOID_MAN_CD                             NaN                        NaN
BODY_TYPE                                  4                         75
COMM_VEH                                   N                          Y
COUNTY                                    67                         67
COUNTY_NAME                              NaN                        NaN
COUNTY_YEAR        VEHICLE_2007_Philadelphia  VEHICLE_2007_Philadelphia
CRASH_YEAR                              2007                       2007
CRN                               2012030689                 2012030689
DAMAGE_IND                                 3                          1
DVR_PRES_IND                               1                          1
EMERG_VEH_USE_CD                         NaN                        NaN
GRADE                                      1                          1
HAZMAT_IND                               NaN                          N
IMPACT_POINT                              10                          2
INS_CO                                   NaN                        NaN
INS_CO_TEL                               NaN                        NaN
INS_IND                                    Y                          Y
MAKE_CD                                   37                         82
MODEL_CD                                 UAX                        NaN
MODEL_YR                                2007                       2007
MUNICIPALITY                           67301                      67301
OWNER_DRIVER                               1                          2
PARTIAL_VIN                      1HGFA16897L                1FUJA6CK37L
PEOPLE_IN_UNIT                             1                          1
PRIN_IMP_PT                              NaN                        NaN
RDWY_ALIGNMENT                             1                          1
SPECIAL_USAGE                              0                         21
TOW_CO_NM                                NaN                        NaN
TOW_CO_TEL                               NaN                        NaN
TOW_IND                                    Y                          N
TRAVEL_DIRECTION                           S                          S
TRAVEL_SPD                                35                         35
TRL_VEH_CNT                              NaN                          1
UNDER_RIDE_IND                           NaN                        NaN
UNIT_NUM                                   2                          1
UNIT_TYPE                                  1                          1
VEH_COLOR_CD                               1                          3
VEH_MOVEMENT                               1                         15
VEH_POSITION                               6                          3
VEH_REG_STATE                             PA                         OK
VEH_ROLE_CD                                2                          1
VEH_TYPE                                   1                          5
VINA_BODY_TYPE_CD                        P4D                        TTR

In [119]:
df_vehicle_07_17.groupby('DAMAGE_IND')['CRN'].count()

DAMAGE_IND
0.0     16571
1.0     46662
2.0     49990
3.0    101407
9.0     25992
Name: CRN, dtype: int64

In [120]:
df_tmp = df_vehicle_07_17[['CRN','UNIT_NUM','CRASH_YEAR']]
df_tmp['unique_key'] = df_tmp['CRN'].map(str)+'_'+df_tmp['UNIT_NUM'].map(str)
df_tmp.head(2)

          CRN  UNIT_NUM  CRASH_YEAR    unique_key
0  2012030689         2        2007  2012030689_2
1  2012030689         1        2007  2012030689_1

In [121]:
df_tmp['CRN'].count()

260684

In [122]:
df_tmp['unique_key'].nunique()

260684

In [123]:
df_vehicle_07_17.groupby('VEH_ROLE_CD')['CRN'].count()

VEH_ROLE_CD
0.0      2552
1.0    125274
2.0    113986
3.0     18856
Name: CRN, dtype: int64

In [124]:
df_vehicle_07_17[df_vehicle_07_17['UNIT_TYPE'] == 1].groupby('VEH_TYPE')['CRN'].count()

VEH_TYPE
1.0     128530
2.0       3304
3.0       2998
4.0      12179
5.0       3907
6.0      34285
7.0      11481
11.0         2
12.0        34
13.0       195
18.0        21
20.0         3
21.0         8
24.0         2
25.0       313
98.0        15
99.0       718
Name: CRN, dtype: int64

In [156]:
df_tmp_vehicle = df_vehicle_07_17[['CRN','UNIT_NUM','HAZMAT_IND','MODEL_YR','TRAVEL_SPD','UNIT_TYPE']]
df_tmp_vehicle['key_crn_unit'] = df_tmp_vehicle['CRN'].map(str)+'_'+df_tmp_vehicle['UNIT_NUM'].map(str)
df_tmp_vehicle.head(2)

,CRN,UNIT_NUM,HAZMAT_IND,MODEL_YR,TRAVEL_SPD,UNIT_TYPE,key_crn_unit
0,2012030689,2,NaN,2007.0,35.0,1,2012030689_2
1,2012030689,1,N,2007.0,35.0,1,2012030689_1

In [157]:
df_tmp_vehicle.isnull().sum()

CRN                  0
UNIT_NUM             0
HAZMAT_IND      218959
MODEL_YR         36779
TRAVEL_SPD       18148
UNIT_TYPE            0
key_crn_unit         0
dtype: int64

## 5.2 Cycle data

In [127]:
df_cycle_07_17.head(2).transpose()

                                          0                        1
COUNTY                                   67                       67
COUNTY_NAME                             NaN                      NaN
COUNTY_YEAR         CYCLE_2007_Philadelphia  CYCLE_2007_Philadelphia
CRASH_YEAR                             2007                     2007
CRN                              2007080818               2007080818
MC_BAG_IND                                N                      NaN
MC_DVR_BOOTS_IND                          N                      NaN
MC_DVR_EDC_IND                            N                      NaN
MC_DVR_EYEPRT_IND                         N                      NaN
MC_DVR_HLMTDOT_IND                        N                      NaN
MC_DVR_HLMTON_IND                         N                      NaN
MC_DVR_HLMT_TYPE                          0                      NaN
MC_DVR_LNGPNTS_IND                        Y                      NaN
MC_DVR_LNGSLV_IND                         N                      NaN
MC_ENGINE_SIZE                          650                      NaN
MC_PASSNGR_IND                            N                      NaN
MC_PAS_BOOTS_IND                        NaN                      NaN
MC_PAS_EYEPRT_IND                       NaN                      NaN
MC_PAS_HLMTDOT_IND                      NaN                      NaN
MC_PAS_HLMTON_IND                       NaN                      NaN
MC_PAS_HLMT_TYPE                        NaN                      NaN
MC_PAS_LNGPNTS_IND                      NaN                      NaN
MC_PAS_LNGSLV_IND                       NaN                      NaN
MC_TRAIL_IND                              N                      NaN
MUNICIPALITY                          67301                    67301
PC_HDLGHT_IND                           NaN                        U
PC_HLMT_IND                             NaN                        N
PC_PASSNGR_IND                          NaN                        Y
PC_REAR_RFLTR_IND                       NaN                        U
UNIT_NUM                                  1                        2

In [128]:
df_cycle_07_17.groupby('MC_DVR_HLMTON_IND')['CRN'].count()

MC_DVR_HLMTON_IND
      429
N    1089
U    1510
Y     490
Name: CRN, dtype: int64

In [129]:
df_tmp_cycle = df_cycle_07_17[['CRN','UNIT_NUM','MC_DVR_EDC_IND','MC_DVR_HLMTON_IND','MC_PASSNGR_IND','PC_HDLGHT_IND','PC_HLMT_IND','PC_PASSNGR_IND','PC_REAR_RFLTR_IND']]
df_tmp_cycle['key_crn_unit'] = df_tmp_cycle['CRN'].map(str)+'_'+df_tmp_cycle['UNIT_NUM'].map(str)
df_tmp_cycle.head(2)

,CRN,UNIT_NUM,MC_DVR_EDC_IND,MC_DVR_HLMTON_IND,MC_PASSNGR_IND,PC_HDLGHT_IND,PC_HLMT_IND,PC_PASSNGR_IND,PC_REAR_RFLTR_IND,key_crn_unit
0,2007080818,1,N,N,N,NaN,NaN,NaN,NaN,2007080818_1
1,2007080818,2,NaN,NaN,NaN,U,N,Y,U,2007080818_2

In [130]:
df_tmp_cycle.drop(['CRN','UNIT_NUM'],axis=1,inplace=True)

In [131]:
df_tmp_cycle.head(2)

,MC_DVR_EDC_IND,MC_DVR_HLMTON_IND,MC_PASSNGR_IND,PC_HDLGHT_IND,PC_HLMT_IND,PC_PASSNGR_IND,PC_REAR_RFLTR_IND,key_crn_unit
0,N,N,N,NaN,NaN,NaN,NaN,2007080818_1
1,NaN,NaN,NaN,U,N,Y,U,2007080818_2

## 5.3 Commercial vehicle data (skip)

In [132]:
df_commveh_07_17.head(2).transpose()

                                            0                          1
AXLE_CNT                                   99                         99
CARGO_BD_TYPE                               8                          7
CARRIER_ADDR_1                 1019 E. 9TH ST        1600 ARCH ST 4TH FL
CARRIER_ADDR_2                            NaN                        NaN
CARRIER_ADDR_CITY                     CHESTER               PHILADELPHIA
CARRIER_ADDR_STATE                         PA                         PA
CARRIER_ADDR_ZIP                        19013                      99999
CARRIER_NM            DELAWARE COUNTY TRANSP.       CITY OF PHILADELPHIA
CARRIER_TEL                             1e+10                      1e+10
COUNTY                                     67                         67
COUNTY_NAME                               NaN                        NaN
COUNTY_YEAR         COMMVEH_2007_Philadelphia  COMMVEH_2007_Philadelphia
CRASH_YEAR                               2007                       2007
CRN                                2007098134                 2007098274
GVWR                                      NaN                        NaN
HAZMAT_CD1                                NaN                        NaN
HAZMAT_CD2                                NaN                        NaN
HAZMAT_CD3                                NaN                        NaN
HAZMAT_CD4                                NaN                        NaN
HAZMAT_IND                                  N                          N
HAZMAT_REL_IND1                           NaN                        NaN
HAZMAT_REL_IND2                           NaN                        NaN
HAZMAT_REL_IND3                           NaN                        NaN
HAZMAT_REL_IND4                           NaN                        NaN
ICC_NUM                                   NaN                        NaN
MUNICIPALITY                            67301                      67301
OSIZE_LOAD_IND                            NaN                        NaN
PUC_NUM                                   NaN                        NaN
UNIT_NUM                                    1                          1
USDOT_NUM                               1e+08                      1e+08
VEH_CONFIG_CD                              11                          5

## 5.4 Trailer vehicle data

In [133]:
df_trailveh_07_17.head(2).transpose()

                                            0                           1
COUNTY                                     67                          67
COUNTY_NAME                               NaN                         NaN
COUNTY_YEAR        TRAILVEH_2007_Philadelphia  TRAILVEH_2007_Philadelphia
CRASH_YEAR                               2007                        2007
CRN                                2008000426                  2008000438
MUNICIPALITY                            67301                       67301
TRL_SEQ_NUM                                 0                           0
TRL_VEH_REG_STATE                         NaN                         NaN
TRL_VEH_TAG_NUM                           NaN                         NaN
TRL_VEH_TAG_YR                            NaN                         NaN
TRL_VEH_TYPE_CD                           NaN                         NaN
UNIT_NUM                                    1                           1

In [134]:
df_tmp_trailer = df_trailveh_07_17[['CRN','UNIT_NUM']]
df_tmp_trailer['ind_trailer_vehicle'] = 1
df_tmp_trailer['key_crn_unit'] = df_tmp_trailer['CRN'].map(str)+'_'+df_tmp_trailer['UNIT_NUM'].map(str)
df_tmp_trailer.head(2)

          CRN  UNIT_NUM  ind_trailer_vehicle  key_crn_unit
0  2008000426         1                    1  2008000426_1
1  2008000438         1                    1  2008000438_1

In [135]:
df_tmp_trailer.drop(['CRN','UNIT_NUM'],axis=1,inplace=True)

In [136]:
df_tmp_trailer.head(2)

   ind_trailer_vehicle  key_crn_unit
0                    1  2008000426_1
1                    1  2008000438_1

## 5.5 Merge data together and roll up to crash level

In [331]:
print(df_tmp_vehicle['key_crn_unit'].count())
print(df_tmp_vehicle['key_crn_unit'].nunique())

260684
260684

In [332]:
print(df_tmp_cycle['key_crn_unit'].count())
print(df_tmp_cycle['key_crn_unit'].nunique())

8533
8533

In [333]:
df_tmp = pd.merge(df_tmp_vehicle,df_tmp_cycle,on='key_crn_unit',how='left')
df_tmp1 = pd.merge(df_tmp,df_tmp_trailer,on='key_crn_unit',how='left')

In [334]:
df_tmp['key_crn_unit'].nunique()

260684

In [335]:
df_tmp.groupby('TRAVEL_SPD')['CRN'].count()

TRAVEL_SPD
0.0       42701
1.0         523
2.0         365
3.0         218
4.0          92
5.0        4441
6.0         141
7.0          68
8.0          94
9.0          37
10.0       4911
11.0          5
12.0         24
13.0          7
14.0          7
15.0       4766
16.0          4
17.0          6
18.0         21
19.0          6
20.0       4991
21.0          3
22.0          7
23.0         16
24.0          6
25.0      10729
26.0         12
27.0          8
28.0         30
29.0         10
30.0       4417
31.0          1
32.0          9
33.0          5
34.0          5
35.0       5167
36.0          2
37.0          5
38.0         16
39.0          8
40.0       3274
41.0          1
42.0         12
43.0          5
44.0         23
45.0       2785
46.0         47
47.0          5
48.0          8
49.0          5
50.0       3663
51.0          5
52.0          3
53.0          2
54.0          2
55.0       3700
56.0         12
57.0         11
58.0         13
59.0          2
60.0       2165
61.0          5
62.0          6
63.0          2
64.0          3
65.0       1419
66.0         12
67.0          2
68.0          4
70.0        715
71.0          1
72.0          2
75.0        245
76.0          3
77.0          1
78.0          3
80.0        270
83.0          1
85.0         51
88.0          1
90.0         69
91.0          2
95.0          8
96.0          1
97.0          1
98.0          4
99.0       1477
100.0        51
101.0         2
105.0         3
110.0        13
111.0        11
114.0         1
115.0         5
120.0        18
125.0        14
130.0         9
135.0         6
140.0         3
145.0         2
150.0         4
151.0         3
152.0         1
154.0         1
157.0         1
199.0         3
200.0         3
201.0         2
202.0         3
204.0         1
205.0         1
206.0         1
208.0         2
210.0         1
215.0         1
220.0         1
225.0         1
232.0         1
250.0         3
251.0        10
252.0         1
261.0         1
297.0         1
301.0         6
302.0         1
304.0         1
310.0         1
325.0         3
333.0         1
335.0         1
345.0         1
350.0         2
351.0         1
400.0         3
401.0         4
402.0         1
404.0         3
405.0         1
406.0         5
410.0         1
412.0         1
424.0         1
440.0         1
442.0         1
444.0         2
446.0         1
448.0         2
449.0         3
450.0         1
451.0         4
455.0         2
460.0         1
471.0         1
499.0         6
500.0         1
501.0         5
505.0         2
510.0         1
511.0         1
520.0         1
530.0         1
551.0         1
555.0         1
599.0         1
600.0         2
601.0         2
602.0         1
604.0         7
605.0         1
606.0         5
608.0         1
610.0         2
620.0         1
625.0         4
630.0         1
640.0         3
642.0         1
644.0         1
645.0         1
646.0         4
655.0         1
660.0         3
666.0         1
672.0         1
694.0         1
701.0         2
704.0         1
705.0         3
710.0         1
715.0         1
720.0         1
725.0         2
735.0         3
750.0         2
775.0         1
794.0         1
799.0         1
800.0         1
806.0         2
825.0         2
888.0         3
899.0         2
900.0         3
909.0         1
919.0         1
939.0         1
940.0         1
949.0         2
959.0         2
975.0         1
979.0         2
988.0         1
990.0         3
993.0         3
994.0         5
995.0         3
997.0         5
998.0         2
999.0    138229
Name: CRN, dtype: int64

In [336]:
df_tmp1.head(2).transpose()

                                0             1
CRN                    2012030689    2012030689
UNIT_NUM                        2             1
HAZMAT_IND                    NaN             N
MODEL_YR                     2007          2007
TRAVEL_SPD                     35            35
UNIT_TYPE                       1             1
key_crn_unit         2012030689_2  2012030689_1
MC_DVR_EDC_IND                NaN           NaN
MC_DVR_HLMTON_IND             NaN           NaN
MC_PASSNGR_IND                NaN           NaN
PC_HDLGHT_IND                 NaN           NaN
PC_HLMT_IND                   NaN           NaN
PC_PASSNGR_IND                NaN           NaN
PC_REAR_RFLTR_IND             NaN           NaN
ind_trailer_vehicle           NaN             1

In [337]:
df_tmp1.columns

Index(['CRN', 'UNIT_NUM', 'HAZMAT_IND', 'MODEL_YR', 'TRAVEL_SPD', 'UNIT_TYPE',
       'key_crn_unit', 'MC_DVR_EDC_IND', 'MC_DVR_HLMTON_IND', 'MC_PASSNGR_IND',
       'PC_HDLGHT_IND', 'PC_HLMT_IND', 'PC_PASSNGR_IND', 'PC_REAR_RFLTR_IND',
       'ind_trailer_vehicle'],
      dtype='object')

In [338]:
df_tmp1['hazmat_commveh'] = df_tmp1['HAZMAT_IND'].apply(lambda x: 1 if x == 'Y' else 0)

df_tmp1['parked_legal'] = df_tmp1['UNIT_TYPE'].apply(lambda x: 1 if x == 2 else 0)
df_tmp1['parked_illegal'] = df_tmp1['UNIT_TYPE'].apply(lambda x: 1 if x == 3 else 0)
df_tmp1['non_motorized'] = df_tmp1['UNIT_TYPE'].apply(lambda x: 1 if x == 11 else 0)
df_tmp1['pedestrian'] = df_tmp1['UNIT_TYPE'].apply(lambda x: 1 if (x == 31)|(x == 32) else 0)

df_tmp1['mc_drv_safty_training_N'] = df_tmp1['MC_DVR_EDC_IND'].apply(lambda x: 1 if x == 'N' else 0)
df_tmp1['mc_drv_helmet_N'] = df_tmp1['MC_DVR_HLMTON_IND'].apply(lambda x: 1 if x == 'N' else 0)
df_tmp1['mc_passenger_Y'] = df_tmp1['MC_PASSNGR_IND'].apply(lambda x: 1 if x == 'Y' else 0)

df_tmp1['pc_head_light_N'] = df_tmp1['PC_HDLGHT_IND'].apply(lambda x: 1 if x == 'N' else 0)
df_tmp1['pc_helmet_N'] = df_tmp1['PC_HLMT_IND'].apply(lambda x: 1 if x == 'N' else 0)
df_tmp1['pc_passenger_Y'] = df_tmp1['PC_PASSNGR_IND'].apply(lambda x: 1 if x == 'Y' else 0)
df_tmp1['pc_rear_reflector_N'] = df_tmp1['PC_REAR_RFLTR_IND'].apply(lambda x: 1 if x == 'N' else 0)

df_tmp1['trailer_veh'] = df_tmp1['ind_trailer_vehicle'].apply(lambda x: 1 if x == 1 else 0)

In [339]:
pd.crosstab(df_tmp1['ind_trailer_vehicle'],df_tmp1['trailer_veh'])

trailer_veh             1
ind_trailer_vehicle
1.0                  2930

In [340]:
df_tmp1.head(2).transpose()

                                    0             1
CRN                        2012030689    2012030689
UNIT_NUM                            2             1
HAZMAT_IND                        NaN             N
MODEL_YR                         2007          2007
TRAVEL_SPD                         35            35
UNIT_TYPE                           1             1
key_crn_unit             2012030689_2  2012030689_1
MC_DVR_EDC_IND                    NaN           NaN
MC_DVR_HLMTON_IND                 NaN           NaN
MC_PASSNGR_IND                    NaN           NaN
PC_HDLGHT_IND                     NaN           NaN
PC_HLMT_IND                       NaN           NaN
PC_PASSNGR_IND                    NaN           NaN
PC_REAR_RFLTR_IND                 NaN           NaN
ind_trailer_vehicle               NaN             1
hazmat_commveh                      0             0
parked_legal                        0             0
parked_illegal                      0             0
non_motorized                       0             0
pedestrian                          0             0
mc_drv_safty_training_N             0             0
mc_drv_helmet_N                     0             0
mc_passenger_Y                      0             0
pc_head_light_N                     0             0
pc_helmet_N                         0             0
pc_passenger_Y                      0             0
pc_rear_reflector_N                 0             0
trailer_veh                         0             1

In [341]:
df_tmp1.columns

Index(['CRN', 'UNIT_NUM', 'HAZMAT_IND', 'MODEL_YR', 'TRAVEL_SPD', 'UNIT_TYPE',
       'key_crn_unit', 'MC_DVR_EDC_IND', 'MC_DVR_HLMTON_IND', 'MC_PASSNGR_IND',
       'PC_HDLGHT_IND', 'PC_HLMT_IND', 'PC_PASSNGR_IND', 'PC_REAR_RFLTR_IND',
       'ind_trailer_vehicle', 'hazmat_commveh', 'parked_legal',
       'parked_illegal', 'non_motorized', 'pedestrian',
       'mc_drv_safty_training_N', 'mc_drv_helmet_N', 'mc_passenger_Y',
       'pc_head_light_N', 'pc_helmet_N', 'pc_passenger_Y',
       'pc_rear_reflector_N', 'trailer_veh'],
      dtype='object')

In [342]:
df_tmp2 = df_tmp1.groupby('CRN').agg({'key_crn_unit':'count','MODEL_YR':'min','TRAVEL_SPD':'max','hazmat_commveh':'sum',
                                      'parked_legal':'sum','parked_illegal':'sum','non_motorized':'sum','pedestrian':'sum',
                                      'mc_drv_safty_training_N':'max','mc_drv_helmet_N':'max','mc_passenger_Y':'max',
                                      'pc_head_light_N':'max','pc_helmet_N':'max','pc_passenger_Y':'max',
                                      'pc_rear_reflector_N':'max','trailer_veh':'sum'}).reset_index()
df_tmp2.drop(columns=['key_crn_unit'],axis=1,inplace=True)
df_tmp2 = df_tmp2.rename(columns={'MODEL_YR': 'model_yr_min','TRAVEL_SPD':'speed_max',
                                  'hazmat_commveh':'cnt_hazmat_commveh','parked_legal':'parked_legal_cnt',
                                  'parked_illegal':'parked_illegal_cnt','non_motorized':'non_motorized_cnt','pedestrian':'pedestrian_cnt',
                                  'mc_drv_safty_training_N':'ind_mc_drv_safty_training_N',
                                  'mc_drv_helmet_N':'ind_mc_drv_helmet_N',
                                  'mc_passenger_Y':'ind_mc_passenger_Y',
                                  'pc_head_light_N':'ind_pc_head_light_N',
                                  'pc_helmet_N':'ind_pc_helmet_N',
                                  'pc_passenger_Y':'ind_pc_passenger_Y',
                                  'pc_rear_reflector_N':'ind_pc_rear_reflector_N',
                                  'trailer_veh':'trailer_veh_cnt'
                                 })
df_tmp2.head(2).transpose()

                                        0             1
CRN                          2.007002e+09  2.007002e+09
model_yr_min                 2.003000e+03  2.002000e+03
speed_max                    9.990000e+02  9.990000e+02
cnt_hazmat_commveh           0.000000e+00  0.000000e+00
parked_legal_cnt             0.000000e+00  0.000000e+00
parked_illegal_cnt           0.000000e+00  0.000000e+00
non_motorized_cnt            0.000000e+00  0.000000e+00
pedestrian_cnt               0.000000e+00  0.000000e+00
ind_mc_drv_safty_training_N  0.000000e+00  0.000000e+00
ind_mc_drv_helmet_N          0.000000e+00  0.000000e+00
ind_mc_passenger_Y           0.000000e+00  0.000000e+00
ind_pc_head_light_N          0.000000e+00  0.000000e+00
ind_pc_helmet_N              0.000000e+00  0.000000e+00
ind_pc_passenger_Y           0.000000e+00  0.000000e+00
ind_pc_rear_reflector_N      0.000000e+00  0.000000e+00
trailer_veh_cnt              0.000000e+00  0.000000e+00

In [344]:
df_tmp2['CRN'].nunique()

123116

In [345]:
df_tmp2['CRN'].count()

123116

In [346]:
df_tmp2.head(2)

,CRN,model_yr_min,speed_max,cnt_hazmat_commveh,parked_legal_cnt,parked_illegal_cnt,non_motorized_cnt,pedestrian_cnt,ind_mc_drv_safty_training_N,ind_mc_drv_helmet_N,ind_mc_passenger_Y,ind_pc_head_light_N,ind_pc_helmet_N,ind_pc_passenger_Y,ind_pc_rear_reflector_N,trailer_veh_cnt
0,2007001504,2003.0,999.0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2007001511,2002.0,999.0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [347]:
df_vehicle_07_17_crn_lvl = df_tmp2
df_vehicle_07_17_crn_lvl.head(2)

,CRN,model_yr_min,speed_max,cnt_hazmat_commveh,parked_legal_cnt,parked_illegal_cnt,non_motorized_cnt,pedestrian_cnt,ind_mc_drv_safty_training_N,ind_mc_drv_helmet_N,ind_mc_passenger_Y,ind_pc_head_light_N,ind_pc_helmet_N,ind_pc_passenger_Y,ind_pc_rear_reflector_N,trailer_veh_cnt
0,2007001504,2003.0,999.0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2007001511,2002.0,999.0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [221]:
df_vehicle_07_17_crn_lvl.groupby('speed_max')['CRN'].count()

speed_max
0.0        163
1.0         69
2.0        118
3.0         77
4.0         33
5.0       1278
6.0         41
7.0         35
8.0         33
9.0         10
10.0      1754
11.0         3
12.0        15
13.0         3
14.0         1
15.0      2186
16.0         3
17.0         3
18.0        15
19.0         1
20.0      2588
21.0         2
22.0         4
23.0         5
24.0         3
25.0      5780
26.0         8
27.0         5
28.0        17
29.0         9
30.0      2768
31.0         1
32.0         5
34.0         3
35.0      3332
36.0         2
37.0         2
38.0        12
39.0         5
40.0      2160
42.0         5
43.0         2
44.0         6
45.0      1865
46.0        20
47.0         5
48.0         5
49.0         4
50.0      2353
51.0         2
52.0         1
53.0         2
54.0         2
55.0      2304
56.0         9
57.0         6
58.0         8
59.0         2
60.0      1632
61.0         4
62.0         4
63.0         2
64.0         2
65.0      1235
66.0         5
67.0         2
68.0         4
70.0       664
71.0         1
72.0         2
75.0       232
76.0         3
77.0         1
78.0         3
80.0       258
83.0         1
85.0        48
90.0        63
91.0         1
95.0         8
98.0         3
99.0       760
100.0       45
101.0        1
105.0        2
110.0        6
111.0        7
115.0        4
120.0       14
125.0       10
130.0        8
135.0        2
140.0        1
145.0        2
150.0        2
151.0        2
152.0        1
157.0        1
199.0        2
200.0        1
201.0        2
202.0        1
205.0        1
206.0        1
210.0        1
215.0        1
220.0        1
225.0        1
232.0        1
250.0        2
251.0        7
252.0        1
301.0        4
310.0        1
325.0        2
335.0        1
345.0        1
350.0        2
351.0        1
400.0        2
401.0        2
402.0        1
404.0        1
406.0        2
412.0        1
424.0        1
440.0        1
442.0        1
448.0        2
449.0        1
450.0        1
451.0        1
455.0        2
471.0        1
499.0        1
501.0        5
505.0        2
510.0        1
511.0        1
551.0        1
555.0        1
599.0        1
601.0        1
602.0        1
604.0        3
605.0        1
606.0        3
608.0        1
610.0        2
620.0        1
625.0        3
630.0        1
640.0        2
644.0        1
645.0        1
646.0        2
655.0        1
660.0        3
701.0        2
704.0        1
705.0        2
710.0        1
715.0        1
725.0        2
735.0        2
750.0        1
775.0        1
825.0        2
888.0        1
900.0        1
940.0        1
959.0        1
988.0        1
990.0        2
994.0        1
995.0        1
997.0        1
998.0        1
999.0    88769
Name: CRN, dtype: int64

In [348]:
df_vehicle_07_17_crn_lvl.isnull().sum()

CRN                               0
model_yr_min                   4606
speed_max                        27
cnt_hazmat_commveh                0
parked_legal_cnt                  0
parked_illegal_cnt                0
non_motorized_cnt                 0
pedestrian_cnt                    0
ind_mc_drv_safty_training_N       0
ind_mc_drv_helmet_N               0
ind_mc_passenger_Y                0
ind_pc_head_light_N               0
ind_pc_helmet_N                   0
ind_pc_passenger_Y                0
ind_pc_rear_reflector_N           0
trailer_veh_cnt                   0
dtype: int64

In [247]:
df_vehicle_07_17_crn_lvl.to_csv('df_vehicle_07_17_crn_lvl.csv')

In [349]:
df_vehicle_07_17_crn_lvl.columns

Index(['CRN', 'model_yr_min', 'speed_max', 'cnt_hazmat_commveh',
       'parked_legal_cnt', 'parked_illegal_cnt', 'non_motorized_cnt',
       'pedestrian_cnt', 'ind_mc_drv_safty_training_N', 'ind_mc_drv_helmet_N',
       'ind_mc_passenger_Y', 'ind_pc_head_light_N', 'ind_pc_helmet_N',
       'ind_pc_passenger_Y', 'ind_pc_rear_reflector_N', 'trailer_veh_cnt'],
      dtype='object')

<a id='person'> </a>

# Step 6. Prepare person data

In [259]:
df_person_07_17.head(2).transpose()

                                          0                         1
AGE                                      26                        19
AIRBAG_PADS                               0                         0
CLOTHING_TYPE                           NaN                       NaN
COUNTY                                   67                        67
COUNTY_NAME                             NaN                       NaN
COUNTY_YEAR        PERSON_2007_Philadelphia  PERSON_2007_Philadelphia
CRASH_YEAR                             2007                      2007
CRN                              2008016368                2008016368
DVR_LIC_STATE                            PA                        PA
DVR_PED_CONDITION                         0                         0
EJECTION_IND                              0                         0
EJECT_PATH_CD                             0                         0
EXTRIC_IND                                0                         0
INJ_SEVERITY                              4                         0
MUNICIPALITY                          67301                     67301
PED_LOCATION                            NaN                       NaN
PED_SIGNAL                              NaN                       NaN
PERSON_NUM                                2                         1
PERSON_TYPE                               2                         1
RESTRAINT_HELMET                          3                         3
SEAT_POSITION                             3                         1
SEX                                       M                         M
TRANSPORTED                             NaN                       NaN
UNIT_NUM                                  2                         2

In [224]:
df_person_07_17.columns

Index(['AGE', 'AIRBAG_PADS', 'CLOTHING_TYPE', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_YEAR', 'CRN', 'DVR_LIC_STATE',
       'DVR_PED_CONDITION', 'EJECTION_IND', 'EJECT_PATH_CD', 'EXTRIC_IND',
       'INJ_SEVERITY', 'MUNICIPALITY', 'PED_LOCATION', 'PED_SIGNAL',
       'PERSON_NUM', 'PERSON_TYPE', 'RESTRAINT_HELMET', 'SEAT_POSITION', 'SEX',
       'TRANSPORTED', 'UNIT_NUM'],
      dtype='object')

In [255]:
df_person_07_17.groupby('PERSON_TYPE')['CRN'].count()

PERSON_TYPE
1.0    215451
2.0     92405
7.0     19755
8.0       822
9.0       795
Name: CRN, dtype: int64

In [254]:
df_person_07_17[df_person_07_17['PERSON_TYPE'] == 1].groupby('SEX')['CRN'].count()

SEX
          2
F     77512
M    124610
U     13320
Name: CRN, dtype: int64

In [248]:
df_person_07_17.columns

Index(['AGE', 'AIRBAG_PADS', 'CLOTHING_TYPE', 'COUNTY', 'COUNTY_NAME',
       'COUNTY_YEAR', 'CRASH_YEAR', 'CRN', 'DVR_LIC_STATE',
       'DVR_PED_CONDITION', 'EJECTION_IND', 'EJECT_PATH_CD', 'EXTRIC_IND',
       'INJ_SEVERITY', 'MUNICIPALITY', 'PED_LOCATION', 'PED_SIGNAL',
       'PERSON_NUM', 'PERSON_TYPE', 'RESTRAINT_HELMET', 'SEAT_POSITION', 'SEX',
       'TRANSPORTED', 'UNIT_NUM'],
      dtype='object')

In [305]:
df_tmp = df_person_07_17[['CRN','UNIT_NUM','PERSON_NUM','AGE','DVR_PED_CONDITION','PED_LOCATION','PED_SIGNAL','PERSON_TYPE','RESTRAINT_HELMET']]
df_tmp.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET
0,2008016368,2,2,26,0.0,NaN,NaN,2.0,3.0
1,2008016368,2,1,19,0.0,NaN,NaN,1.0,3.0

In [306]:
df_tmp_driver = df_tmp[df_tmp['PERSON_TYPE'] == 1]
df_tmp_passenger = df_tmp[df_tmp['PERSON_TYPE'] == 2]
df_tmp_pedestrian = df_tmp[df_tmp['PERSON_TYPE'] == 7]

In [285]:
df_tmp_passenger.groupby('DVR_PED_CONDITION')['CRN'].count()

DVR_PED_CONDITION
0.0    83179
1.0     1614
2.0      433
3.0      147
4.0      190
5.0       81
6.0       48
9.0     6151
Name: CRN, dtype: int64

In [261]:
df_tmp_driver.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET
1,2008016368,2,1,19,0.0,NaN,NaN,1.0,3.0
2,2008016368,1,1,80,0.0,NaN,NaN,1.0,3.0

In [262]:
df_tmp_driver.groupby('DVR_PED_CONDITION')['CRN'].count()

DVR_PED_CONDITION
0.0    175738
1.0      5789
2.0      1766
3.0       656
4.0       929
5.0       349
6.0       334
9.0     29590
Name: CRN, dtype: int64

In [273]:
df_tmp_driver['drv_drinking'] = df_tmp_driver['DVR_PED_CONDITION'].apply(lambda x: 1 if x == 1 else 0)
df_tmp_driver['drv_drug'] = df_tmp_driver['DVR_PED_CONDITION'].apply(lambda x: 1 if x == 2 else 0)
df_tmp_driver['drv_sick_medication'] = df_tmp_driver['DVR_PED_CONDITION'].apply(lambda x: 1 if (x == 3)|(x == 6) else 0)
df_tmp_driver['drv_fatigue_asleep'] = df_tmp_driver['DVR_PED_CONDITION'].apply(lambda x: 1 if (x == 4)|(x == 5) else 0)

df_tmp_driver['drv_no_restraint_helmet'] = df_tmp_driver['RESTRAINT_HELMET'].apply(lambda x: 1 if x == 0 else 0)

In [274]:
pd.crosstab(df_tmp_driver['RESTRAINT_HELMET'],df_tmp_driver['passenger_no_restraint_helmet'])

passenger_no_restraint_helmet      0      1
RESTRAINT_HELMET
0.0                                0  14817
1.0                             4902      0
2.0                             1246      0
3.0                            23696      0
4.0                             5364      0
5.0                               70      0
6.0                                9      0
10.0                              60      0
11.0                             289      0
12.0                               4      0
90.0                             412      0
99.0                           41532      0

In [275]:
df_tmp_driver.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET,drv_drinking,drv_drug,drv_sick_medication,drv_fatigue_asleep,drv_no_restraint_helmet
1,2008016368,2,1,19,0.0,NaN,NaN,1.0,3.0,0,0,0,0,0
2,2008016368,1,1,80,0.0,NaN,NaN,1.0,3.0,0,0,0,0,0

In [281]:
df_tmp_driver1 = df_tmp_driver.groupby('CRN').agg({'CRN':'count','AGE':['min','max'],'drv_drinking':'sum','drv_drug':'sum',
                                                   'drv_sick_medication':'sum','drv_fatigue_asleep':'sum',
                                                   'drv_no_restraint_helmet':'sum'
                                                  }).reset_index()
df_tmp_driver1.columns = ["_".join(x) for x in df_tmp_driver1.columns.ravel()]
df_tmp_driver1 = df_tmp_driver1.rename(columns={'CRN_': 'CRN','CRN_count':'cnt_driver',
                                                'AGE_min':'drv_age_min','AGE_max':'drv_age_max'})
df_tmp_driver1.head(2)

,CRN,cnt_driver,drv_age_min,drv_age_max,drv_drinking_sum,drv_drug_sum,drv_sick_medication_sum,drv_fatigue_asleep_sum,drv_no_restraint_helmet_sum
0,2007001504,3,24,70,0,0,0,0,1
1,2007001511,2,46,48,0,0,0,0,0

In [282]:
df_driver_07_17_crn_lvl = df_tmp_driver1
df_driver_07_17_crn_lvl.head(2)

,CRN,cnt_driver,drv_age_min,drv_age_max,drv_drinking_sum,drv_drug_sum,drv_sick_medication_sum,drv_fatigue_asleep_sum,drv_no_restraint_helmet_sum
0,2007001504,3,24,70,0,0,0,0,1
1,2007001511,2,46,48,0,0,0,0,0

In [318]:
df_driver_07_17_crn_lvl.to_csv('df_driver_07_17_crn_lvl.csv')

In [288]:
df_tmp_passenger.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET,passenger_no_restraint_helmet
0,2008016368,2,2,26,0.0,NaN,NaN,2.0,3.0,0
3,2008017018,1,3,4,0.0,NaN,NaN,2.0,4.0,0

In [287]:
df_tmp_passenger['passenger_no_restraint_helmet'] = df_tmp_passenger['RESTRAINT_HELMET'].apply(lambda x: 1 if x == 0 else 0)

In [289]:
df_tmp_passenger1 = df_tmp_passenger.groupby('CRN').agg({'CRN':'count','AGE':['min','max'],'passenger_no_restraint_helmet':'sum'
                                                  }).reset_index()
df_tmp_passenger1.columns = ["_".join(x) for x in df_tmp_passenger1.columns.ravel()]
df_tmp_passenger1 = df_tmp_passenger1.rename(columns={'CRN_': 'CRN','CRN_count':'cnt_passenger',
                                                'AGE_min':'passenger_age_min','AGE_max':'passenger_age_max'})
df_tmp_passenger1.head(2)

,CRN,cnt_passenger,passenger_age_min,passenger_age_max,passenger_no_restraint_helmet_sum
0,2007014726,6,1,47,0
1,2007017931,2,7,83,0

In [290]:
df_passenger_07_17_crn_lvl = df_tmp_passenger1
df_passenger_07_17_crn_lvl.head(2)

,CRN,cnt_passenger,passenger_age_min,passenger_age_max,passenger_no_restraint_helmet_sum
0,2007014726,6,1,47,0
1,2007017931,2,7,83,0

In [319]:
df_passenger_07_17_crn_lvl.to_csv('df_passenger_07_17_crn_lvl.csv')

In [291]:
df_tmp_pedestrian.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET
10,2008017060,2,1,26,0.0,99,2,7.0,0.0
13,2008017120,2,1,24,9.0,99,2,7.0,0.0

In [301]:
df_tmp_pedestrian.groupby('PED_SIGNAL')['CRN'].count()

PED_SIGNAL
1.0     1359
2.0    12230
3.0     4447
1        162
2        866
3        633
Name: CRN, dtype: int64

In [307]:
df_tmp_pedestrian['pedestrian_drinking'] = df_tmp_pedestrian['DVR_PED_CONDITION'].apply(lambda x: 1 if x == 1 else 0)
df_tmp_pedestrian['pedestrian_drug'] = df_tmp_pedestrian['DVR_PED_CONDITION'].apply(lambda x: 1 if x == 2 else 0)
df_tmp_pedestrian['pedestrian_sick_medication'] = df_tmp_pedestrian['DVR_PED_CONDITION'].apply(lambda x: 1 if (x == 3)|(x == 6) else 0)
df_tmp_pedestrian['pedestrian_fatigue_asleep'] = df_tmp_pedestrian['DVR_PED_CONDITION'].apply(lambda x: 1 if (x == 4)|(x == 5) else 0)

df_tmp_pedestrian['pedestrian_loc_int_crosswalk'] = df_tmp_pedestrian['PED_LOCATION'].apply(lambda x: 1 if (x == 1)|(x == '01') else 0)
df_tmp_pedestrian['pedestrian_loc_int_no_crosswalk'] = df_tmp_pedestrian['PED_LOCATION'].apply(lambda x: 1 if (x == 2)|(x == '02') else 0)
df_tmp_pedestrian['pedestrian_loc_in_roadway'] = df_tmp_pedestrian['PED_LOCATION'].apply(lambda x: 1 if (x == 5)|(x == '05') else 0)
df_tmp_pedestrian['pedestrian_loc_shoulder_sidewalk'] = df_tmp_pedestrian['PED_LOCATION'].apply(lambda x: 1 if (x == 9)|(x == 10)|(x == '09')|(x == '10') else 0)

df_tmp_pedestrian['pedestrian_signal_Y'] = df_tmp_pedestrian['PED_SIGNAL'].apply(lambda x: 1 if (x == 1)|(x == '1') else 0)
df_tmp_pedestrian['pedestrian_signal_N'] = df_tmp_pedestrian['PED_SIGNAL'].apply(lambda x: 1 if (x == 2)|(x == '2') else 0)
df_tmp_pedestrian['pedestrian_signal_not_int'] = df_tmp_pedestrian['PED_SIGNAL'].apply(lambda x: 1 if (x == 3)|(x == '3') else 0)

In [310]:
pd.crosstab(df_tmp_pedestrian['PED_SIGNAL'],df_tmp_pedestrian['pedestrian_signal_not_int'])

pedestrian_signal_not_int      0     1
PED_SIGNAL
1.0                         1359     0
2.0                        12230     0
3.0                            0  4447
1                            162     0
2                            866     0
3                              0   633

In [311]:
df_tmp_pedestrian.head(2)

,CRN,UNIT_NUM,PERSON_NUM,AGE,DVR_PED_CONDITION,PED_LOCATION,PED_SIGNAL,PERSON_TYPE,RESTRAINT_HELMET,pedestrian_drinking,pedestrian_drug,pedestrian_sick_medication,pedestrian_fatigue_asleep,pedestrian_loc_int_crosswalk,pedestrian_loc_int_no_crosswalk,pedestrian_loc_in_roadway,pedestrian_loc_shoulder_sidewalk,pedestrian_signal_Y,pedestrian_signal_N,pedestrian_signal_not_int
10,2008017060,2,1,26,0.0,99,2,7.0,0.0,0,0,0,0,0,0,0,0,0,1,0
13,2008017120,2,1,24,9.0,99,2,7.0,0.0,0,0,0,0,0,0,0,0,0,1,0

In [316]:
df_tmp_pedestrian1 = df_tmp_pedestrian.groupby('CRN').agg({'CRN':'count','AGE':['min','max'],'pedestrian_drinking':'sum',
                                                           'pedestrian_drug':'sum','pedestrian_sick_medication':'sum',
                                                           'pedestrian_fatigue_asleep':'sum',
                                                           'pedestrian_loc_int_crosswalk':'sum',
                                                           'pedestrian_loc_int_no_crosswalk':'sum',
                                                           'pedestrian_loc_in_roadway':'sum',
                                                           'pedestrian_loc_shoulder_sidewalk':'sum',
                                                           'pedestrian_signal_Y':'sum',
                                                           'pedestrian_signal_N':'sum',
                                                           'pedestrian_signal_not_int':'sum'
                                                          }).reset_index()
df_tmp_pedestrian1.columns = ["_".join(x) for x in df_tmp_pedestrian1.columns.ravel()]
df_tmp_pedestrian1 = df_tmp_pedestrian1.rename(columns={'CRN_': 'CRN','CRN_count':'cnt_pedestrian','AGE_min':'pedestrian_age_min','AGE_max':'pedestrian_age_max'})
df_tmp_pedestrian1.head(2)

,CRN,cnt_pedestrian,pedestrian_age_min,pedestrian_age_max,pedestrian_drinking_sum,pedestrian_drug_sum,pedestrian_sick_medication_sum,pedestrian_fatigue_asleep_sum,pedestrian_loc_int_crosswalk_sum,pedestrian_loc_int_no_crosswalk_sum,pedestrian_loc_in_roadway_sum,pedestrian_loc_shoulder_sidewalk_sum,pedestrian_signal_Y_sum,pedestrian_signal_N_sum,pedestrian_signal_not_int_sum
0,2007017932,2,44,45,2,0,0,0,2,0,0,0,2,0,0
1,2007022099,1,15,15,0,0,0,0,0,0,0,0,0,1,0

In [317]:
df_pedestrian_07_17_crn_lvl = df_tmp_pedestrian1
df_pedestrian_07_17_crn_lvl.head(2)

,CRN,cnt_pedestrian,pedestrian_age_min,pedestrian_age_max,pedestrian_drinking_sum,pedestrian_drug_sum,pedestrian_sick_medication_sum,pedestrian_fatigue_asleep_sum,pedestrian_loc_int_crosswalk_sum,pedestrian_loc_int_no_crosswalk_sum,pedestrian_loc_in_roadway_sum,pedestrian_loc_shoulder_sidewalk_sum,pedestrian_signal_Y_sum,pedestrian_signal_N_sum,pedestrian_signal_not_int_sum
0,2007017932,2,44,45,2,0,0,0,2,0,0,0,2,0,0
1,2007022099,1,15,15,0,0,0,0,0,0,0,0,0,1,0

In [321]:
df_pedestrian_07_17_crn_lvl.to_csv('df_pedestrian_07_17_crn_lvl.csv')

<a id='master'> </a>

# Step 7. Prepare final master data

In [ ]:
#df_crash_flg_07_17
#df_roadway_07_17_crn_lvl
#df_vehicle_07_17_crn_lvl
#df_driver_07_17_crn_lvl
#df_passenger_07_17_crn_lvl
#df_pedestrian_07_17_crn_lvl

In [324]:
df_roadway_07_17_crn_lvl.columns

Index(['CRN', 'cnt_road_01_interstate', 'cnt_road_02_state',
       'cnt_road_03_local', 'cnt_road_04_other', 'cnt_road_segments',
       'LANE_COUNT_min', 'LANE_COUNT_max', 'SPEED_LIMIT_nunique',
       'SPEED_LIMIT_min', 'SPEED_LIMIT_max'],
      dtype='object')

In [350]:
df_vehicle_07_17_crn_lvl.head(2).transpose()

                                        0             1
CRN                          2.007002e+09  2.007002e+09
model_yr_min                 2.003000e+03  2.002000e+03
speed_max                    9.990000e+02  9.990000e+02
cnt_hazmat_commveh           0.000000e+00  0.000000e+00
parked_legal_cnt             0.000000e+00  0.000000e+00
parked_illegal_cnt           0.000000e+00  0.000000e+00
non_motorized_cnt            0.000000e+00  0.000000e+00
pedestrian_cnt               0.000000e+00  0.000000e+00
ind_mc_drv_safty_training_N  0.000000e+00  0.000000e+00
ind_mc_drv_helmet_N          0.000000e+00  0.000000e+00
ind_mc_passenger_Y           0.000000e+00  0.000000e+00
ind_pc_head_light_N          0.000000e+00  0.000000e+00
ind_pc_helmet_N              0.000000e+00  0.000000e+00
ind_pc_passenger_Y           0.000000e+00  0.000000e+00
ind_pc_rear_reflector_N      0.000000e+00  0.000000e+00
trailer_veh_cnt              0.000000e+00  0.000000e+00

In [355]:
df_tmp = pd.merge(df_crash_flg_07_17,df_roadway_07_17_crn_lvl,on='CRN',how='left')
df_tmp1 = pd.merge(df_tmp,df_vehicle_07_17_crn_lvl,on='CRN',how='left')
df_tmp2 = pd.merge(df_tmp1,df_driver_07_17_crn_lvl,on='CRN',how='left')
df_tmp3 = pd.merge(df_tmp2,df_passenger_07_17_crn_lvl,on='CRN',how='left')
df_master_07_17_crn_lvl = pd.merge(df_tmp3,df_pedestrian_07_17_crn_lvl,on='CRN',how='left')

In [356]:
df_master_07_17_crn_lvl.head(2).transpose()

                                                 0                     1
ARRIVAL_TM                                    1815                   300
AUTOMOBILE_COUNT                                 3                     3
BELTED_DEATH_COUNT                               0                     0
BELTED_MAJ_INJ_COUNT                             0                     0
BICYCLE_COUNT                                    0                     0
BICYCLE_DEATH_COUNT                              0                     0
BICYCLE_MAJ_INJ_COUNT                            0                     0
BUS_COUNT                                        0                     0
COLLISION_TYPE                                   2                     5
COMM_VEH_COUNT                                   0                     0
CONS_ZONE_SPD_LIM                              NaN                   NaN
CRASH_MONTH                                      2                     2
CRN                                     2007045703            2007047000
DAY_OF_WEEK                                      2                     7
DEC_LAT                                    40.0509               39.9416
DEC_LONG                                  -75.1807              -75.1493
DISPATCH_TM                                   1815                   256
DISTRICT                                         6                     6
DRIVER_COUNT_16YR                                0                     0
DRIVER_COUNT_17YR                                1                     0
DRIVER_COUNT_18YR                                0                     0
DRIVER_COUNT_19YR                                0                     0
DRIVER_COUNT_20YR                                0                     1
DRIVER_COUNT_50_64YR                             0                     0
DRIVER_COUNT_65_74YR                             0                     0
DRIVER_COUNT_75PLUS                              0                     0
EST_HRS_CLOSED                                 NaN                   NaN
FATAL_COUNT                                      0                     0
HEAVY_TRUCK_COUNT                                0                     0
HOUR_OF_DAY                                     99                     2
ILLUMINATION                                     3                     6
INJURY_COUNT                                     2                     0
INTERSECT_TYPE                                   0                     0
LANE_CLOSED                                      0                     0
LATITUDE                              40 03:03.000          39 56:29.734
LN_CLOSE_DIR                                   NaN                   NaN
LOCATION_TYPE                                    0                     0
LONGITUDE                             75 10:50.397          75 08:57.440
MAJ_INJ_COUNT                                    0                     0
MAX_SEVERITY_LEVEL                               8                     0
MCYCLE_DEATH_COUNT                               0                     0
MCYCLE_MAJ_INJ_COUNT                             0                     0
MIN_INJ_COUNT                                    0                     0
MOD_INJ_COUNT                                    0                     0
MOTORCYCLE_COUNT                                 0                     0
NTFY_HIWY_MAINT                                  N                     N
PED_COUNT                                        0                     0
PED_DEATH_COUNT                                  0                     0
PED_MAJ_INJ_COUNT                                0                     0
PERSON_COUNT                                     2                     4
POLICE_AGCY                                  67301                 67301
RDWY_SURF_TYPE_CD                              NaN                   NaN
RELATION_TO_ROAD                                 6                     6
ROAD_CONDITION                                   0                     1
SCH_BUS_IND                                      N                     N
SCH_ZONE_IND                                     N                     N
SMALL_TRUCK_COUNT                                0                     0
SPEC_JURIS_CD                                  NaN                   NaN
SUV_COUNT                                        0                     3
TCD_FUNC_CD                                      0                     3
TCD_TYPE                                         0                     2
TFC_DETOUR_IND                                 NaN                   NaN
TIME_OF_DAY                                   9999                   250
TOTAL_UNITS                                      3                     7
TOT_INJ_COUNT                                    2                     0
UNBELTED_OCC_COUNT                               0                     2
UNB_DEATH_COUNT                                  0                     0
UNB_MAJ_INJ_COUNT                                0                     0
UNK_INJ_DEG_COUNT                                2                     0
UNK_INJ_PER_COUNT                                0                     0
URBAN_RURAL                                      3                     3
VAN_COUNT                                        0                     0
VEHICLE_COUNT                                    3                     7
WEATHER                                          1                     4
WORKERS_PRES                                   NaN                   NaN
WORK_ZONE_IND                                    N                     N
WORK_ZONE_LOC                                  NaN                   NaN
WORK_ZONE_TYPE                                 NaN                   NaN
WZ_CLOSE_DETOUR                                NaN                   NaN
WZ_FLAGGER                                     NaN                   NaN
WZ_LAW_OFFCR_IND                               NaN                   NaN
WZ_LN_CLOSURE                                  NaN                   NaN
WZ_MOVING                                      NaN                   NaN
WZ_OTHER                                       NaN                   NaN
WZ_SHLDER_MDN                                  NaN                   NaN
collision_type_name                        Head-on  Sideswipe(same dir.)
AGGRESSIVE_DRIVING                               0                     0
ALCOHOL_RELATED                                  0                     0
BICYCLE                                          0                     0
CELL_PHONE                                       0                     0
COMM_VEHICLE                                     0                     0
CRASH_YEAR                                    2007                  2007
CROSS_MEDIAN                                     0                     0
CURVED_ROAD                                      0                     0
CURVE_DVR_ERROR                                  0                     0
DEER_RELATED                                     0                     0
DISTRACTED                                       1                     0
DRINKING_DRIVER                                  0                     0
DRIVER_16YR                                      0                     0
DRIVER_17YR                                      1                     0
DRIVER_18YR                                      0                     0
DRIVER_19YR                                      0                     0
DRIVER_20YR                                      0                     1
DRIVER_50_64YR                                   0                     0
DRIVER_65_74YR                                   0                     0
DRIVER_75PLUS                                    0                     0
DRUGGED_DRIVER                                   0                     0
DRUG_RELATED                                     0                     0
FATAL                                            0                     0
FATAL_OR_MAJ_INJ                                 0                     0
FATIGUE_ASLEEP                                   0                     0
FIRE_IN_VEHICLE                                  0                     0
HAZARDOUS_TRUCK                                  0                     0
HIT_BARRIER                                      0                     0
HIT_BRIDGE                                       0                     0
HIT_DEER                                         0                     0
HIT_EMBANKMENT                                   0                     0
HIT_FIXED_OBJECT                                 0                     0
HIT_GDRAIL                                       0                     0
HIT_GDRAIL_END                                   0                     0
HIT_PARKED_VEHICLE                               1                     1
HIT_POLE                                         0                     0
HIT_TREE_SHRUB                                   0                     0
HO_OPPDIR_SDSWP                                  1                     0
HVY_TRUCK_RELATED                                0                     0
ICY_ROAD                                         0                     0
ILLEGAL_DRUG_RELATED                             0                     0
ILLUMINATION_DARK                                1                     1
IMPAIRED_DRIVER                                  0                     0
INJURY                                           1                     0
INJURY_OR_FATAL                                  1                     0
INTERSECTION                                     0                     0
INTERSTATE                                       0                     0
LIMIT_65MPH                                      0                     0
LOCAL_ROAD                                       0                     1
LOCAL_ROAD_ONLY                                  0                     1
MAJOR_INJURY                                     0                     0
MC_DRINKING_DRIVER                               0                     0
MINOR_INJURY                                     0                     0
MODERATE_INJURY                                  0                     0
MOTORCYCLE                                       0                     0
NHTSA_AGG_DRIVING                                0                     0
NON_INTERSECTION                                 1                     1
NO_CLEARANCE                                     0                     0
OVERTURNED                                       0                     0
PEDESTRIAN                                       0                     0
PHANTOM_VEHICLE                                  0                     0
PROPERTY_DAMAGE_ONLY                             0                     1
PSP_REPORTED                                     0                     0
REAR_END                                         0                     0
RUNNING_RED_LT                                   0                     0
RUNNING_STOP_SIGN                                0                     0
SCHOOL_BUS                                       0                     0
SCHOOL_BUS_UNIT                                  0                     0
SCHOOL_ZONE                                      0                     0
SHLDR_RELATED                                    0                     0
SIGNALIZED_INT                                   0                     0
SNOW_SLUSH_ROAD                                  0                     0
SPEEDING                                         0                     0
SPEEDING_RELATED                                 0                     0
STATE_ROAD                                       1                     0
STOP_CONTROLLED_INT                              0                     0
SUDDEN_DEER                                      0                     0
SV_RUN_OFF_RD                                    0                     0
TAILGATING                                       0                     0
TRAIN                                            0                     0
TRAIN_TROLLEY                                    0                     0
TROLLEY                                          0                     0
TURNPIKE                                         0                     0
UNBELTED                                         0                     1
UNDERAGE_DRNK_DRV                                0                     0
UNLICENSED                                       0                     0
UNSIGNALIZED_INT                                 0                     0
VEHICLE_FAILURE                                  0                     0
VEHICLE_TOWED                                    1                     1
WET_ROAD                                         0                     1
WORK_ZONE                                        0                     0
cnt_road_01_interstate                           0                     0
cnt_road_02_state                                1                     0
cnt_road_03_local                                0                     1
cnt_road_04_other                                0                     0
cnt_road_segments                                1                     1
LANE_COUNT_min                                   2                     1
LANE_COUNT_max                                   2                     1
SPEED_LIMIT_nunique                              1                     1
SPEED_LIMIT_min                                 25                    25
SPEED_LIMIT_max                                 25                    25
model_yr_min                                  1997                  1998
speed_max                                       35                   999
cnt_hazmat_commveh                               0                     0
parked_legal_cnt                                 2                     3
parked_illegal_cnt                               0                     0
non_motorized_cnt                                0                     0
pedestrian_cnt                                   0                     0
ind_mc_drv_safty_training_N                      0                     0
ind_mc_drv_helmet_N                              0                     0
ind_mc_passenger_Y                               0                     0
ind_pc_head_light_N                              0                     0
ind_pc_helmet_N                                  0                     0
ind_pc_passenger_Y                               0                     0
ind_pc_rear_reflector_N                          0                     0
trailer_veh_cnt                                  0                     0
cnt_driver                                       1                     4
drv_age_min                                     17                    20
drv_age_max                                     17                    40
drv_drinking_sum                                 0                     0
drv_drug_sum                                     0                     0
drv_sick_medication_sum                          0                     0
drv_fatigue_asleep_sum                           0                     0
drv_no_restraint_helmet_sum                      0                     2
cnt_passenger                                    1                   NaN
passenger_age_min                               11                   NaN
passenger_age_max                               11                   NaN
passenger_no_restraint_helmet_sum                0                   NaN
cnt_pedestrian                                 NaN                   NaN
pedestrian_age_min                             NaN                   NaN
pedestrian_age_max                             NaN                   NaN
pedestrian_drinking_sum                        NaN                   NaN
pedestrian_drug_sum                            NaN                   NaN
pedestrian_sick_medication_sum                 NaN                   NaN
pedestrian_fatigue_asleep_sum                  NaN                   NaN
pedestrian_loc_int_crosswalk_sum               NaN                   NaN
pedestrian_loc_int_no_crosswalk_sum            NaN                   NaN
pedestrian_loc_in_roadway_sum                  NaN                   NaN
pedestrian_loc_shoulder_sidewalk_sum           NaN                   NaN
pedestrian_signal_Y_sum                        NaN                   NaN
pedestrian_signal_N_sum                        NaN                   NaN
pedestrian_signal_not_int_sum                  NaN                   NaN

In [357]:
df_master_07_17_crn_lvl.to_csv('df_master_07_17_crn_lvl.csv')

In [358]:
df_master_07_17_crn_lvl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123116 entries, 0 to 123115
Columns: 228 entries, ARRIVAL_TM to pedestrian_signal_not_int_sum
dtypes: float64(138), int64(64), object(26)
memory usage: 215.1+ MB

In [359]:
df_master_07_17_crn_lvl.head(2).transpose().to_csv('zz01_sample.csv')

In [360]:
df_master_07_17_crn_lvl.isnull().sum()

ARRIVAL_TM                                 978
AUTOMOBILE_COUNT                             0
BELTED_DEATH_COUNT                           0
BELTED_MAJ_INJ_COUNT                         0
BICYCLE_COUNT                                0
BICYCLE_DEATH_COUNT                          0
BICYCLE_MAJ_INJ_COUNT                        0
BUS_COUNT                                    0
COLLISION_TYPE                               0
COMM_VEH_COUNT                               0
CONS_ZONE_SPD_LIM                       110648
CRASH_MONTH                                  0
CRN                                          0
DAY_OF_WEEK                                  0
DEC_LAT                                   1294
DEC_LONG                                  1294
DISPATCH_TM                               1074
DISTRICT                                     0
DRIVER_COUNT_16YR                            0
DRIVER_COUNT_17YR                            0
DRIVER_COUNT_18YR                            0
DRIVER_COUNT_19YR                            0
DRIVER_COUNT_20YR                            0
DRIVER_COUNT_50_64YR                         0
DRIVER_COUNT_65_74YR                         0
DRIVER_COUNT_75PLUS                          0
EST_HRS_CLOSED                           79648
FATAL_COUNT                                  0
HEAVY_TRUCK_COUNT                            0
HOUR_OF_DAY                                  9
ILLUMINATION                                 9
INJURY_COUNT                                 0
INTERSECT_TYPE                               0
LANE_CLOSED                                  0
LATITUDE                                  1247
LN_CLOSE_DIR                             79650
LOCATION_TYPE                                0
LONGITUDE                                 1247
MAJ_INJ_COUNT                                0
MAX_SEVERITY_LEVEL                           0
MCYCLE_DEATH_COUNT                           0
MCYCLE_MAJ_INJ_COUNT                         0
MIN_INJ_COUNT                                0
MOD_INJ_COUNT                                0
MOTORCYCLE_COUNT                             0
NTFY_HIWY_MAINT                          32301
PED_COUNT                                    0
PED_DEATH_COUNT                              0
PED_MAJ_INJ_COUNT                            0
PERSON_COUNT                                 0
POLICE_AGCY                                 80
RDWY_SURF_TYPE_CD                       111090
RELATION_TO_ROAD                             3
ROAD_CONDITION                               5
SCH_BUS_IND                               7597
SCH_ZONE_IND                             21488
SMALL_TRUCK_COUNT                            0
SPEC_JURIS_CD                           111090
SUV_COUNT                                    0
TCD_FUNC_CD                                  6
TCD_TYPE                                     0
TFC_DETOUR_IND                           79647
TIME_OF_DAY                                  9
TOTAL_UNITS                                  0
TOT_INJ_COUNT                                0
UNBELTED_OCC_COUNT                           0
UNB_DEATH_COUNT                              0
UNB_MAJ_INJ_COUNT                            0
UNK_INJ_DEG_COUNT                            0
UNK_INJ_PER_COUNT                            0
URBAN_RURAL                                  0
VAN_COUNT                                    0
VEHICLE_COUNT                                0
WEATHER                                     18
WORKERS_PRES                            110648
WORK_ZONE_IND                                0
WORK_ZONE_LOC                           110648
WORK_ZONE_TYPE                          110648
WZ_CLOSE_DETOUR                         110869
WZ_FLAGGER                              110877
WZ_LAW_OFFCR_IND                        110648
WZ_LN_CLOSURE                           110783
WZ_MOVING                               110866
WZ_OTHER                                110861
WZ_SHLDER_MDN                           110850
collision_type_name                          0
AGGRESSIVE_DRIVING                           2
ALCOHOL_RELATED                              2
BICYCLE                                      2
CELL_PHONE                                   2
COMM_VEHICLE                                 2
CRASH_YEAR                                   2
CROSS_MEDIAN                                 2
CURVED_ROAD                                  2
CURVE_DVR_ERROR                              2
DEER_RELATED                                 2
DISTRACTED                                   2
DRINKING_DRIVER                              2
DRIVER_16YR                                  2
DRIVER_17YR                                  2
DRIVER_18YR                                  2
DRIVER_19YR                                  2
DRIVER_20YR                                  2
DRIVER_50_64YR                               2
DRIVER_65_74YR                               2
DRIVER_75PLUS                                2
DRUGGED_DRIVER                               2
DRUG_RELATED                                 2
FATAL                                        2
FATAL_OR_MAJ_INJ                             2
FATIGUE_ASLEEP                               2
FIRE_IN_VEHICLE                              2
HAZARDOUS_TRUCK                              2
HIT_BARRIER                                  2
HIT_BRIDGE                                   2
HIT_DEER                                     2
HIT_EMBANKMENT                               2
HIT_FIXED_OBJECT                             2
HIT_GDRAIL                                   2
HIT_GDRAIL_END                               2
HIT_PARKED_VEHICLE                           2
HIT_POLE                                     2
HIT_TREE_SHRUB                               2
HO_OPPDIR_SDSWP                              2
HVY_TRUCK_RELATED                            2
ICY_ROAD                                     2
ILLEGAL_DRUG_RELATED                         2
ILLUMINATION_DARK                            2
IMPAIRED_DRIVER                              2
INJURY                                       2
INJURY_OR_FATAL                              2
INTERSECTION                                 2
INTERSTATE                                   2
LIMIT_65MPH                                  2
LOCAL_ROAD                                   2
LOCAL_ROAD_ONLY                              2
MAJOR_INJURY                                 2
MC_DRINKING_DRIVER                           2
MINOR_INJURY                                 2
MODERATE_INJURY                              2
MOTORCYCLE                                   2
NHTSA_AGG_DRIVING                            2
NON_INTERSECTION                             2
NO_CLEARANCE                                 2
OVERTURNED                                   2
PEDESTRIAN                                   2
PHANTOM_VEHICLE                              2
PROPERTY_DAMAGE_ONLY                         2
PSP_REPORTED                                 2
REAR_END                                     2
RUNNING_RED_LT                               2
RUNNING_STOP_SIGN                            2
SCHOOL_BUS                                   2
SCHOOL_BUS_UNIT                              2
SCHOOL_ZONE                                  2
SHLDR_RELATED                                2
SIGNALIZED_INT                               2
SNOW_SLUSH_ROAD                              2
SPEEDING                                     2
SPEEDING_RELATED                             2
STATE_ROAD                                   2
STOP_CONTROLLED_INT                          2
SUDDEN_DEER                                  2
SV_RUN_OFF_RD                                2
TAILGATING                                   2
TRAIN                                        2
TRAIN_TROLLEY                                2
TROLLEY                                      2
TURNPIKE                                     2
UNBELTED                                     2
UNDERAGE_DRNK_DRV                            2
UNLICENSED                                   2
UNSIGNALIZED_INT                             2
VEHICLE_FAILURE                              2
VEHICLE_TOWED                                2
WET_ROAD                                     2
WORK_ZONE                                    2
cnt_road_01_interstate                      64
cnt_road_02_state                           64
cnt_road_03_local                           64
cnt_road_04_other                           64
cnt_road_segments                           64
LANE_COUNT_min                              66
LANE_COUNT_max                              66
SPEED_LIMIT_nunique                         64
SPEED_LIMIT_min                          14579
SPEED_LIMIT_max                          14579
model_yr_min                              4606
speed_max                                   27
cnt_hazmat_commveh                           0
parked_legal_cnt                             0
parked_illegal_cnt                           0
non_motorized_cnt                            0
pedestrian_cnt                               0
ind_mc_drv_safty_training_N                  0
ind_mc_drv_helmet_N                          0
ind_mc_passenger_Y                           0
ind_pc_head_light_N                          0
ind_pc_helmet_N                              0
ind_pc_passenger_Y                           0
ind_pc_rear_reflector_N                      0
trailer_veh_cnt                              0
cnt_driver                                 722
drv_age_min                                722
drv_age_max                                722
drv_drinking_sum                           722
drv_drug_sum                               722
drv_sick_medication_sum                    722
drv_fatigue_asleep_sum                     722
drv_no_restraint_helmet_sum                722
cnt_passenger                            76181
passenger_age_min                        76181
passenger_age_max                        76181
passenger_no_restraint_helmet_sum        76181
cnt_pedestrian                          104176
pedestrian_age_min                      104176
pedestrian_age_max                      104176
pedestrian_drinking_sum                 104176
pedestrian_drug_sum                     104176
pedestrian_sick_medication_sum          104176
pedestrian_fatigue_asleep_sum           104176
pedestrian_loc_int_crosswalk_sum        104176
pedestrian_loc_int_no_crosswalk_sum     104176
pedestrian_loc_in_roadway_sum           104176
pedestrian_loc_shoulder_sidewalk_sum    104176
pedestrian_signal_Y_sum                 104176
pedestrian_signal_N_sum                 104176
pedestrian_signal_not_int_sum           104176
dtype: int64

In [361]:
df_master_07_17_crn_lvl.dtypes

ARRIVAL_TM                               object
AUTOMOBILE_COUNT                          int64
BELTED_DEATH_COUNT                        int64
BELTED_MAJ_INJ_COUNT                      int64
BICYCLE_COUNT                             int64
BICYCLE_DEATH_COUNT                       int64
BICYCLE_MAJ_INJ_COUNT                     int64
BUS_COUNT                                 int64
COLLISION_TYPE                            int64
COMM_VEH_COUNT                            int64
CONS_ZONE_SPD_LIM                        object
CRASH_MONTH                               int64
CRN                                       int64
DAY_OF_WEEK                               int64
DEC_LAT                                 float64
DEC_LONG                                float64
DISPATCH_TM                              object
DISTRICT                                  int64
DRIVER_COUNT_16YR                         int64
DRIVER_COUNT_17YR                         int64
DRIVER_COUNT_18YR                         int64
DRIVER_COUNT_19YR                         int64
DRIVER_COUNT_20YR                         int64
DRIVER_COUNT_50_64YR                      int64
DRIVER_COUNT_65_74YR                      int64
DRIVER_COUNT_75PLUS                       int64
EST_HRS_CLOSED                           object
FATAL_COUNT                               int64
HEAVY_TRUCK_COUNT                         int64
HOUR_OF_DAY                             float64
ILLUMINATION                            float64
INJURY_COUNT                              int64
INTERSECT_TYPE                            int64
LANE_CLOSED                               int64
LATITUDE                                 object
LN_CLOSE_DIR                             object
LOCATION_TYPE                             int64
LONGITUDE                                object
MAJ_INJ_COUNT                             int64
MAX_SEVERITY_LEVEL                        int64
MCYCLE_DEATH_COUNT                        int64
MCYCLE_MAJ_INJ_COUNT                      int64
MIN_INJ_COUNT                             int64
MOD_INJ_COUNT                             int64
MOTORCYCLE_COUNT                          int64
NTFY_HIWY_MAINT                          object
PED_COUNT                                 int64
PED_DEATH_COUNT                           int64
PED_MAJ_INJ_COUNT                         int64
PERSON_COUNT                              int64
POLICE_AGCY                              object
RDWY_SURF_TYPE_CD                        object
RELATION_TO_ROAD                        float64
ROAD_CONDITION                          float64
SCH_BUS_IND                              object
SCH_ZONE_IND                             object
SMALL_TRUCK_COUNT                         int64
SPEC_JURIS_CD                            object
SUV_COUNT                                 int64
TCD_FUNC_CD                             float64
TCD_TYPE                                  int64
TFC_DETOUR_IND                           object
TIME_OF_DAY                             float64
TOTAL_UNITS                               int64
TOT_INJ_COUNT                             int64
UNBELTED_OCC_COUNT                        int64
UNB_DEATH_COUNT                           int64
UNB_MAJ_INJ_COUNT                         int64
UNK_INJ_DEG_COUNT                         int64
UNK_INJ_PER_COUNT                         int64
URBAN_RURAL                               int64
VAN_COUNT                                 int64
VEHICLE_COUNT                             int64
WEATHER                                 float64
WORKERS_PRES                             object
WORK_ZONE_IND                            object
WORK_ZONE_LOC                            object
WORK_ZONE_TYPE                           object
WZ_CLOSE_DETOUR                          object
WZ_FLAGGER                               object
WZ_LAW_OFFCR_IND                         object
WZ_LN_CLOSURE                            object
WZ_MOVING                                object
WZ_OTHER                                 object
WZ_SHLDER_MDN                            object
collision_type_name                      object
AGGRESSIVE_DRIVING                      float64
ALCOHOL_RELATED                         float64
BICYCLE                                 float64
CELL_PHONE                              float64
COMM_VEHICLE                            float64
CRASH_YEAR                              float64
CROSS_MEDIAN                            float64
CURVED_ROAD                             float64
CURVE_DVR_ERROR                         float64
DEER_RELATED                            float64
DISTRACTED                              float64
DRINKING_DRIVER                         float64
DRIVER_16YR                             float64
DRIVER_17YR                             float64
DRIVER_18YR                             float64
DRIVER_19YR                             float64
DRIVER_20YR                             float64
DRIVER_50_64YR                          float64
DRIVER_65_74YR                          float64
DRIVER_75PLUS                           float64
DRUGGED_DRIVER                          float64
DRUG_RELATED                            float64
FATAL                                   float64
FATAL_OR_MAJ_INJ                        float64
FATIGUE_ASLEEP                          float64
FIRE_IN_VEHICLE                         float64
HAZARDOUS_TRUCK                         float64
HIT_BARRIER                             float64
HIT_BRIDGE                              float64
HIT_DEER                                float64
HIT_EMBANKMENT                          float64
HIT_FIXED_OBJECT                        float64
HIT_GDRAIL                              float64
HIT_GDRAIL_END                          float64
HIT_PARKED_VEHICLE                      float64
HIT_POLE                                float64
HIT_TREE_SHRUB                          float64
HO_OPPDIR_SDSWP                         float64
HVY_TRUCK_RELATED                       float64
ICY_ROAD                                float64
ILLEGAL_DRUG_RELATED                    float64
ILLUMINATION_DARK                       float64
IMPAIRED_DRIVER                         float64
INJURY                                  float64
INJURY_OR_FATAL                         float64
INTERSECTION                            float64
INTERSTATE                              float64
LIMIT_65MPH                             float64
LOCAL_ROAD                              float64
LOCAL_ROAD_ONLY                         float64
MAJOR_INJURY                            float64
MC_DRINKING_DRIVER                      float64
MINOR_INJURY                            float64
MODERATE_INJURY                         float64
MOTORCYCLE                              float64
NHTSA_AGG_DRIVING                       float64
NON_INTERSECTION                        float64
NO_CLEARANCE                            float64
OVERTURNED                              float64
PEDESTRIAN                              float64
PHANTOM_VEHICLE                         float64
PROPERTY_DAMAGE_ONLY                    float64
PSP_REPORTED                            float64
REAR_END                                float64
RUNNING_RED_LT                          float64
RUNNING_STOP_SIGN                       float64
SCHOOL_BUS                              float64
SCHOOL_BUS_UNIT                         float64
SCHOOL_ZONE                             float64
SHLDR_RELATED                           float64
SIGNALIZED_INT                          float64
SNOW_SLUSH_ROAD                         float64
SPEEDING                                float64
SPEEDING_RELATED                        float64
STATE_ROAD                              float64
STOP_CONTROLLED_INT                     float64
SUDDEN_DEER                             float64
SV_RUN_OFF_RD                           float64
TAILGATING                              float64
TRAIN                                   float64
TRAIN_TROLLEY                           float64
TROLLEY                                 float64
TURNPIKE                                float64
UNBELTED                                float64
UNDERAGE_DRNK_DRV                       float64
UNLICENSED                              float64
UNSIGNALIZED_INT                        float64
VEHICLE_FAILURE                         float64
VEHICLE_TOWED                           float64
WET_ROAD                                float64
WORK_ZONE                               float64
cnt_road_01_interstate                  float64
cnt_road_02_state                       float64
cnt_road_03_local                       float64
cnt_road_04_other                       float64
cnt_road_segments                       float64
LANE_COUNT_min                          float64
LANE_COUNT_max                          float64
SPEED_LIMIT_nunique                     float64
SPEED_LIMIT_min                         float64
SPEED_LIMIT_max                         float64
model_yr_min                            float64
speed_max                               float64
cnt_hazmat_commveh                        int64
parked_legal_cnt                          int64
parked_illegal_cnt                        int64
non_motorized_cnt                         int64
pedestrian_cnt                            int64
ind_mc_drv_safty_training_N               int64
ind_mc_drv_helmet_N                       int64
ind_mc_passenger_Y                        int64
ind_pc_head_light_N                       int64
ind_pc_helmet_N                           int64
ind_pc_passenger_Y                        int64
ind_pc_rear_reflector_N                   int64
trailer_veh_cnt                           int64
cnt_driver                              float64
drv_age_min                             float64
drv_age_max                             float64
drv_drinking_sum                        float64
drv_drug_sum                            float64
drv_sick_medication_sum                 float64
drv_fatigue_asleep_sum                  float64
drv_no_restraint_helmet_sum             float64
cnt_passenger                           float64
passenger_age_min                       float64
passenger_age_max                       float64
passenger_no_restraint_helmet_sum       float64
cnt_pedestrian                          float64
pedestrian_age_min                      float64
pedestrian_age_max                      float64
pedestrian_drinking_sum                 float64
pedestrian_drug_sum                     float64
pedestrian_sick_medication_sum          float64
pedestrian_fatigue_asleep_sum           float64
pedestrian_loc_int_crosswalk_sum        float64
pedestrian_loc_int_no_crosswalk_sum     float64
pedestrian_loc_in_roadway_sum           float64
pedestrian_loc_shoulder_sidewalk_sum    float64
pedestrian_signal_Y_sum                 float64
pedestrian_signal_N_sum                 float64
pedestrian_signal_not_int_sum           float64
dtype: object